/** Source-bound E01/E02 engineering-instrument projection; never records model outputs. */
import { createHash } from "node:crypto"
import { readFile, writeFile } from "node:fs/promises"
import { createRequire } from "node:module"
const require=createRequire(new URL("../../src/hswm/effect-runtime/package.json",import.meta.url));const {Either}=require("effect") as typeof import("effect")
const {decodeKgBundleSource}=await import("../../src/hswm/effect-runtime/dist/native-kg-bundle-domain.js")
const out="ontology/development/HSWM_LOCAL_SEMANTIC_EXECUTION_INSTRUMENT_2026-09-22.v1.json",sha=(x:Uint8Array|string)=>createHash("sha256").update(x).digest("hex"),uid=(k:string,x:string)=>`sym:${k}:hswm-local-exec-20260922-${sha(x).slice(0,18)}`
const paths=["src/hswm/effect-runtime/src/local-semantic-execution-domain.ts","tests/effect-runtime/local-semantic-execution-domain.test.ts","tests/research/local-semantic-execution-instrument.test.mts","_research/local_semantic_execution_v1/runner.mts","_research/local_semantic_execution_v1/analyze.mts","_research/local_semantic_execution_v1/protocol.v1.json","_research/local_semantic_execution_v1/README.md","_research/local_semantic_execution_v1/launch.sh","_research/local_semantic_execution_v1/graph.mts","docs/operations/artifacts/hswm_local_semantic_execution_2026-09-22/verification.v1.json","_research/jev_research_work_plan_2026-09-22/plan.v1.json","ontology/development/HSWM_JEV_RESEARCH_WORK_PLAN_2026-09-22.v1.json","ontology/development/HSWM_VALIDATION_GRAPH_2026-09-22.v1.json","ontology/development/HSWM_JEV_PRINCIPLES_2026-09-21.v1.json","docs/research/artifacts/hswm_jev_principles_2026-09-21/audit.v1.json","docs/research/artifacts/hswm_jev_principles_2026-09-21/observations.v1.json"]
const bindings=await Promise.all(paths.map(async path=>({path,sha256:sha(await readFile(path))}))),by=new Map(bindings.map(x=>[x.path,x.sha256])),plan=JSON.parse(await readFile("ontology/development/HSWM_JEV_RESEARCH_WORK_PLAN_2026-09-22.v1.json","utf8")),validation=JSON.parse(await readFile("ontology/development/HSWM_VALIDATION_GRAPH_2026-09-22.v1.json","utf8"));const nodes:any[]=[],relations:any[]=[]
const add=(id:string,label:string,role:string,name:string,p:any={})=>{nodes.push({uid:id,labels:label==='AbstractNode'?['Concept','AbstractNode']:[label],properties:{name,description:"Engineering instrument declaration only; no observed model output or efficacy result.",projection_nonclaim:"ENGINEERING_INSTRUMENT_ONLY_NOT_OBSERVED_EVIDENCE_OR_EFFICACY",standard_graph_role:role,authority_class:"SECONDARY_AI",ontology_authority_class_v1:"SECONDARY_AI",ontology_kind_v1:"CONCEPT",ontology_domain_v1:"ENGINEERING",ontology_plane_v1:"RESEARCH_PROJECTION",ontology_canonical_scope_v1:"PENDING",ontology_epistemic_state_v1:"PENDING",ontology_record_lifecycle_v1:"ACTIVE",ontology_review_required_v1:true,ontology_sensitivity_v1:"NORMAL",responsibility_owner:"local_semantic_execution_instrument_2026_09_22",claim_boundary:"ENGINEERING_INSTRUMENT_ONLY",cr_fcl_promotion:false,status:"NOT_RUN",...p,...(p.source_ref?{source_sha256:by.get(p.source_ref)}:{})}});return id};const link=(a:string,t:string,b:string)=>relations.push({from_uid:a,type:t,to_uid:b,authority_class:"SECONDARY_AI",scope:"ENGINEERING_INSTRUMENT_ONLY",status:"NOT_RUN"});const sourceNodes=new Map<string,string>();const source=(p:string)=>sourceNodes.get(p)??(sourceNodes.set(p,add(uid('Reference',p),'Reference','ENGINEERING_SOURCE',p,{source_ref:p,source_path:p})),sourceNodes.get(p)!)
const root="sym:AbstractNode:hswm-local-semantic-execution-instrument-2026-09-22";add(root,'AbstractNode','ENGINEERING_INSTRUMENT','Local semantic execution instrument',{source_ref:"_research/local_semantic_execution_v1/protocol.v1.json",planned_requests:384,case_population:"128_ORIGINAL_CASES_X_E0_E1_E2",e03_readiness:"NOT_READY",full_2784_status:"UNCHANGED_NOT_RUN",local_8001:"REFUSED_DOCUMENTED",dgx_ssh_5s:"TIMEOUT_DOCUMENTED"});for(const p of paths)link(root,'HAS_SOURCE',source(p))
const taskNodes=new Map(plan.nodes.map((n:any)=>[n.properties.task_id,n]));const anchors=['E01','E02','E03'].map(k=>taskNodes.get(k));const local=validation.nodes.find((n:any)=>n.properties.track_id==='LOCAL');if(!local||anchors.some(x=>!x))throw Error('missing prior anchors');const anchorDefs=[...anchors.map((n:any)=>({uid:n.uid,name:n.properties.name,required_labels:n.labels})),{uid:local.uid,name:local.properties.name,required_labels:local.labels}];for(const n of anchors)link(root,'ABOUT',n.uid);link(root,'RELATES_TO',local.uid)
for(const [id,name] of [['E01','E0/E1/E2 execution and parser contract'],['E02','serving denominator and cost recorder']] as const){const n=add(uid('Concept',id),'Concept','PARTIAL_READINESS',name,{source_ref:"_research/local_semantic_execution_v1/protocol.v1.json",task_id:id,readiness:"PARTIAL_INSTRUMENT_PREPARED_MODEL_NOT_RUN"});link(root,'HAS_CONCEPT',n);link(n,'ABOUT',taskNodes.get(id).uid)}
const negative=add(uid('Claim','prior-negative'),'Claim','INHERITED_NEGATIVE_EVIDENCE','Prior 27/48 oracle direct and zero semantic-revision delta',{source_ref:"docs/research/artifacts/hswm_jev_principles_2026-09-21/audit.v1.json",status:"INHERITED_NOT_NEW_MEASUREMENT",oracle_direct:"27/48",semantic_revision_delta:"0"});link(root,'HAS_CONCEPT',negative);const b={schema_version:'hswm-kg-bundle/v1',bundle_uid:root,status:'ENGINEERING_INSTRUMENT_ONLY',nonclaim:'NO_MODEL_RUN_NO_OBSERVED_OUTPUT_NO_E03_READINESS_NO_EFFICACY_OR_CR_FCL_PROMOTION',source_accessed_on:'2026-09-22',authority_boundary:'SECONDARY_AI instrument declaration only',artifact_bindings:bindings,expected_counts:{nodes:nodes.length,anchors:anchorDefs.length,relations:relations.length},anchors:anchorDefs,nodes,relations},bytes=Buffer.from(JSON.stringify(b,null,2)+'\n');Either.getOrThrowWith(decodeKgBundleSource({sourceId:'local-exec',rawBytes:bytes},'v2'),(e:any)=>e);await writeFile(out,bytes,{flag:'wx'});console.log(JSON.stringify({path:out,sha256:sha(bytes),...b.expected_counts}))
