"""Token-native, agent-authored memory and harness self-modification."""

from .contracts import (
    ActiveSnapshot,
    ActivationReceipt,
    CognitiveToken,
    HarnessDocument,
    HarnessMode,
    HarnessNode,
    MemoryRecord,
    MutationProposal,
    SelfModelContractError,
    SelfModelPolicy,
    SelfModelSnapshot,
    make_harness,
    make_mutation,
    make_token,
)
from .runtime import (
    AgentDecision,
    AuthoringRequest,
    EpisodeReceipt,
    ExecutionRequest,
    JsonSelfModifyingAgent,
    SelfModRuntimeError,
    SelfModifyingAgent,
    SelfModifyingHSWM,
)
from .store import (
    IdentityConflictError,
    MissingSourceTokenError,
    SQLiteSelfModelStore,
    SelfModelStoreError,
    StaleGenerationError,
    StoreIntegrityError,
)

__all__ = [
    "ActiveSnapshot",
    "ActivationReceipt",
    "AgentDecision",
    "AuthoringRequest",
    "CognitiveToken",
    "EpisodeReceipt",
    "ExecutionRequest",
    "HarnessDocument",
    "HarnessMode",
    "HarnessNode",
    "IdentityConflictError",
    "JsonSelfModifyingAgent",
    "MemoryRecord",
    "MissingSourceTokenError",
    "MutationProposal",
    "SQLiteSelfModelStore",
    "SelfModRuntimeError",
    "SelfModifyingAgent",
    "SelfModifyingHSWM",
    "SelfModelContractError",
    "SelfModelPolicy",
    "SelfModelSnapshot",
    "SelfModelStoreError",
    "StaleGenerationError",
    "StoreIntegrityError",
    "make_harness",
    "make_mutation",
    "make_token",
]
