/** Create-only source-bound plan projection; it does not execute planned work. */
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../../src/hswm/effect-runtime/package.json', import.meta.url));
const { Either } = require('effect');
const { decodeKgBundleSource } = await import('../../src/hswm/effect-runtime/dist/native-kg-bundle-domain.js');
const sha = (x: Uint8Array | string) => createHash('sha256').update(x).digest('hex');
const planPath = '_research/jev_research_work_plan_2026-09-22/plan.v1.json';
const out = 'ontology/development/HSWM_JEV_RESEARCH_WORK_PLAN_2026-09-22.v1.json';
const plan = JSON.parse(await readFile(planPath, 'utf8')) as any;
const queryPaths = ['plan-root-shape.ttl','ready_roots.rq','task_contracts.rq','dependencies.rq','crosswalk.rq','open_conditions.rq','violations.rq'].map(x => `ontology/queries/hswm_jev_research_work_plan_2026-09-22/${x}`);
const local = [...new Set([...(plan.source_paths ?? []), ...(plan.tasks ?? []).flatMap((t:any) => t.source_paths ?? []), ...(plan.requirements ?? []).map((r:any) => r.source_path), planPath, plan.plan_doc, '_research/jev_research_work_plan_2026-09-22/build.mts', '_research/jev_research_work_plan_2026-09-22/verify-plan.mjs', ...queryPaths, 'schemas/HSWM_KG_BUNDLE_RDF_PROJECTION_SHACL_1_0_V2.ttl', 'schemas/HSWM_NEXT_DEVELOPMENT_PLAN_SHACL_1_0.v1.ttl', 'src/hswm/effect-runtime/package-lock.json'])];
const bindingInfo = await Promise.all(local.map(async (path: string) => { const bytes = await readFile(path); return { path, sha256: sha(bytes), byte_length: bytes.byteLength }; }));
const bindings = bindingInfo.map(({ path, sha256 }) => ({ path, sha256 }));
const uid = (k: string, x: string) => `sym:${k}:hswm-jev-plan-20260922-${x}`;
const nodes: any[] = [], relations: any[] = [];
const add = (id:string,label:string,role:string,name:string,description:string, more:any={}) => { nodes.push({uid:id,labels:label==='AbstractNode'?['Concept','AbstractNode']:[label],properties:{name,description,standard_graph_role:role,authority_class:'SECONDARY_AI',ontology_authority_class_v1:'SECONDARY_AI',ontology_kind_v1:label==='Reference'?'DOCUMENT':'CONCEPT',ontology_domain_v1:'ENGINEERING',ontology_plane_v1:'RESEARCH_PROJECTION',ontology_canonical_scope_v1:'PENDING_OR_PRELIMINARY',ontology_epistemic_state_v1:'PENDING',ontology_record_lifecycle_v1:'ACTIVE',ontology_review_required_v1:true,ontology_sensitivity_v1:'NORMAL',responsibility_owner:'hswm:research-role:jev-work-plan',claim_ceiling:plan.claim_ceiling ?? 'PLANNING_ONLY_NOT_EXECUTION_OR_EFFICACY',claim_boundary:'PLANNING_DELIVERY_NO_WORK_EXECUTED',projection_nonclaim:'NOT_CANONICAL_COGNITION_ROUTING_ADMISSION_OR_LEARNING',cr_fcl_promotion:false,...more}}); return id; };
const link=(from_uid:string,type:string,to_uid:string,scope='SOURCE_BOUND_PLAN')=>relations.push({from_uid,type,to_uid,authority_class:'SECONDARY_AI',scope,status:'PLANNED_NOT_EXECUTED'});
const sourceIds=new Map<string,string>(); const source=(path:string)=>{let id=sourceIds.get(path);if(id)return id;const b=bindingInfo.find(x=>x.path===path);if(!b)throw new Error(`unbound ${path}`);id=add(uid('Reference',sha(path).slice(0,18)),'Reference','ENGINEERING_SOURCE',path,'Exact source bytes.',{source_path:path,source_ref:path,sha256:b.sha256,source_sha256:b.sha256,byte_length:b.byte_length,source_revision:`WORKTREE_CONTENT_SHA256:${b.sha256}`,source_base_commit:plan.source_base_commit});sourceIds.set(path,id);return id;};
const root=add(plan.root_uid ?? 'sym:AbstractNode:hswm-jev-research-work-plan-2026-09-22','AbstractNode','PLAN_ROOT',plan.title ?? 'HSWM JEV research work plan 2026-09-22','Source-bound future-work organization; not execution authorization or evidence.',{source_ref:plan.plan_doc,source_sha256:bindings.find(x=>x.path===plan.plan_doc)?.sha256});
for(const p of local) link(root,'HAS_SOURCE',source(p)); link(root,'DERIVED_FROM',source(plan.plan_doc));
const taskIds=new Map<string,string>(), roleIds=new Map<string,string>(), assIds=new Map<string,string>(), decIds=new Map<string,string>(), reqIds=new Map<string,string>();
for(const a of plan.assumptions ?? []) { const id=add(uid('Assumption',a.id),'Assumption','RESEARCH_ASSUMPTION',a.id,a.contract,{assumption_id:a.id,status:a.status}); assIds.set(a.id,id); }
for(const d of plan.decisions ?? []) { const id=add(uid('Decision',d.id),'Decision','PLAN_DECISION',d.id,d.required_condition,{decision_id:d.id,status:d.status,required_condition:d.required_condition}); decIds.set(d.id,id); }
for(const q of plan.requirements ?? []) { const id=add(uid('Requirement',q.id),'Requirement','AUDIT_REQUIREMENT',q.title,q.title,{requirement_id:q.id,status:'OPEN',source_ref:q.source_path}); link(id,'HAS_SOURCE',source(q.source_path)); reqIds.set(q.id,id); }
const prior = JSON.parse(await readFile('ontology/development/HSWM_SEMANTIC_PROOF_WORK_PLAN_2026-09-15.v1.json','utf8')) as any;
const priorTasks=new Map(prior.nodes.filter((n:any)=>n.properties?.standard_graph_role==='WORK_PACKAGE').map((n:any)=>[n.properties.task_id,n]));
const priorAnchors=new Map(prior.anchors.map((a:any)=>[a.name.split(/[: ]/)[0],a]));
const jev=JSON.parse(await readFile('ontology/development/HSWM_JEV_GRAPH_ENGINEERING_2026-09-22.v1.json','utf8')) as any, deep=JSON.parse(await readFile('ontology/development/HSWM_DEEP_RESEARCH_2026-09-22.v1.json','utf8')) as any;
const finder=(bundle:any,key:string,value:string)=>bundle.nodes.find((n:any)=>n.properties?.[key]===value);
for(const t of plan.tasks ?? []) { const id=add(uid('WorkPackage',t.id),'WorkPackage','WORK_PACKAGE',`${t.id} ${t.title}`,t.output_contract,{task_id:t.id,track:t.track,status:t.status,result_status:t.result_status,task_kind:t.task_kind,failure_action:t.failure_action,planned_output_path:t.planned_output_path,resource_policy:'PLANNING_DELIVERY_NO_WORK_EXECUTED',responsibility_owner:`hswm:research-role:${t.responsibility_role}`,claim_ceiling:t.claim_ceiling});taskIds.set(t.id,id);const rid=roleIds.get(t.responsibility_role)??add(uid('Role',t.responsibility_role),'Role','RESPONSIBILITY_ROLE',t.responsibility_role,'Schema-relative research responsibility role.');roleIds.set(t.responsibility_role,rid);link(id,'HAS_RESPONSIBILITY_ROLE',rid);const input=add(uid('Input',t.id),'Contract','INPUT_CONTRACT',`${t.id} input`,t.input_contract),output=add(uid('Output',t.id),'Artifact','EXPECTED_ARTIFACT',`${t.id} output`,t.output_contract,{status:'NOT_PRODUCED'});link(id,'USES_INPUT',input);link(id,'EXPECTS_OUTPUT',output);for(const c of t.acceptance??[]){const cid=add(uid('Criterion',sha(`${t.id}:${c}`).slice(0,16)),'Criterion','ACCEPTANCE_CRITERION',`${t.id} criterion`,c,{status:'NOT_RUN'});link(id,'HAS_CRITERION',cid);} for(const p of t.source_paths??[]){link(id,'HAS_SOURCE',source(p));}for(const a of t.assumptions??[]){if(!assIds.has(a))throw new Error(`unknown assumption ${a}`);link(id,'TESTS_OR_DEPENDS_ON_ASSUMPTION',assIds.get(a)!);}for(const d of t.required_start_decisions??[]){if(!decIds.has(d))throw new Error(`unknown decision ${d}`);link(id,'REQUIRES_START_DECISION',decIds.get(d)!);}for(const d of t.resolves_decisions??[]){if(!decIds.has(d))throw new Error(`unknown decision ${d}`);link(id,'RESOLVES',decIds.get(d)!);}for(const r of t.requirements??[]){if(!reqIds.has(r))throw new Error(`unknown requirement ${r}`);link(id,'ADDRESSES',reqIds.get(r)!);}link(root,'HAS_CONCEPT',id); }
for(const tool of plan.tools ?? []) { const id=add(uid('Tool',tool.name.replace(/[^A-Za-z0-9_.-]/g,'-')),'Tool','TOOL_PROFILE',tool.name,'Existing pinned local graph tool; no install is requested.',{package_version:tool.version,package_integrity:tool.integrity,license:tool.license,tool_authority_class:tool.authority_class,status:tool.status});link(id,'HAS_SOURCE',source('src/hswm/effect-runtime/package-lock.json'));link(root,'HAS_CONCEPT',id); }
for(const t of plan.tasks??[]){const id=taskIds.get(t.id)!;for(const d of t.hard_dependencies??[]){if(!taskIds.has(d))throw new Error(`unknown dependency ${d}`);link(id,'DEPENDS_ON',taskIds.get(d)!);}for(const p of t.prior_tasks??[]){const n=priorTasks.get(p);if(!n)throw new Error(`unknown prior task ${p}`);link(id,'REUSES_PRIOR_TASK',n.uid,'PRIOR_PLAN_ANCHOR');}for(const p of t.jev_principles??[]){const n=finder(jev,'principle_id',p);if(!n)throw new Error(`unknown principle ${p}`);link(id,'ADDRESSES_JEV_PRINCIPLE',n.uid,'JEV_ANCHOR');}for(const c of t.cr??[]){const a=priorAnchors.get(`CR-${c}`);if(!a)throw new Error(`unknown CR-${c}`);link(id,'ADDRESSES_OBLIGATION',a.uid,'CR_ANCHOR');}for(const f of t.fcl??[]){const a=priorAnchors.get(`FCL-${f}`);if(!a)throw new Error(`unknown FCL-${f}`);link(id,'PRESERVES_FRACTAL_LAW',a.uid,'FCL_ANCHOR');}for(const w of [t.track].filter((x:string)=>/^W[1-5]$/.test(x))){const n=finder(deep,'work_id',w);if(n)link(id,'RELATES_TO',n.uid,'DEEP_W_ANCHOR');}}
for(const a of plan.assumptions??[]){if(!taskIds.has(a.resolver))throw new Error(`unknown resolver ${a.resolver}`);link(assIds.get(a.id)!,'RESOLVED_BY',taskIds.get(a.resolver)!);}for(const d of plan.decisions??[]){if(!taskIds.has(d.resolver))throw new Error(`unknown resolver ${d.resolver}`);link(decIds.get(d.id)!,'RESOLVED_BY',taskIds.get(d.resolver)!);}
for(const n of nodes){const p=n.properties;if(typeof p.source_ref==='string'&&!p.source_ref.startsWith('https://')){const b=bindings.find(x=>x.path===p.source_ref);if(b)p.source_sha256=b.sha256;}}
const anchors=[...new Map([...priorTasks.values(),...jev.nodes.filter((n:any)=>n.properties?.principle_id),...deep.nodes.filter((n:any)=>n.properties?.work_id&&n.properties.standard_graph_role==='RESEARCH_DECISION')].map((n:any)=>[n.uid,{uid:n.uid,name:n.properties.name,required_labels:n.labels}])).values(),...prior.anchors.filter((a:any)=>/^CR-|^FCL-/.test(a.name))];
const bundle={schema_version:'hswm-kg-bundle/v1',bundle_uid:root,status:'PLANNED_NOT_EXECUTED',nonclaim:'SOURCE_BOUND_PLAN_NOT_EXECUTION_AUTHORIZATION_OR_EFFICACY',source_accessed_on:'2026-09-22',artifact_bindings:bindings,expected_counts:{nodes:nodes.length,anchors:anchors.length,relations:relations.length},anchors,nodes,relations};const bytes=Buffer.from(JSON.stringify(bundle,null,2)+'\n');Either.getOrThrowWith(decodeKgBundleSource({sourceId:'jev_plan',rawBytes:bytes},'v2'),(e:any)=>e);await writeFile(out,bytes,{flag:'wx'});console.log(JSON.stringify({path:out,sha256:sha(bytes),...bundle.expected_counts}));
