/** Read-only structural verification for the JEV future-work plan. */
import { readFile, access } from 'node:fs/promises'; import { createRequire } from 'node:module'; import { createHash } from 'node:crypto'; import { resolve, dirname } from 'node:path'; import { pathToFileURL } from 'node:url';
const root=process.cwd(), read=async p=>readFile(resolve(root,p)), sha=x=>createHash('sha256').update(x).digest('hex'), json=async p=>JSON.parse((await read(p)).toString());
const planPath='_research/jev_research_work_plan_2026-09-22/plan.v1.json', bundlePath='ontology/development/HSWM_JEV_RESEARCH_WORK_PLAN_2026-09-22.v1.json', qdir='ontology/queries/hswm_jev_research_work_plan_2026-09-22/';
const [{compileKgBundle},{queryKgBundle,validateKgShacl},{Effect,Either}]=await Promise.all([import(pathToFileURL(resolve(root,'src/hswm/effect-runtime/dist/native-kg-bundle-domain.js')).href),import(pathToFileURL(resolve(root,'src/hswm/effect-runtime/dist/native-kg-standards.js')).href),import(pathToFileURL(resolve(root,'src/hswm/effect-runtime/node_modules/effect/dist/esm/index.js')).href)]);
const check=(v,m)=>{if(!v)throw new Error(m)}, run=e=>Effect.runPromise(e), [plan,bundle]=await Promise.all([json(planPath),json(bundlePath)]);
const verifyBindings=async value=>{for(const b of value.artifact_bindings)check(sha(await read(b.path))===b.sha256,`hash ${b.path}`)}; await verifyBindings(bundle);
const bytes=Buffer.from(JSON.stringify(bundle));const compiled=compileKgBundle([{sourceId:'plan',rawBytes:bytes,sha256:sha(bytes),byteLength:bytes.length}],'v2');check(Either.isRight(compiled),'compile');
for(const s of ['schemas/HSWM_KG_BUNDLE_RDF_PROJECTION_SHACL_1_0_V2.ttl','schemas/HSWM_NEXT_DEVELOPMENT_PLAN_SHACL_1_0.v1.ttl',qdir+'plan-root-shape.ttl'])check((await run(validateKgShacl(compiled.right,await read(s)))).conforms,`shape ${s}`);
const nodes=new Map(bundle.nodes.map(n=>[n.uid,n])), tasks=new Map(bundle.nodes.filter(n=>n.properties.standard_graph_role==='WORK_PACKAGE').map(n=>[n.properties.task_id,n])), rel=(id,type)=>bundle.relations.filter(r=>r.from_uid===id&&r.type===type).map(r=>r.to_uid), same=(a,b,m)=>check(JSON.stringify([...a].sort())===JSON.stringify([...b].sort()),m), props=(id,key)=>rel(id,key).map(x=>nodes.get(x).properties);
check(tasks.size===plan.tasks.length,'task count');for(const t of plan.tasks){const n=tasks.get(t.id);check(n,'missing task '+t.id);check(n.properties.status==='PLANNED'&&n.properties.result_status==='NOT_ASSESSED','false progress '+t.id);check(n.properties.responsibility_owner===`hswm:research-role:${t.responsibility_role}`,'owner '+t.id);same(props(n.uid,'HAS_RESPONSIBILITY_ROLE').map(x=>x.name),[t.responsibility_role],'role '+t.id);same(props(n.uid,'DEPENDS_ON').map(x=>x.task_id),t.hard_dependencies??[],'dependency '+t.id);same(props(n.uid,'REQUIRES_START_DECISION').map(x=>x.decision_id),t.required_start_decisions??[],'start '+t.id);same(props(n.uid,'RESOLVES').map(x=>x.decision_id),t.resolves_decisions??[],'resolve '+t.id);same(props(n.uid,'HAS_SOURCE').map(x=>x.source_path),t.source_paths??[],'source '+t.id);same(props(n.uid,'TESTS_OR_DEPENDS_ON_ASSUMPTION').map(x=>x.assumption_id),t.assumptions??[],'assumption '+t.id);same(props(n.uid,'ADDRESSES').map(x=>x.requirement_id),t.requirements??[],'requirement '+t.id);check(rel(n.uid,'EXPECTS_OUTPUT').every(x=>nodes.get(x).properties.status==='NOT_PRODUCED'),'output '+t.id);check(rel(n.uid,'HAS_CRITERION').every(x=>nodes.get(x).properties.status==='NOT_RUN'),'criterion '+t.id);check(!bundle.relations.some(r=>r.from_uid===n.uid&&r.type==='HAS_ACTUAL_EVIDENCE'),'future evidence '+t.id);}
for(const d of plan.decisions){const n=[...nodes.values()].find(x=>x.properties.decision_id===d.id);check(n&&n.properties.status==='OPEN','decision '+d.id);same(props(n.uid,'RESOLVED_BY').map(x=>x.task_id),[d.resolver],'decision resolver '+d.id);}for(const a of plan.assumptions){const n=[...nodes.values()].find(x=>x.properties.assumption_id===a.id);check(n&&n.properties.status==='UNVERIFIED','assumption '+a.id);same(props(n.uid,'RESOLVED_BY').map(x=>x.task_id),[a.resolver],'assumption resolver '+a.id);}
const initial=plan.tasks.filter(t=>(t.hard_dependencies??[]).length===0&&(t.required_start_decisions??[]).length===0).map(t=>t.id);same(initial,plan.initial_ready_tasks,'initial roots');check(JSON.stringify(plan.initial_ready_tasks)===JSON.stringify(['B00','B01','B02']),'declared roots');const verifyDag=value=>{const decisions=new Map(value.decisions.map(d=>[d.id,d]));const closure=new Map(value.tasks.map(t=>[t.id,[...t.hard_dependencies,...t.required_start_decisions.map(id=>{check(decisions.has(id),`unknown decision ${id}`);return decisions.get(id).resolver})]]));const visiting=new Set(),done=new Set();const visit=id=>{check(closure.has(id),`unknown dependency ${id}`);check(!visiting.has(id),`combined dependency/condition cycle ${id}`);if(done.has(id))return;visiting.add(id);for(const dep of closure.get(id))visit(dep);visiting.delete(id);done.add(id)};for(const id of closure.keys())visit(id)}; verifyDag(plan);
const expectRejected=async(operation,pattern)=>{let rejection;try{await operation()}catch(e){rejection=e}check(rejection&&pattern.test(String(rejection)),`expected rejection ${pattern}`)};

for(const n of bundle.nodes)check(n.properties.cr_fcl_promotion===false,'promotion '+n.uid);const queries=['ready_roots.rq','task_contracts.rq','dependencies.rq','crosswalk.rq','open_conditions.rq','violations.rq'];const results=Object.fromEntries(await Promise.all(queries.map(async q=>[q,await run(queryKgBundle(compiled.right,(await read(qdir+q)).toString()))])));check(results['violations.rq'].length===0,'plan violations');
const lock=await json('src/hswm/effect-runtime/package-lock.json');for(const tool of plan.tools){const p=lock.packages[`node_modules/${tool.name}`];check(p&&p.version===tool.version&&p.integrity===tool.integrity&&p.license===tool.license,'tool pin '+tool.name);}
// Exact crosswalks resolve anchor UIDs against their source bundles.
const [prior,jev,deep]=await Promise.all([json('ontology/development/HSWM_SEMANTIC_PROOF_WORK_PLAN_2026-09-15.v1.json'),json('ontology/development/HSWM_JEV_GRAPH_ENGINEERING_2026-09-22.v1.json'),json('ontology/development/HSWM_DEEP_RESEARCH_2026-09-22.v1.json')]);
check(plan.prior_plan_uid===prior.bundle_uid,'prior plan namespace');
const priorTasks=new Map(prior.nodes.filter(n=>n.properties.standard_graph_role==='WORK_PACKAGE').map(n=>[n.properties.task_id,n]));
const priorAnchors=new Map(prior.anchors.map(a=>[a.name.split(/[: ]/)[0],a]));
const find=(b,key,value)=>{const n=b.nodes.find(n=>n.properties[key]===value);check(n,`source target ${key}:${value}`);return n.uid};
for(const t of plan.tasks){const id=tasks.get(t.id).uid;check(t.prior_plan_uid===plan.prior_plan_uid,`prior namespace ${t.id}`);same(rel(id,'REUSES_PRIOR_TASK'),t.prior_tasks.map(k=>priorTasks.get(k)?.uid),`prior crosswalk ${t.id}`);same(rel(id,'ADDRESSES_JEV_PRINCIPLE'),t.jev_principles.map(k=>find(jev,'principle_id',k)),`Jev crosswalk ${t.id}`);same(rel(id,'ADDRESSES_OBLIGATION'),t.cr.map(k=>priorAnchors.get(`CR-${k}`)?.uid),`CR crosswalk ${t.id}`);same(rel(id,'PRESERVES_FRACTAL_LAW'),t.fcl.map(k=>priorAnchors.get(`FCL-${k}`)?.uid),`FCL crosswalk ${t.id}`);same(rel(id,'RELATES_TO'),/^W[1-5]$/.test(t.track)?[find(deep,'work_id',t.track)]:[],`W crosswalk ${t.id}`);same(props(id,'USES_INPUT').map(p=>p.description),[t.input_contract],`input ${t.id}`);same(props(id,'EXPECTS_OUTPUT').map(p=>p.description),[t.output_contract],`output contract ${t.id}`);same(props(id,'HAS_CRITERION').map(p=>p.description),t.acceptance,`criteria ${t.id}`);check(tasks.get(t.id).properties.claim_ceiling===t.claim_ceiling,`ceiling ${t.id}`);let exists=true;try{await access(resolve(root,t.planned_output_path))}catch(e){if(e.code==='ENOENT')exists=false;else throw e}check(!exists&&t.actual_evidence.length===0,`future output exists ${t.id}`)}
same(new Set(plan.tasks.flatMap(t=>t.prior_tasks)),priorTasks.keys(),'all22 prior tasks');same(new Set(plan.tasks.flatMap(t=>t.jev_principles)),['P1','P2','P3','P4','P5','P6'],'all6 Jev principles');same(new Set(plan.tasks.map(t=>t.track).filter(x=>/^W[1-5]$/.test(x))),['W1','W2','W3','W4','W5'],'all5 work stages');
const boundNodes=new Map();for(const b of bundle.artifact_bindings.filter(b=>b.path.startsWith('ontology/')&&b.path.endsWith('.json'))){const source=await json(b.path);for(const n of source.nodes??[])boundNodes.set(n.uid,n)}for(const a of bundle.anchors){const n=boundNodes.get(a.uid);check(n&&a.required_labels.every(l=>n.labels.includes(l)),`unresolved anchor ${a.uid}`)}
for(const n of bundle.nodes.filter(n=>n.properties.standard_graph_role==='ENGINEERING_SOURCE')){const p=n.properties,b=await read(p.source_path);check(p.sha256===sha(b)&&p.source_sha256===sha(b)&&p.byte_length===b.length,`source property binding ${p.source_path}`)}
for(const tool of plan.tools){const n=bundle.nodes.find(n=>n.properties.standard_graph_role==='TOOL_PROFILE'&&n.properties.name===tool.name),p=n?.properties;check(p&&p.package_version===tool.version&&p.package_integrity===tool.integrity&&p.license===tool.license&&p.tool_authority_class===tool.authority_class,`tool projection ${tool.name}`)}
check(!bundle.relations.some(r=>r.type==='HAS_ACTUAL_EVIDENCE'),'future evidence leakage');same(results['ready_roots.rq'].map(r=>r.taskId.value),plan.initial_ready_tasks,'query ready IDs');
same(results['crosswalk.rq'].map(r=>`${r.taskId.value}|${r.relation.value}|${r.target.value}`),bundle.relations.filter(r=>['REUSES_PRIOR_TASK','ADDRESSES_JEV_PRINCIPLE','ADDRESSES_OBLIGATION','PRESERVES_FRACTAL_LAW','RELATES_TO'].includes(r.type)).map(r=>`${nodes.get(r.from_uid).properties.task_id}|https://hswm.invalid/kg-bundle-rdf/v1/rel/${r.type}|urn:hswm:kg:node:${r.to_uid}`),'queried crosswalk exact edges');
const compileValue=value=>{const raw=Buffer.from(JSON.stringify(value));return compileKgBundle([{sourceId:'bad',rawBytes:raw,sha256:sha(raw),byteLength:raw.length}],'v2')};const bad=structuredClone(bundle);bad.relations.push({from_uid:tasks.values().next().value.uid,to_uid:tasks.values().next().value.uid,type:'DEPENDS_ON',authority_class:'SECONDARY_AI',scope:'negative',status:'INVALID'});bad.expected_counts.relations=bad.relations.length;const c=compileValue(bad),cq=Either.isRight(c)?await run(queryKgBundle(c.right,(await read(qdir+'violations.rq')).toString())):[];check(cq.length>0,'cycle mutation missed');const missingRole=structuredClone(bundle);missingRole.relations=missingRole.relations.filter(r=>!(r.from_uid===tasks.get('B00').uid&&r.type==='HAS_RESPONSIBILITY_ROLE'));missingRole.expected_counts.relations=missingRole.relations.length;const mr=compileValue(missingRole),ms=Either.isRight(mr)?await run(validateKgShacl(mr.right,await read('schemas/HSWM_NEXT_DEVELOPMENT_PLAN_SHACL_1_0.v1.ttl'))):{conforms:true};check(!ms.conforms,'missing role mutation missed');const premature=structuredClone(bundle);premature.nodes.find(n=>n.uid===tasks.get('B00').uid).properties.status='COMPLETE';const pr=compileValue(premature),pq=Either.isRight(pr)?await run(queryKgBundle(pr.right,(await read(qdir+'violations.rq')).toString())):[];check(pq.length>0,'premature completion mutation missed');const corrupt=structuredClone(bundle);corrupt.artifact_bindings[0].sha256='0'.repeat(64);await expectRejected(()=>verifyBindings(corrupt),/hash /);
const deadlocked=structuredClone(plan);deadlocked.tasks.find(t=>t.id==='B01').required_start_decisions=['D-MODEL'];await expectRejected(()=>verifyDag(deadlocked),/combined dependency\/condition cycle/);
// Native failed-report formatter does not serialize null resultPath from node-level
// class violations. Inspect the same pinned validator's actual boolean directly;
// an adapter exception is never counted as a successful negative test.
const require=createRequire(resolve(root,'src/hswm/effect-runtime/package.json'));
const {Parser,Store,DataFactory}=require('n3');
const {loadKgVendorEngines}=await import(pathToFileURL(resolve(root,'src/hswm/effect-runtime/dist/native-kg-vendor.js')).href);
const {SHACLValidator}=await run(loadKgVendorEngines);
const shapeStore=new Store(new Parser({format:'Turtle'}).parse((await read(qdir+'plan-root-shape.ttl')).toString()));
const validator=()=>new SHACLValidator(shapeStore,{importGraph:()=>Promise.reject(new Error('imports forbidden'))});
const union=p=>new Store(new Parser({format:'N-Quads'}).parse(Buffer.from(p.nquads).toString()).map(q=>DataFactory.quad(q.subject,q.predicate,q.object)));
check((await validator().validate(union(compiled.right))).conforms,'root positive control');
const noRootRole=structuredClone(bundle);noRootRole.nodes.find(n=>n.uid===bundle.bundle_uid).properties.standard_graph_role='UNRELATED_ROOT';const nr=compileValue(noRootRole);check(Either.isRight(nr),'root mutation compile');check(!(await validator().validate(union(nr.right))).conforms,'root role mutation missed');check(!(await validator().validate(new Store())).conforms,'empty graph mutation missed');
console.log(JSON.stringify({status:'PASS',counts:bundle.expected_counts,artifact_bindings:bundle.artifact_bindings.length,ready_tasks:plan.initial_ready_tasks,crosswalk:{prior_tasks:22,jev_principles:6,work_stages:5,anchors_resolved:bundle.anchors.length},queries:Object.fromEntries(Object.entries(results).map(([k,v])=>[k,v.length])),negative_probes:['CYCLE_DETECTED','MISSING_ROLE_REJECTED','PREMATURE_COMPLETE_DETECTED','SOURCE_HASH_CORRUPTION_DETECTED','CONDITION_DEADLOCK_DETECTED','NONVACUOUS_ROOT_ROLE_DETECTED','EMPTY_GRAPH_REJECTED'],limitation:'Root negative SHACL reports use the same pinned engine directly because the native failed-report formatter cannot serialize a null resultPath. No engine exception counts as passing.'}));
