import { expect, it } from "@effect/vitest"
import { Either } from "effect"
import { createHash } from "node:crypto"

import { canonicalAtomV2EnvelopeBytes, snapshotCanonicalAtomV2WriteContentBinding } from "../src/canonical-atom-v2-content-bound.js"
import { initialCanonicalAtomV2State, makeCanonicalAtomV2AcceptedReceipt } from "../src/canonical-atom-v2-domain.js"
import { canonicalAtomV2KeyId, type CanonicalAtomV2, type CanonicalAtomV2Key, type CommitCanonicalAtomsV2Command } from "../src/canonical-atom-v2-schema.js"
import { applyCanonicalAtomV2StateJournalCommit, canonicalAtomV2StateJournalRecordBytes, describeCanonicalAtomV2StateJournalRecord, makeCanonicalAtomV2StateJournalCommit, makeCanonicalAtomV2StateJournalGenesis } from "../src/canonical-atom-v2-state-journal.js"
import { DNRD5_V2_OWNER_ROLE_BY_KIND, DNRD5_V2_REFERENCE_TYPE, DNRD5_V2_SCHEMA_VERSION, makeDnrd5V2CanonicalSchema, type Dnrd5V2CanonicalAtomKind } from "../src/canonical-atom-v2-dnrd5-v2-schema.js"
import { validateDnrd5V2AuditRelease } from "../src/canonical-atom-v2-dnrd5-v2-audit-release.js"

const right = <A, E>(v: Either.Either<A, E>): A => { if (Either.isLeft(v)) throw new Error(JSON.stringify(v.left)); return v.right }
const schema = makeDnrd5V2CanonicalSchema(), sha = (x: string) => x.repeat(64)
const key = (atomUid: string): CanonicalAtomV2Key => ({ schemaVersion: DNRD5_V2_SCHEMA_VERSION, lineageId: "lineage:audit-release", atomUid, revisionId: 0 })
const atom = (uid: string, kind: Dnrd5V2CanonicalAtomKind): CanonicalAtomV2 => ({ _tag: "CanonicalAtomV2", contractVersion: "hswm-canonical-atom/v2", key: key(uid), kind: `hswm:dnrd5:v2:${kind}`, responsibilityOwner: `owner:dnrd5:v2:${DNRD5_V2_OWNER_ROLE_BY_KIND[kind]}`, content: { mediaType: "application/json", byteLength: 2, sha256: sha("a") }, provenance: { mode: "BOOTSTRAP", evidenceSha256: sha("b"), sourceRef: null }, lifecycle: "ADMITTED", references: [] })
const rel = (uid: string, kind: Dnrd5V2CanonicalAtomKind, pairs: ReadonlyArray<readonly [string, CanonicalAtomV2]>): CanonicalAtomV2 => ({ ...atom(uid, kind), provenance: { mode: "DERIVATION", evidenceSha256: sha("b"), sourceRef: pairs[0]![1].key }, references: pairs.map(([role, source]) => ({ referenceType: DNRD5_V2_REFERENCE_TYPE, role: `role:dnrd5:v2:${role}`, target: source.key })) })
const command = (revision: number, writes: ReadonlyArray<CanonicalAtomV2>, readSet: ReadonlyArray<CanonicalAtomV2Key>, id = `transition:audit:${revision}`): CommitCanonicalAtomsV2Command => ({ _tag: "CommitCanonicalAtomsV2", contractVersion: "hswm-canonical-transition/v2", transitionId: id, expectedStateRevision: revision, schemaVersion: DNRD5_V2_SCHEMA_VERSION, actorClaim: "principal:test", authorizationRef: "authorization:test", scope: "scope:test", decidedAt: "2026-08-28T12:00:00.000Z", traceRef: null, readSet, writes, provenanceSha256: sha("c") })
const bind = (writes: ReadonlyArray<CanonicalAtomV2>) => { const sorted = [...writes].sort((a, b) => canonicalAtomV2KeyId(a.key).localeCompare(canonicalAtomV2KeyId(b.key))), bytes = sorted.map((a) => right(canonicalAtomV2EnvelopeBytes(a))); return { bytes, bindings: sorted.map((a, i) => snapshotCanonicalAtomV2WriteContentBinding({ key: a.key, payload: a.content, envelope: { mediaType: "application/vnd.hswm.canonical-atom-v2+json", byteLength: bytes[i]!.byteLength, sha256: createHash("sha256").update(bytes[i]!).digest("hex") } })) } }
const leftCode = <A, E extends { readonly code: string }>(value: Either.Either<A, E>) => { expect(Either.isLeft(value)).toBe(true); return Either.isLeft(value) ? value.left.code : "RIGHT" }

it("replays a real delayed-audit journal record and rejects forged scope, pairing, bytes, and replay", () => {
  const randomness = atom("randomness", "study_randomness"), alternateRandomness = atom("alternate-randomness", "study_randomness"), evaluator = atom("evaluator", "evaluator_commitment"), alternateEvaluator = atom("alternate-evaluator", "evaluator_commitment"), policy = atom("policy", "permit_policy"), alternatePolicy = atom("alternate-policy", "permit_policy"), projectionPolicy = atom("projection-policy", "projection_policy")
  const block = rel("block", "block_spec", [["randomness", randomness], ["evaluator", evaluator]]), authorization = rel("authorization", "authorization_decision", [["policy", policy]]), capability = rel("capability", "capability_issuance", [["authorization", authorization], ["policy", policy]]), revocation = rel("revocation", "revocation_status", [["authorization", authorization], ["capability", capability]])
  const alternateAuthorization = rel("alternate-authorization", "authorization_decision", [["policy", alternatePolicy]]), alternateCapability = rel("alternate-capability", "capability_issuance", [["authorization", alternateAuthorization], ["policy", alternatePolicy]])
  const alternateBlock = rel("alternate-block", "block_spec", [["randomness", randomness], ["evaluator", evaluator]]), w0 = rel("w0-real", "w0_snapshot", [["block-spec", block]]), alternateW0 = rel("w0-alternate", "w0_snapshot", [["block-spec", alternateBlock]]), forks = [1, 2, 3, 4].map((n) => rel(`real-fork${n}`, "fork_incidence", [["w0", w0]])), alternateForks = [1, 2, 3, 4].map((n) => rel(`alternate-fork${n}`, "fork_incidence", [["w0", alternateW0]]))
  const assignmentReal = rel("assignment-real", "block_assignment", [["randomness", randomness], ["block-spec", block], ...forks.map((fork) => ["fork", fork] as const)])
  const auditCapability = rel("audit-capability", "audit_release_capability", [["block", block], ["commitment", evaluator], ["policy", policy], ["authorization", authorization], ["capability", capability], ["revocation", revocation]]), alternateAuditCapability = rel("alternate-audit-capability", "audit_release_capability", [["block", block], ["commitment", alternateEvaluator], ["policy", policy], ["authorization", authorization], ["capability", capability], ["revocation", revocation]])
  const evaluatorCapability = rel("evaluator-capability", "evaluator_capability", [["commitment", evaluator], ["capability", capability], ["authorization", authorization], ["revocation", revocation]]), alternateEvaluatorCapability = rel("alternate-evaluator-capability", "evaluator_capability", [["commitment", alternateEvaluator], ["capability", capability], ["authorization", authorization], ["revocation", revocation]])
  const mainProbe = rel("probe-main", "probe_commitment", [["block-spec", block], ["randomness", randomness]]), alternateProbe = rel("probe-alternate", "probe_commitment", [["block-spec", block], ["randomness", alternateRandomness]])
  const activation = rel("activation", "episode_activation", [["block-spec", block], ["probe", mainProbe], ["w0", w0], ...forks.map((fork) => ["fork", fork] as const), ["assignment", assignmentReal], ["evaluator", evaluator]])
  const alternateActivation = rel("alternate-activation", "episode_activation", [["block-spec", block], ["probe", mainProbe], ["w0", w0], ...forks.map((fork) => ["fork", fork] as const), ["assignment", assignmentReal], ["evaluator", evaluator]])
  const contract = rel("contract", "trajectory_contract", [["activation", activation]])
  const trajectorySeal = rel("trajectory-seal", "trajectory_seal", [["activation", activation], ["contract", contract], ["w0", w0]])
  const probes = [1, 2, 3, 4].map((n) => rel(`probe${n}`, "probe_commitment", [["block-spec", block], ["randomness", randomness]])); const projections = probes.map((_, n) => rel(`projection${n + 1}`, "behavior_projection", [["source", w0], ["policy", projectionPolicy]])); const probeTrajectories = probes.map((probe, n) => rel(`probe-trajectory${n + 1}`, "probe_trajectory", [["probe", probe], ["projection", projections[n]!]]))
  const releases = probeTrajectories.map((trajectory, n) => rel(`release${n + 1}`, "evaluator_release", [["trajectory", trajectory], ["capability", evaluatorCapability], ["authorization", authorization], ["revocation", revocation]]))
  const hiddenRelease = rel("hidden-release", "evaluator_release", [["trajectory", trajectorySeal], ["capability", evaluatorCapability], ["authorization", authorization], ["revocation", revocation]])
  const hidden = rel("hidden", "hidden_outcome", [["trajectory", trajectorySeal], ["release", hiddenRelease], ["commitment", evaluator]]), escrow = rel("escrow", "outcome_credit_escrow", [["outcome", hidden], ["capability", capability], ["policy", policy]])
  const probeOutcomes = probes.map((probe, n) => rel(`probe-outcome${n + 1}`, "probe_outcome", [["trajectory", probeTrajectories[n]!], ["release", releases[n]!], ["probe", probe]]))
  const genesis = right(makeCanonicalAtomV2StateJournalGenesis("journal:audit-release", schema)), genesisDescriptor = right(describeCanonicalAtomV2StateJournalRecord(genesis))
  const bootstrapWrites = [randomness, alternateRandomness, evaluator, alternateEvaluator, policy, alternatePolicy, projectionPolicy, block, alternateBlock, authorization, alternateAuthorization, capability, alternateCapability, revocation, w0, alternateW0, ...forks, ...alternateForks, assignmentReal, auditCapability, alternateAuditCapability, evaluatorCapability, alternateEvaluatorCapability, mainProbe, alternateProbe, activation, alternateActivation, contract, trajectorySeal, ...releases, hiddenRelease, hidden, escrow, ...probes, ...projections, ...probeTrajectories, ...probeOutcomes]
  const bootstrap = command(0, bootstrapWrites, []), bootstrapBound = bind(bootstrap.writes), bootstrapRecord = right(makeCanonicalAtomV2StateJournalCommit(schema, { state: initialCanonicalAtomV2State(DNRD5_V2_SCHEMA_VERSION), descriptor: genesisDescriptor, journalLineageId: genesis.journalLineageId, schema: genesis.schema }, makeCanonicalAtomV2AcceptedReceipt(bootstrap, 0, 1), bootstrapBound.bindings, bootstrapBound.bytes)), pre = right(applyCanonicalAtomV2StateJournalCommit(schema, { state: initialCanonicalAtomV2State(DNRD5_V2_SCHEMA_VERSION), descriptor: genesisDescriptor, journalLineageId: genesis.journalLineageId, schema: genesis.schema }, bootstrapRecord, bootstrapBound.bytes))
  // Grant is deliberately a separate predecessor record, so the audit commit
  // exercises an actual chronological journal rather than a caller label.
  const grantAtom = rel("grant", "grant_snapshot", [["policy", policy], ["authorization", authorization], ["capability", capability], ["revocation", revocation]])
  const grantCommit = command(1, [grantAtom], [policy.key, authorization.key, capability.key, revocation.key], "transition:audit:grant"), grantBound = bind(grantCommit.writes), grantRecord = right(makeCanonicalAtomV2StateJournalCommit(schema, { state: pre.state, descriptor: pre.descriptor, journalLineageId: genesis.journalLineageId, schema: genesis.schema }, makeCanonicalAtomV2AcceptedReceipt(grantCommit, 1, 2), grantBound.bindings, grantBound.bytes)), granted = right(applyCanonicalAtomV2StateJournalCommit(schema, { state: pre.state, descriptor: pre.descriptor, journalLineageId: genesis.journalLineageId, schema: genesis.schema }, grantRecord, grantBound.bytes))
  const evidenceReal = rel("audit-evidence-real", "evidence_seal_consumption", [["grant", grantAtom], ["capability", capability], ["revocation", revocation], ["purpose", auditCapability]])
  const audit = rel("audit", "audit_release", [["block", block], ["assignment", assignmentReal], ["outcome", hidden], ["escrow", escrow], ...probeTrajectories.map((x) => ["probe-trajectory", x] as const), ...probeOutcomes.map((x) => ["probe-outcome", x] as const), ["evaluator-capability", evaluatorCapability], ["release-capability", auditCapability], ...releases.map((x) => ["evaluator-release", x] as const), ["evidence-consumption", evidenceReal]])
  const reads = [...evidenceReal.references, ...audit.references].map((r) => r.target).filter((value) => canonicalAtomV2KeyId(value) !== canonicalAtomV2KeyId(evidenceReal.key)).filter((value, index, all) => all.findIndex((other) => canonicalAtomV2KeyId(other) === canonicalAtomV2KeyId(value)) === index)
  const auditCommand = command(2, [audit, evidenceReal], reads, "transition:audit:release"), auditBound = bind(auditCommand.writes), auditRecord = right(makeCanonicalAtomV2StateJournalCommit(schema, { state: granted.state, descriptor: granted.descriptor, journalLineageId: genesis.journalLineageId, schema: genesis.schema }, makeCanonicalAtomV2AcceptedReceipt(auditCommand, 2, 3), auditBound.bindings, auditBound.bytes)), auditBytes = right(canonicalAtomV2StateJournalRecordBytes(auditRecord)), auditDescriptor = right(describeCanonicalAtomV2StateJournalRecord(auditRecord))
  const input = { schema, preState: granted.state, predecessor: { descriptor: granted.descriptor, journalLineageId: genesis.journalLineageId, schemaContentSha256: genesis.schema.content.sha256 }, command: auditCommand, record: auditRecord, recordBytes: auditBytes, recordDescriptor: auditDescriptor, envelopes: auditBound.bytes, usedAuditReleaseRecordDescriptorSha256s: [] }
  expect(right(validateDnrd5V2AuditRelease(input)).status).toBe("RAW_AUDIT_RELEASE_STRUCTURALLY_VALIDATED_NOT_PERMIT_OR_OCCURRENCE")
  const wrongPurpose = { ...evidenceReal, references: evidenceReal.references.map((r) => r.role.endsWith(":purpose") ? { ...r, target: capability.key } : r) }
  expect(Either.isLeft(validateDnrd5V2AuditRelease({ ...input, command: { ...auditCommand, writes: [audit, wrongPurpose] } }))).toBe(true)
  const badAudit = { ...audit, references: audit.references.map((r) => canonicalAtomV2KeyId(r.target) === canonicalAtomV2KeyId(probeOutcomes[0]!.key) ? { ...r, target: probeOutcomes[1]!.key } : r) }
  expect(Either.isLeft(validateDnrd5V2AuditRelease({ ...input, command: { ...auditCommand, writes: [badAudit, evidenceReal] } }))).toBe(true)
  const crossWire = (uid: string, mutate: (value: CanonicalAtomV2) => CanonicalAtomV2) => ({ ...granted.state, atoms: granted.state.atoms.map((value) => value.key.atomUid === uid ? mutate(value) : value) })
  const releaseCrossWire = crossWire("release1", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":capability") ? { ...r, target: alternateEvaluatorCapability.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: releaseCrossWire }))).toBe("CROSS_LINK_INVALID")
  const probeCrossWire = crossWire("probe-outcome1", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":probe") ? { ...r, target: probes[1]!.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: probeCrossWire }))).toBe("CROSS_LINK_INVALID")
  const hiddenCrossWire = crossWire("hidden-release", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":capability") ? { ...r, target: alternateEvaluatorCapability.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: hiddenCrossWire }))).toBe("CROSS_LINK_INVALID")
  const internallyCrosswiredAuthority = crossWire("capability", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":authorization") ? { ...r, target: alternateAuthorization.key } : r.role.endsWith(":policy") ? { ...r, target: alternatePolicy.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: internallyCrosswiredAuthority }))).toBe("CROSS_LINK_INVALID")
  // These alternates are all schema-valid: they only become invalid when the
  // delayed audit tries to splice a different evaluator authority into this block.
  const alternateEvidence = { ...evidenceReal, references: evidenceReal.references.map((r) => r.role.endsWith(":purpose") ? { ...r, target: alternateAuditCapability.key } : r) }
  const alternateAudit = { ...audit, references: audit.references.map((r) => r.role.endsWith(":release-capability") ? { ...r, target: alternateAuditCapability.key } : r.role.endsWith(":evaluator-capability") ? { ...r, target: alternateEvaluatorCapability.key } : r) }
  const alternateReads = [...alternateEvidence.references, ...alternateAudit.references].map((r) => r.target).filter((value) => canonicalAtomV2KeyId(value) !== canonicalAtomV2KeyId(alternateEvidence.key)).filter((value, index, all) => all.findIndex((other) => canonicalAtomV2KeyId(other) === canonicalAtomV2KeyId(value)) === index)
  const alternateAuthorityState = { ...granted.state, atoms: granted.state.atoms.map((value) => value.kind === "hswm:dnrd5:v2:evaluator_release" ? { ...value, references: value.references.map((r) => r.role.endsWith(":capability") ? { ...r, target: alternateEvaluatorCapability.key } : r) } : value) }
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: alternateAuthorityState, command: command(2, [alternateAudit, alternateEvidence], alternateReads, "transition:audit:alternate-authority") }))).toBe("CROSS_LINK_INVALID")
  const assignmentForkScope = crossWire("assignment-real", (value) => { let index = 0; return { ...value, references: value.references.map((r) => r.role.endsWith(":fork") ? { ...r, target: alternateForks[index++]!.key } : r) } })
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: assignmentForkScope }))).toBe("CROSS_LINK_INVALID")
  const forkW0Scope = crossWire("real-fork1", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":w0") ? { ...r, target: alternateW0.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: forkW0Scope }))).toBe("CROSS_LINK_INVALID")
  const activationW0Scope = crossWire("activation", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":w0") ? { ...r, target: alternateW0.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: activationW0Scope }))).toBe("CROSS_LINK_INVALID")
  const activationEvaluatorScope = crossWire("activation", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":evaluator") ? { ...r, target: alternateEvaluator.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: activationEvaluatorScope }))).toBe("CROSS_LINK_INVALID")
  const activationProbeRandomnessScope = crossWire("activation", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":probe") ? { ...r, target: alternateProbe.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: activationProbeRandomnessScope }))).toBe("CROSS_LINK_INVALID")
  const trajectoryW0Scope = crossWire("trajectory-seal", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":w0") ? { ...r, target: alternateW0.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: trajectoryW0Scope }))).toBe("CROSS_LINK_INVALID")
  const trajectoryContractScope = crossWire("contract", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":activation") ? { ...r, target: alternateActivation.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: trajectoryContractScope }))).toBe("CROSS_LINK_INVALID")
  const probeRandomnessScope = crossWire("probe1", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":randomness") ? { ...r, target: alternateRandomness.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: probeRandomnessScope }))).toBe("CROSS_LINK_INVALID")
  const repeatedUnderlyingProbeScope = { ...granted.state, atoms: granted.state.atoms.map((value) => value.key.atomUid === "probe-trajectory2" ? { ...value, references: value.references.map((r) => r.role.endsWith(":probe") ? { ...r, target: probes[0]!.key } : r) } : value.key.atomUid === "probe-outcome2" ? { ...value, references: value.references.map((r) => r.role.endsWith(":probe") ? { ...r, target: probes[0]!.key } : r) } : value) }
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: repeatedUnderlyingProbeScope }))).toBe("CROSS_LINK_INVALID")
  const assignmentRandomnessScope = crossWire("assignment-real", (value) => ({ ...value, references: value.references.map((r) => r.role.endsWith(":randomness") ? { ...r, target: alternateRandomness.key } : r) }))
  expect(leftCode(validateDnrd5V2AuditRelease({ ...input, preState: assignmentRandomnessScope }))).toBe("CROSS_LINK_INVALID")
  expect(Either.isLeft(validateDnrd5V2AuditRelease({ ...input, recordBytes: Uint8Array.from([...auditBytes, 0]) }))).toBe(true)
  expect(Either.isLeft(validateDnrd5V2AuditRelease({ ...input, usedAuditReleaseRecordDescriptorSha256s: [auditDescriptor.sha256] }))).toBe(true)
})
