import { expect, it } from "@effect/vitest"
import { Either } from "effect"
import { makeCanonicalAtomV2ContentDescriptor } from "../src/canonical-atom-v2-content.js"
import { canonicalJsonBytes, canonicalJsonSha256 } from "../src/canonical-atom-v2-json.js"
import { validateDnrd5RestoreProjectionBytes } from "../src/canonical-atom-v2-dnrd5-restore.js"
import { validateDnrd5W0ForkManifestBytes } from "../src/canonical-atom-v2-dnrd5-w0.js"

const enc = new TextEncoder(); const sha = (x: string) => x.repeat(64); const d = (x: string) => ({ mediaType: "application/json", byteLength: 1, sha256: sha(x) })
const describe = (mediaType: string, core: unknown) => { const b = canonicalJsonBytes(core); const h = canonicalJsonSha256(core); if (Either.isLeft(b) || Either.isLeft(h)) throw new Error("hash"); return { mediaType, byteLength: b.right.byteLength, sha256: h.right } }
const put = (map: Map<string, Uint8Array>, bytes: Uint8Array, mediaType = "application/octet-stream") => { const x = makeCanonicalAtomV2ContentDescriptor(mediaType, bytes); if (Either.isLeft(x)) throw new Error(x.left.detail); map.set(x.right.sha256, bytes); return x.right }
const canonPut = (map: Map<string, Uint8Array>, value: unknown) => { const x = canonicalJsonBytes(value); if (Either.isLeft(x)) throw new Error(x.left.detail); return put(map, x.right, "application/json") }

const fixture = () => {
  const content = new Map<string, Uint8Array>(); const state = put(content, enc.encode("w0-state")); const readset = put(content, enc.encode("w0-readset")); const journal = put(content, enc.encode("w0-journal")); const policy = put(content, enc.encode("projection-policy"));
  const manifest: any = { _tag: "Dnrd5W0ForkManifest", contractVersion: "hswm-dnrd5-w0-four-fork-identity/v1", blockId: "DNRD5-BLOCK-0001", w0: { w0Id: "w0:block:0001", state, behaviorReadset: readset, journalHead: journal, projectionPolicy: policy }, forks: [0, 1, 2, 3].map((n) => ({ opaqueForkId: `opaque:fork:${n}`, w0Id: "w0:block:0001", state, behaviorReadset: readset, isolationReceipt: put(content, enc.encode(`isolation:${n}`)), assignmentStatus: "UNASSIGNED" })), terminal: "CALLER_SUPPLIED_CONTENT_MAP_NOT_DURABLE_RECOVERY_OR_ISOLATION_PROOF" }
  const mb = canonicalJsonBytes(manifest); if (Either.isLeft(mb)) throw new Error(mb.left.detail); const identity = validateDnrd5W0ForkManifestBytes(mb.right, content); if (Either.isLeft(identity)) throw new Error(identity.left.detail)
  const restore = { w0Snapshot: state, expectedRootSha256: state.sha256, expectedReadsetSha256: readset.sha256, restorePolicy: policy }
  const permit: any = { _tag: "Dnrd5LocalExperimentalPermitInput", contractVersion: "hswm-dnrd5-local-experimental-state-permit/v1", domain: "LOCAL_NON_HUMAN_EXPERIMENTAL_STATE", evaluatedAt: "2026-08-28T00:00:01.000Z", effect: "RESTORE_W0", snapshot: { journalLineageId: "lineage:one", journalHead: journal, stateRevision: 1, stateSha256: state.sha256 }, principals: { actor: "p:actor", authorizer: "p:authorizer", canonicalStateCustodian: "p:state", restoreCustodian: "p:restore", creditAdjudicator: "p:credit", authorizationDecisionRecordCustodian: "p:record", validator: "p:validator", provenanceSealer: "p:provenance", trajectorySealer: "p:trajectory" }, policy: { descriptor: d("c"), scope: "scope:one", allowedEffects: ["RESTORE_W0"], allowedActors: ["p:actor"], validator: d("8"), validatorPrincipal: "p:validator", allowedReadKindsSha256: sha("d"), allowedWriteKindsSha256: sha("e"), allowedTargetKindsSha256: sha("f"), exactReadsetSha256: sha("1"), exactWritesetSha256: sha("2"), exactTargetAtomKeysSha256: sha("b"), restore }, authorizationDecision: { descriptor: d("7"), decision: "GRANTED", actor: "p:actor", authorizer: "p:authorizer", recordCustodian: "p:record", effect: "RESTORE_W0", scope: "scope:one", decidedAt: "2026-08-28T00:00:00.000Z", notBefore: "2026-08-28T00:00:00.500Z", expiresAt: "2026-08-28T00:02:00.000Z", generation: 1 }, capability: { issuance: d("3"), capabilityId: "cap:one", issuedAt: "2026-08-28T00:00:00.500Z", expiresAt: "2026-08-28T00:01:00.000Z", scope: "scope:one", allowedEffect: "RESTORE_W0", oneShotNonceSha256: sha("4"), policy: d("c"), authorization: d("7"), authorizationGeneration: 1, capabilityGeneration: 2 }, currentRevocation: { descriptor: d("5"), checkedAt: "2026-08-28T00:00:01.000Z", status: "CHECKED_NOT_REVOKED", authorization: d("7"), capability: d("3"), authorizationGeneration: 1, capabilityGeneration: 2 }, grantSnapshot: { descriptor: d("6"), policy: d("c"), authorization: d("7"), capability: d("3"), revocation: d("5"), snapshotSha256: "" }, transition: { command: d("9"), readKindsSha256: sha("d"), writeKindsSha256: sha("e"), targetKindsSha256: sha("f"), readsetSha256: sha("1"), writesetSha256: sha("2"), targetAtomKeysSha256: sha("b"), validator: d("8"), validatorPrincipal: "p:validator", provenance: d("d"), provenanceSealer: "p:provenance", trajectoryContract: d("e"), trajectorySeal: d("f"), trajectorySealer: "p:trajectory" }, restore }
  const rehash = () => { permit.policy.descriptor = describe("application/vnd.hswm.dnrd5.local-experimental-permit-policy-v1+json", { scope: permit.policy.scope, allowedEffects: permit.policy.allowedEffects, allowedActors: permit.policy.allowedActors, validator: permit.policy.validator, validatorPrincipal: permit.policy.validatorPrincipal, allowedReadKindsSha256: permit.policy.allowedReadKindsSha256, allowedWriteKindsSha256: permit.policy.allowedWriteKindsSha256, allowedTargetKindsSha256: permit.policy.allowedTargetKindsSha256, exactReadsetSha256: permit.policy.exactReadsetSha256, exactWritesetSha256: permit.policy.exactWritesetSha256, exactTargetAtomKeysSha256: permit.policy.exactTargetAtomKeysSha256, restore: permit.policy.restore }); permit.authorizationDecision.descriptor = describe("application/vnd.hswm.dnrd5.local-experimental-authorization-decision-v1+json", { decision: permit.authorizationDecision.decision, actor: permit.authorizationDecision.actor, authorizer: permit.authorizationDecision.authorizer, recordCustodian: permit.authorizationDecision.recordCustodian, effect: permit.authorizationDecision.effect, scope: permit.authorizationDecision.scope, decidedAt: permit.authorizationDecision.decidedAt, notBefore: permit.authorizationDecision.notBefore, expiresAt: permit.authorizationDecision.expiresAt, generation: permit.authorizationDecision.generation }); permit.capability.issuance = describe("application/vnd.hswm.dnrd5.local-experimental-capability-v1+json", { capabilityId: permit.capability.capabilityId, issuedAt: permit.capability.issuedAt, expiresAt: permit.capability.expiresAt, scope: permit.capability.scope, allowedEffect: permit.capability.allowedEffect, oneShotNonceSha256: permit.capability.oneShotNonceSha256, policy: permit.capability.policy, authorization: permit.capability.authorization, authorizationGeneration: permit.capability.authorizationGeneration, capabilityGeneration: permit.capability.capabilityGeneration }); permit.currentRevocation.descriptor = describe("application/vnd.hswm.dnrd5.local-experimental-revocation-v1+json", { checkedAt: permit.currentRevocation.checkedAt, status: permit.currentRevocation.status, authorization: permit.currentRevocation.authorization, capability: permit.currentRevocation.capability, authorizationGeneration: permit.currentRevocation.authorizationGeneration, capabilityGeneration: permit.currentRevocation.capabilityGeneration }); permit.grantSnapshot.descriptor = describe("application/vnd.hswm.dnrd5.local-experimental-grant-snapshot-v1+json", { policy: permit.grantSnapshot.policy, authorization: permit.grantSnapshot.authorization, capability: permit.grantSnapshot.capability, revocation: permit.grantSnapshot.revocation }); permit.grantSnapshot.snapshotSha256 = permit.grantSnapshot.descriptor.sha256 }
  rehash(); permit.capability.policy = permit.policy.descriptor; permit.capability.authorization = permit.authorizationDecision.descriptor; rehash(); permit.currentRevocation.authorization = permit.authorizationDecision.descriptor; permit.currentRevocation.capability = permit.capability.issuance; rehash(); permit.grantSnapshot.policy = permit.policy.descriptor; permit.grantSnapshot.authorization = permit.authorizationDecision.descriptor; permit.grantSnapshot.capability = permit.capability.issuance; permit.grantSnapshot.revocation = permit.currentRevocation.descriptor; rehash()
  const behaviorUids = ["behavior:a", "behavior:z"], auditOnlyUids = ["audit:x"]
  const projection = canonPut(content, { _tag: "Dnrd5BehaviorProjection", blockId: manifest.blockId, sourceStateSha256: state.sha256, projectionPolicySha256: policy.sha256, behaviorUids, auditOnlyUids, terminal: "CALLER_SUPPLIED_PROJECTION_NOT_NONTRAVERSABILITY_PROOF" })
  const permitInputHash = canonicalJsonSha256(permit)
  if (Either.isLeft(permitInputHash)) throw new Error(permitInputHash.left.detail)
  const permitResolution = canonicalJsonSha256({ contractVersion: "hswm-dnrd5-local-experimental-state-permit/v1", domain: "LOCAL_NON_HUMAN_EXPERIMENTAL_STATE", effect: "RESTORE_W0", snapshot: permit.snapshot, inputSha256: permitInputHash.right })
  if (Either.isLeft(permitResolution)) throw new Error(permitResolution.left.detail)
  const receipt = canonPut(content, { _tag: "Dnrd5RestoreJournalReceipt", blockId: manifest.blockId, opaqueForkId: manifest.forks[0].opaqueForkId, w0Id: manifest.w0.w0Id, w0JournalHeadSha256: journal.sha256, w0StateSha256: state.sha256, w0BehaviorReadsetSha256: readset.sha256, projectionPolicySha256: policy.sha256, grantSnapshotSha256: permit.grantSnapshot.snapshotSha256, permitResolutionSha256: permitResolution.right, terminal: "CALLER_SUPPLIED_RESTORE_AUDIT_RECEIPT_NOT_DURABLE_RECOVERY_PROOF" })
  const record: any = { _tag: "Dnrd5RestoreProjectionRecord", contractVersion: "hswm-dnrd5-w0-restore-projection/v1", blockId: manifest.blockId, binding: { opaqueForkId: manifest.forks[0].opaqueForkId, w0Id: manifest.w0.w0Id, state, behaviorReadset: readset, journalHead: journal, projectionPolicy: policy }, transition: { sourceKind: "staging_successor", targetKind: "macro_disposition", typedRole: "restore_transaction" }, permitInput: permit, recoveredState: state, recoveredBehaviorReadset: readset, restoredJournalReceipt: receipt, behaviorProjection: { descriptor: projection, behaviorUids, auditOnlyUids }, terminal: "CALLER_SUPPLIED_BYTES_NOT_DURABLE_RUNTIME_RECOVERY_NOT_NONTRAVERSABILITY_NOT_EXECUTION_OCCURRENCE_OR_SCIENCE" }
  const bytes = () => { const b = canonicalJsonBytes(record); if (Either.isLeft(b)) throw new Error(b.left.detail); return b.right }; return { content, identity: identity.right, record, bytes }
}

it("validates exact W0 restore bytes and audit-only behavior projection", () => { const x = fixture(); const result = validateDnrd5RestoreProjectionBytes(x.bytes(), x.identity, x.content); expect(Either.isRight(result)).toBe(true); if (Either.isRight(result)) { x.record.binding.w0Id = "w0:other"; expect(result.right.record.binding.w0Id).toBe("w0:block:0001"); expect(Object.isFrozen(result.right.record.binding)).toBe(true) } })
it("fails closed for cross-W0/fork/block, descriptor/bytes, receipt, and malformed records", () => { const cases = [(x: any) => { x.record.binding.opaqueForkId = "opaque:fork:missing" }, (x: any) => { x.record.binding.w0Id = "w0:other" }, (x: any) => { x.record.blockId = "DNRD5-BLOCK-0002" }, (x: any) => { x.content.set(x.record.recoveredState.sha256, enc.encode("corrupt")) }, (x: any) => { x.record.restoredJournalReceipt = x.identity.manifest.w0.journalHead }, (x: any) => { x.content.set(x.record.restoredJournalReceipt.sha256, enc.encode("corrupt")) }, (x: any) => { x.record.extra = true }]; for (const f of cases) { const x = fixture(); f(x); expect(Either.isLeft(validateDnrd5RestoreProjectionBytes(x.bytes(), x.identity, x.content))).toBe(true) } })
it("rejects unsorted/duplicate/overlapping projection UIDs and Permit root drift", () => { const cases = [(x: any) => { x.record.behaviorProjection.behaviorUids = ["behavior:z", "behavior:a"] }, (x: any) => { x.record.behaviorProjection.behaviorUids = ["behavior:a", "behavior:a"] }, (x: any) => { x.record.behaviorProjection.auditOnlyUids = ["behavior:a"] }, (x: any) => { x.record.permitInput.restore.expectedRootSha256 = sha("0") }]; for (const f of cases) { const x = fixture(); f(x); expect(Either.isLeft(validateDnrd5RestoreProjectionBytes(x.bytes(), x.identity, x.content))).toBe(true) } })
it("rejects noncanonical, extra, cross-state, and cross-policy projection content", () => {
  const cases = [
    (x: any) => { x.record.behaviorProjection.descriptor = put(x.content, enc.encode('{"behaviorUids":["behavior:a","behavior:z"], "auditOnlyUids":["audit:x"]}'), "application/json") },
    (x: any) => { x.record.behaviorProjection.descriptor = canonPut(x.content, { _tag: "Dnrd5BehaviorProjection", blockId: "DNRD5-BLOCK-0001", sourceStateSha256: sha("0"), projectionPolicySha256: x.record.binding.projectionPolicy.sha256, behaviorUids: x.record.behaviorProjection.behaviorUids, auditOnlyUids: x.record.behaviorProjection.auditOnlyUids, terminal: "CALLER_SUPPLIED_PROJECTION_NOT_NONTRAVERSABILITY_PROOF" }) },
    (x: any) => { x.record.behaviorProjection.descriptor = canonPut(x.content, { _tag: "Dnrd5BehaviorProjection", blockId: "DNRD5-BLOCK-0001", sourceStateSha256: x.record.binding.state.sha256, projectionPolicySha256: sha("0"), behaviorUids: x.record.behaviorProjection.behaviorUids, auditOnlyUids: x.record.behaviorProjection.auditOnlyUids, terminal: "CALLER_SUPPLIED_PROJECTION_NOT_NONTRAVERSABILITY_PROOF" }) },
    (x: any) => { x.record.behaviorProjection.descriptor = canonPut(x.content, { _tag: "Dnrd5BehaviorProjection", blockId: "DNRD5-BLOCK-0001", sourceStateSha256: x.record.binding.state.sha256, projectionPolicySha256: x.record.binding.projectionPolicy.sha256, behaviorUids: x.record.behaviorProjection.behaviorUids, auditOnlyUids: x.record.behaviorProjection.auditOnlyUids, terminal: "CALLER_SUPPLIED_PROJECTION_NOT_NONTRAVERSABILITY_PROOF", extra: true }) }
  ]
  for (const f of cases) { const x = fixture(); f(x); expect(Either.isLeft(validateDnrd5RestoreProjectionBytes(x.bytes(), x.identity, x.content))).toBe(true) }
})
