import { createHash } from "node:crypto"
import { mkdirSync, writeFileSync } from "node:fs"
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { Effect, Layer } from "effect"
import { describe, expect, it } from "vitest"
import { BoundedSubprocess, type SubprocessCommand, type SubprocessObservation } from "../src/effect-bounded-subprocess.js"
import { NodePosixFileSystemLive } from "../src/effect-posix-filesystem.js"
import { fetchNativeGraphStandardSource, qualifyNativeGraphStandardsProfile } from "../src/native-graph-standards-runtime.js"
import type { TaskJson } from "../src/native-task-json-domain.js"

const root=resolve(fileURLToPath(new URL("../../../..",import.meta.url)))
const enc=new TextEncoder()
const hash=(value:Uint8Array|string)=>createHash("sha256").update(value).digest("hex")
const ok=(stdout:string):SubprocessObservation=>({exitCode:0,signal:null,timedOut:false,outputTruncated:false,launchError:null,stdout:enc.encode(stdout),stderr:new Uint8Array()})
const failed=(exitCode:number):SubprocessObservation=>({exitCode,signal:null,timedOut:false,outputTruncated:false,launchError:null,stdout:new Uint8Array(),stderr:new Uint8Array()})
const timedOut=():SubprocessObservation=>({exitCode:null,signal:"SIGTERM",timedOut:true,outputTruncated:false,launchError:null,stdout:new Uint8Array(),stderr:new Uint8Array()})
const truncated=():SubprocessObservation=>({exitCode:0,signal:null,timedOut:false,outputTruncated:true,launchError:null,stdout:new Uint8Array(),stderr:new Uint8Array()})
const fixture=async(profileId:string):Promise<{readonly lock:TaskJson;readonly sourceRoot:string;readonly dispose:()=>Promise<void>}>=>{
 const lock=JSON.parse(await readFile(join(root,"_research/graph_standards/HSWM_GRAPH_STANDARDS_ACCEPTANCE.v1.json"),"utf8")) as Record<string,TaskJson>
 const profile=(lock["qualification_profiles"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]===profileId) as Record<string,TaskJson>
 const source=(lock["suite_sources"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]===profile["suite_source_id"]) as Record<string,TaskJson>
 const base=await mkdtemp(join(tmpdir(),"hswm-graph-standards-test-")),selected=String(source["selected_path"]),manifestPath=String(source["manifest_path"]),licensePath=String(source["license_path"]),qualificationPath=String(profile["qualification_manifest_path"])
 const manifest=enc.encode("{}\n"),license=enc.encode("test license\n"),qualification=enc.encode("{\"tests\":[]}\n"),archive=enc.encode("archive")
 await mkdir(join(base,".git"));await mkdir(join(base,selected),{recursive:true});await mkdir(join(base,qualificationPath,".."),{recursive:true});await mkdir(join(base,manifestPath,".."),{recursive:true});await mkdir(join(base,licensePath,".."),{recursive:true})
 await writeFile(join(base,manifestPath),manifest);await writeFile(join(base,licensePath),license);await writeFile(join(base,qualificationPath),qualification)
 Object.assign(source,{commit:"1".repeat(40),git_tree_sha1:"2".repeat(40),git_archive_sha256:hash(archive),manifest_sha256:hash(manifest),license_sha256:hash(license)})
 profile["qualification_manifest_sha256"]=hash(qualification)
 return {lock:lock as TaskJson,sourceRoot:base,dispose:()=>rm(base,{recursive:true,force:true})}
}
const queued=(commands:readonly ((command:SubprocessCommand)=>SubprocessObservation)[])=>{let index=0;return Layer.succeed(BoundedSubprocess,{observe:command=>{const next=commands[index++];return next===undefined?Effect.die(new Error(`unexpected command: ${command.argv.join(" ")}`)):Effect.succeed(next(command))}})}
const queuedExact=(commands:readonly ((command:SubprocessCommand)=>SubprocessObservation)[])=>{let index=0;return {layer:Layer.succeed(BoundedSubprocess,{observe:command=>{const next=commands[index++];return next===undefined?Effect.die(new Error(`unexpected command: ${command.argv.join(" ")}`)):Effect.succeed(next(command))}}),verify:()=>expect(index).toBe(commands.length)}}
const gitChecks=(profile:string,adapter:Record<string,TaskJson>,manifestSha:string,expected:Record<string,TaskJson>,python=false)=>[
 (c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",expect.any(String),"rev-parse","HEAD"]);return ok("1".repeat(40)+"\n")},
 (c:SubprocessCommand)=>{expect(c.argv[3]).toBe("rev-parse");return ok("2".repeat(40)+"\n")},
 (c:SubprocessCommand)=>{expect(c.argv[3]).toBe("archive");return ok("archive")},
 (c:SubprocessCommand)=>{expect(c.argv[3]).toBe("status");return ok("")},
 ...(python?[(c:SubprocessCommand)=>{expect(c.argv).toEqual(["uv","--version"]);return ok("uv 0.12.3\n")}]:[(c:SubprocessCommand)=>{expect(c.argv).toEqual(["node","--version"]);return ok("v24.13.0\n")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["npm","--version"]);return ok("11.6.2\n")}]),
 (_c:SubprocessCommand)=>{const result={status:"PASS",profile,manifest_sha256:manifestSha,adapter:{package:adapter["package"],version:adapter["version"]},counts:expected,...(python?{runtime:{implementation:"CPython",python:"3.12.13"}}:{})};return ok(JSON.stringify(result))}
]
describe("native graph standards qualification runtime",()=>{
 it("runs the locked uv profile and emits a bound receipt without network installation",async()=>{const f=await fixture("shacl10-pyshacl-hswm-core");try{const profile=(f.lock as Record<string,TaskJson>)["qualification_profiles"] as TaskJson[],p=profile.find(x=>(x as Record<string,TaskJson>)["id"]==="shacl10-pyshacl-hswm-core") as Record<string,TaskJson>,adapter=((f.lock as Record<string,TaskJson>)["tool_adapters"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]===p["adapter_id"]) as Record<string,TaskJson>,sha=String(p["qualification_manifest_sha256"]);const q=gitChecks(String(p["id"]),adapter,sha,p["expected"] as Record<string,TaskJson>,true);const result=await Effect.runPromise(qualifyNativeGraphStandardsProfile(f.lock,String(p["id"]),f.sourceRoot,root).pipe(Effect.provide(Layer.merge(NodePosixFileSystemLive,queued(q)))));expect(result).toMatchObject({profile_id:p["id"],runtime:{kind:"python-uv"},source:{commit:"1".repeat(40)}})}finally{await f.dispose()}})
 it("runs the isolated locked npm profile and releases its generated temporary root",async()=>{const f=await fixture("jsonld11-jsonldjs-hswm-fromrdf");const temporary=await mkdtemp(join(tmpdir(),"hswm-graph-standard-npm-"));try{const profiles=(f.lock as Record<string,TaskJson>)["qualification_profiles"] as TaskJson[],p=profiles.find(x=>(x as Record<string,TaskJson>)["id"]==="jsonld11-jsonldjs-hswm-fromrdf") as Record<string,TaskJson>,adapter=((f.lock as Record<string,TaskJson>)["tool_adapters"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]===p["adapter_id"]) as Record<string,TaskJson>;const q=[...gitChecks(String(p["id"]),adapter,String(p["qualification_manifest_sha256"]),p["expected"] as Record<string,TaskJson>)];q.splice(6,0,(c:SubprocessCommand)=>{expect(c.argv.slice(0,3)).toEqual(["mktemp","-d","-t"]);return ok(temporary+"\n")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["npm","ci","--ignore-scripts","--no-audit","--no-fund"]);return ok("")});q.push((c:SubprocessCommand)=>{expect(c.argv).toEqual(["rm","-rf","--",temporary]);return ok("")});const result=await Effect.runPromise(qualifyNativeGraphStandardsProfile(f.lock,String(p["id"]),f.sourceRoot,root).pipe(Effect.provide(Layer.merge(NodePosixFileSystemLive,queued(q)))));expect(result).toMatchObject({profile_id:p["id"],runtime:{kind:"node-npm"}})}finally{await rm(temporary,{recursive:true,force:true});await f.dispose()}})
 it.each(["npm ci exit failure", "runner timeout", "runner output truncation"])("releases the temporary npm root after %s",async(kind)=>{const f=await fixture("jsonld11-jsonldjs-hswm-fromrdf"),temporary=await mkdtemp(join(tmpdir(),"hswm-graph-standard-npm-"));try{const profiles=(f.lock as Record<string,TaskJson>)["qualification_profiles"] as TaskJson[],p=profiles.find(x=>(x as Record<string,TaskJson>)["id"]==="jsonld11-jsonldjs-hswm-fromrdf") as Record<string,TaskJson>,adapter=((f.lock as Record<string,TaskJson>)["tool_adapters"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]===p["adapter_id"]) as Record<string,TaskJson>,commands=[...gitChecks(String(p["id"]),adapter,String(p["qualification_manifest_sha256"]),p["expected"] as Record<string,TaskJson>)];commands.splice(6,0,(c:SubprocessCommand)=>{expect(c.argv).toEqual(["mktemp","-d","-t","hswm-graph-standard-npm-XXXXXX"]);return ok(temporary+"\n")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["npm","ci","--ignore-scripts","--no-audit","--no-fund"]);return kind==="npm ci exit failure"?failed(1):ok("")});if(kind!=="npm ci exit failure")commands[8]=c=>{expect(c.argv[0]).toBe("node");return kind==="runner timeout"?timedOut():truncated()};commands.length=kind==="npm ci exit failure"?8:9;commands.push(c=>{expect(c.argv).toEqual(["rm","-rf","--",temporary]);return ok("")});const queue=queuedExact(commands),result=await Effect.runPromise(qualifyNativeGraphStandardsProfile(f.lock,String(p["id"]),f.sourceRoot,root).pipe(Effect.either,Effect.provide(Layer.merge(NodePosixFileSystemLive,queue.layer))));expect(result).toMatchObject({_tag:"Left",left:{detail:kind==="npm ci exit failure"?"subprocess failed with exit 1":kind==="runner timeout"?"subprocess timed out":"subprocess output exceeded bounds"}});queue.verify()}finally{await rm(temporary,{recursive:true,force:true});await f.dispose()}})
})
describe("native graph standards source materialization",()=>{
 it.each(["commit", "tree", "license"])("uses the exact pinned fetch queue and rejects %s drift",async(drift)=>{const f=await fixture("jsonld11-jsonldjs-hswm-fromrdf"),parent=await mkdtemp(join(tmpdir(),"hswm-graph-standard-fetch-")),destination=join(parent,"checkout");try{const profile=((f.lock as Record<string,TaskJson>)["qualification_profiles"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]==="jsonld11-jsonldjs-hswm-fromrdf") as Record<string,TaskJson>,source=((f.lock as Record<string,TaskJson>)["suite_sources"] as TaskJson[]).find(x=>(x as Record<string,TaskJson>)["id"]===profile["suite_source_id"]) as Record<string,TaskJson>,detail=drift==="commit"?"source checkout commit drift":drift==="tree"?"source checkout selected tree drift":"source license digest drift",writeCheckout=():void=>{mkdirSync(join(destination,".git"),{recursive:true});mkdirSync(join(destination,String(source["selected_path"])),{recursive:true});writeFileSync(join(destination,String(source["manifest_path"])),"{}\n");writeFileSync(join(destination,String(source["license_path"])),drift==="license"?"drift\n":"test license\n")},commands=[(c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","init","--quiet",destination]);expect(c.cwd).toBe(parent);writeCheckout();return ok("")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"remote","add","origin",source["repository"]]);return ok("")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"fetch","--quiet","--depth=1","origin",source["commit"]]);return ok("")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"checkout","--quiet","--detach","FETCH_HEAD"]);return ok("")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"rev-parse","HEAD"]);return ok(drift==="commit"?"0".repeat(40)+"\n":"1".repeat(40)+"\n")}];if(drift!=="commit")commands.push((c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"rev-parse",`HEAD:${source["selected_path"]}`]);return ok(drift==="tree"?"0".repeat(40)+"\n":"2".repeat(40)+"\n")});if(drift==="license")commands.push((c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"archive","--format=tar",source["commit"],"--",source["selected_path"]]);return ok("archive")},(c:SubprocessCommand)=>{expect(c.argv).toEqual(["git","-C",destination,"status","--porcelain=v1","--untracked-files=all","--",source["selected_path"]]);return ok("")});const queue=queuedExact(commands),result=await Effect.runPromise(fetchNativeGraphStandardSource(source,destination,root).pipe(Effect.either,Effect.provide(Layer.merge(NodePosixFileSystemLive,queue.layer))));expect(result).toMatchObject({_tag:"Left",left:{detail}});queue.verify()}finally{await rm(parent,{recursive:true,force:true});await f.dispose()}})
})
