import { execFileSync, spawnSync } from "node:child_process"
import { chmodSync, mkdirSync, mkdtempSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { beforeAll, expect, it } from "@effect/vitest"

const runtime=resolve(import.meta.dirname,".."), node=process.execPath
let emitted:string|undefined
const emit=():string=>{if(emitted!==undefined)return emitted;const container=mkdtempSync(join(tmpdir(),"hswm-occurrence-cli-")),out=join(container,"dist");mkdirSync(out);symlinkSync(join(runtime,"node_modules"),join(container,"node_modules"),"dir");symlinkSync(join(runtime,"assets"),join(container,"assets"),"dir");const config=join(out,"tsconfig.json");writeFileSync(config,JSON.stringify({extends:join(runtime,"tsconfig.build.json"),compilerOptions:{rootDir:join(runtime,"src"),outDir:out,noEmit:false,declaration:false,declarationMap:false,sourceMap:false},include:[join(runtime,"src/native-occurrence-process.ts")],exclude:[]}));execFileSync(join(runtime,"node_modules/.bin/tsc"),["-p",config],{cwd:runtime});emitted=out;return out}
beforeAll(() => { emit() }, 30_000)
const run=(out:string,args:ReadonlyArray<string>,env?:NodeJS.ProcessEnv)=>spawnSync(node,[join(out,"native-occurrence-process.js"),...args],{encoding:"utf8",env,cwd:tmpdir()})
it("emitted Effect process preserves describe/workflow/statement/parse-dsse semantic goldens",()=>{
 const out=emit(),dir=mkdtempSync(join(tmpdir(),"hswm-occurrence-input-")),subject=join(dir,"subject.txt"),predicate=join(dir,"predicate.json"),envelope=join(dir,"envelope.json");writeFileSync(subject,"abc");writeFileSync(predicate,'{"ok":true}');const payload=Buffer.from('{"_type":"https://in-toto.io/Statement/v1","predicate":{},"predicateType":"p","subject":[{"digest":{"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"name":"x"}]}').toString("base64");writeFileSync(envelope,JSON.stringify({payloadType:"application/vnd.in-toto+json",payload,signatures:[{keyid:"kid",sig:"AQ=="}]}))
 const describe=run(out,["describe","--media-type","text/plain",subject]),workflow=run(out,["workflow-options","occ-1"]),statement=run(out,["statement","--predicate",predicate,"--media-type","text/plain","--subject-name","subject.txt","--subject",subject,"--predicate-type","p"]),dsse=run(out,["parse-dsse",envelope])
 expect(describe.status).toBe(0);expect(JSON.parse(describe.stdout)).toMatchObject({byte_length:3,media_type:"text/plain"});expect(workflow.status).toBe(0);expect(JSON.parse(workflow.stdout)).toMatchObject({workflow_id:"g0-occurrence/occ-1",workflow_maximum_attempts:1});expect(statement.status).toBe(0);expect(JSON.parse(statement.stdout)).toMatchObject({_type:"https://in-toto.io/Statement/v1",predicate:{ok:true}});expect(dsse.status).toBe(0);expect(JSON.parse(dsse.stdout)).toMatchObject({cryptographically_verified:false,signature_keyids:["kid"],subject_name:"x"})
})
it("emitted process has argparse-style help and malformed/file/unsupported flag exit 2",()=>{
 const out=emit(),help=run(out,["--help"]),bad=run(out,["describe","/no/such/file","--media-type","text/plain"]),stdin=run(out,["describe","-","--media-type","text/plain"]),output=run(out,["workflow-options","occ-1","--output","x"])
 expect(help.status).toBe(0);expect(help.stdout).toContain("usage:");for(const result of [bad,stdin,output]){expect(result.status).toBe(2);expect(result.stderr).toContain("hswm-g0-occurrence: error:")}
})
it("emitted process preserves no-newline handoff template and validates its fixed candidate binding",()=>{
 const out=emit(),template=run(out,["external-handoff-template","occ-1"])
 expect(template.status).toBe(0);expect(template.stdout.endsWith("\n")).toBe(false);const payload=JSON.parse(template.stdout) as Record<string,unknown>;expect(payload).toMatchObject({occurrence_uid:"occ-1",status:"BLOCKED_EXTERNAL"})
 const dir=mkdtempSync(join(tmpdir(),"hswm-handoff-")),path=join(dir,"handoff.json");writeFileSync(path,template.stdout);const valid=run(out,["external-handoff-validate",path]);expect(valid.status).toBe(0);expect(JSON.parse(valid.stdout)).toMatchObject({schema_structure_valid:true,structural_validation_only:true,descriptor_graph_complete:false})
 writeFileSync(path,`${template.stdout} `);const invalid=run(out,["external-handoff-validate",path]);expect(invalid.status).toBe(2)
})
it("emitted process emits all four external command argv arrays and enforces file/new-output contracts",()=>{
 const out=emit(),dir=mkdtempSync(join(tmpdir(),"hswm-generator-")),blob=join(dir,"blob.json"),statement=join(dir,"statement.json"),request=join(dir,"request.tsq"),response=join(dir,"response.tsr"),ca=join(dir,"ca.pem"),untrusted=join(dir,"u.pem"),bundle=join(dir,"bundle.json");for(const file of [blob,statement,request,response,ca,untrusted])writeFileSync(file,"x")
 const worm=run(out,["worm-command","--bucket","hswm-occurrence.example","--occurrence-uid","occurrence-001","--body",blob,"--retain-until","2027-09-03T00:00:00Z","--claimant-account-id","111111111111","--admin-account-id","222222222222"]),cosign=run(out,["cosign-attest-command","--blob",blob,"--statement",statement,"--bundle",bundle]),query=run(out,["rfc3161-query-command","--blob",blob,"--request",bundle]),verify=run(out,["rfc3161-verify-command","--request",request,"--response",response,"--ca-file",ca,"--untrusted",untrusted])
 expect(worm.status).toBe(0);expect((JSON.parse(worm.stdout).argv as string[]).slice(0,3)).toEqual(["aws","s3api","put-object"]);expect(cosign.status).toBe(0);expect(JSON.parse(cosign.stdout).argv).toEqual(["cosign","attest-blob","--statement",statement,"--bundle",bundle,"--yes",blob]);expect(query.status).toBe(0);expect(JSON.parse(query.stdout).argv).toEqual(["openssl","ts","-query","-data",blob,"-sha256","-cert","-out",bundle]);expect(verify.status).toBe(0);expect(JSON.parse(verify.stdout).argv).toEqual(["openssl","ts","-verify","-queryfile",request,"-in",response,"-CAfile",ca,"-untrusted",untrusted])
 writeFileSync(bundle,"exists");for(const result of [run(out,["cosign-attest-command","--blob",blob,"--statement",statement,"--bundle",bundle]),run(out,["rfc3161-query-command","--blob",blob,"--request",bundle]),run(out,["rfc3161-verify-command","--request",join(dir,"missing"),"--response",response,"--ca-file",ca])])expect(result.status).toBe(2)
 const denied=join(dir,"denied");mkdirSync(denied);chmodSync(denied,0o000);try{expect(run(out,["rfc3161-query-command","--blob",blob,"--request",join(denied,"request.tsq")]).status).toBe(2)}finally{chmodSync(denied,0o700)}
})
it("emitted process validates caller-supplied OSF readback locally and keeps preflight secret-free",()=>{
 const out=emit(),dir=mkdtempSync(join(tmpdir(),"hswm-osf-")),registration=join(dir,"registration.json"),file=join(dir,"file.json"),expected=join(dir,"expected"),readback=join(dir,"readback"),url="https://files.osf.io/v1/resources/abc12/providers/osfstorage/file123"
 writeFileSync(registration,'{"data":{"id":"abc12","type":"registrations","attributes":{"date_registered":"2026-09-03T00:00:00Z","withdrawn":false},"links":{"self":"https://api.osf.io/v2/registrations/abc12/"}}}');writeFileSync(file,`{"data":{"type":"files","attributes":{"name":"protocol/package.json","size":3,"extra":{"hashes":{"sha256":"${"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"}"}}},"links":{"self":"https://api.osf.io/v2/files/file123/","download":"${url}"}}}`);writeFileSync(expected,"abc");writeFileSync(readback,"abc")
 const args=["osf-readback","--registration",registration,"--file-metadata",file,"--expected-package",expected,"--read-back-package",readback,"--read-back-download-url",url,"--registered-path","protocol/package.json","--pulse-timestamp","2026-09-03T00:00:03Z"],candidate=run(out,args);expect(candidate.status).toBe(0);expect(JSON.parse(candidate.stdout)).toMatchObject({status:"CANDIDATE_FOR_EXTERNAL_AUDIT",reason:null,registration_timestamp:"2026-09-03T00:00:00Z"})
 writeFileSync(readback,"different");const voided=run(out,args);expect(voided.status).toBe(4);expect(JSON.parse(voided.stdout)).toMatchObject({status:"VOID",reason:"PACKAGE_OR_READBACK_BYTES_DO_NOT_MATCH"})
 writeFileSync(readback,"abc");const micros=run(out,[...args.slice(0,-1),"2026-09-03T00:00:00.000001Z"]);expect(micros.status).toBe(0);expect(JSON.parse(micros.stdout)).toMatchObject({status:"CANDIDATE_FOR_EXTERNAL_AUDIT"})
 writeFileSync(registration,'{"data":{"id":"abc12","type":"registrations","attributes":{"date_registered":"0001-01-01T00:00:00Z","withdrawn":false},"links":{"self":"https://api.osf.io/v2/registrations/abc12/"}}}');const calendar=run(out,[...args.slice(0,-1),"0001-01-01T00:00:00.000001Z"]);expect(calendar.status).toBe(0);expect(JSON.parse(calendar.stdout)).toMatchObject({status:"CANDIDATE_FOR_EXTERNAL_AUDIT"})
 writeFileSync(file,`{"data":{"type":"files","attributes":{"name":"protocol/package.json","size":3.0,"extra":{"hashes":{"sha256":"${"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"}"}}},"links":{"self":"https://api.osf.io/v2/files/file123/","download":"${url}"}}}`);expect(run(out,args).status).toBe(2);writeFileSync(file,`{"data":{"type":"files","attributes":{"name":"protocol/package.json","size":3,"extra":{"hashes":{"sha256":"${"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"}"}}},"links":{"self":"https://api.osf.io/v2/files/file123/","download":"${url}"}}}`)
 expect(run(out,[...args.slice(0,12)," protocol/package.json ",...args.slice(13)]).status).toBe(2)
 writeFileSync(registration,'{"data":{"id":"abc12","type":"registrations","attributes":{"date_registered":"2026-09-03T00:00:00Z","withdrawn":true},"links":{"self":"https://api.osf.io/v2/registrations/abc12/"}}}');writeFileSync(readback,"different");const precedence=run(out,args);expect(precedence.status).toBe(4);expect(JSON.parse(precedence.stdout)).toMatchObject({reason:"PACKAGE_OR_READBACK_BYTES_DO_NOT_MATCH"})
 const secret="https://token:do-not-print@example.invalid/sensitive",preflight=run(out,["preflight"],{PATH:process.env["PATH"],HSWM_G0_WORM_ENDPOINT:secret});expect(preflight.status).toBe(3);expect(preflight.stdout).not.toContain(secret);expect(JSON.parse(preflight.stdout)).toMatchObject({status:"BLOCKED_EXTERNAL",live_execution_ready:false})
})
