import { expect, it } from "@effect/vitest"
import { Either } from "effect"
import { createHash } from "node:crypto"
import { readFileSync } from "node:fs"
import { NATIVE_S2S_TRAINING_SOURCE_SHA256, clipNativeS2SGradients, lossAndGradientsNativeS2S, lossForNativeS2SParameters } from "../src/native-s2s-training-numeric-domain.js"
const values=(n:number):readonly number[]=>Object.freeze(Array.from({length:n},(_,i)=>((i%11)-5)/32))
const inputs=values(48),targets=values(24),weights=Object.freeze([.5,.75,1,1.25,1.5,1.75])
const parameters=(arm:"P_CAP18"|"T16"|"DS870")=>arm==="P_CAP18"?{phiW:values(216),psiW:values(216),unaryW:values(108),pairW:values(324),outB:values(6)}:arm==="T16"?{phiW:values(192),psiW:values(192),unaryW:values(96),pairW:values(288),qW:values(96),outB:values(6)}:{etaW:values(48),etaB:values(12),hidden1W:values(420),hidden1B:values(14),hidden2W:values(308),hidden2B:values(22),outW:values(44),outB:values(2)}
const oracle=JSON.parse(readFileSync(new URL("../../../../tests/fixtures/native_migration/s2s_training_numeric_v1/original_batch2.json",import.meta.url),"utf8")) as {readonly source_sha256:string;readonly input:readonly number[];readonly targets:readonly number[];readonly weights:readonly number[];readonly arms:Readonly<Record<string,{readonly loss:number;readonly gradient_sha256:Readonly<Record<string,string>>}>>}
// Python/NumPy and scalar JS differ only in summation order; compare every value after the frozen 1e-12 engineering rounding.
const bytesHash=(values:readonly number[]):string=>{const a=new Float64Array(values.map(value=>Math.round(value*1e12)/1e12));return createHash("sha256").update(Buffer.from(a.buffer)).digest("hex")}
it("returns positive finite weighted losses and nonzero gradients for all training arms",()=>{for(const arm of ["P_CAP18","T16","DS870"] as const){const result=lossAndGradientsNativeS2S(arm,parameters(arm),inputs,targets,weights);expect(Either.isRight(result)).toBe(true);if(Either.isRight(result)){expect(result.right.loss).toBeGreaterThan(0);expect(Object.values(result.right.gradients).flat().some(x=>x!==0)).toBe(true)}}})
it("matches frozen original Python batch-two losses and every gradient tensor digest",()=>{
 expect(oracle.source_sha256).toBe(NATIVE_S2S_TRAINING_SOURCE_SHA256)
 expect(createHash("sha256").update(readFileSync(new URL("../../../hswm/experiments/swm0w_s2s_training.py",import.meta.url))).digest("hex")).toBe(oracle.source_sha256)
 for(const arm of ["P_CAP18","T16","DS870"] as const){const result=lossAndGradientsNativeS2S(arm,parameters(arm),oracle.input,oracle.targets,oracle.weights),expected=oracle.arms[arm]!;expect(Either.isRight(result)).toBe(true)
  if(Either.isRight(result)){expect(Math.abs(result.right.loss-expected.loss)).toBeLessThanOrEqual(5e-14);for(const [name,digest] of Object.entries(expected.gradient_sha256)){const native=name.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase());expect(bytesHash(result.right.gradients[native]!)).toBe(digest)}}
 }
})
it("matches frozen original Python loss-only evaluation for every arm",()=>{for(const arm of ["P_CAP18","T16","DS870"] as const){const result=lossForNativeS2SParameters(arm,parameters(arm),oracle.input,oracle.targets,oracle.weights);expect(Either.isRight(result)).toBe(true);if(Either.isRight(result))expect(Math.abs(result.right-oracle.arms[arm]!.loss)).toBeLessThanOrEqual(5e-14)}})
it("matches central finite differences across P_CAP18, T16 q, and DS870 eta nonlinear paths",()=>{for(const [arm,key,at] of [["P_CAP18","phiW",7],["T16","qW",7],["DS870","etaW",7]] as const){const p=parameters(arm),e=1e-6,base=p[key]!,plus={...p,[key]:Object.freeze(base.map((v,i)=>i===at?v+e:v))},minus={...p,[key]:Object.freeze(base.map((v,i)=>i===at?v-e:v))},analytic=lossAndGradientsNativeS2S(arm,p,inputs,targets,weights),a=lossForNativeS2SParameters(arm,plus,inputs,targets,weights),b=lossForNativeS2SParameters(arm,minus,inputs,targets,weights);expect(Either.isRight(analytic)&&Either.isRight(a)&&Either.isRight(b)).toBe(true);if(Either.isRight(analytic)&&Either.isRight(a)&&Either.isRight(b))expect(analytic.right.gradients[key]![at]).toBeCloseTo((a.right-b.right)/(2*e),7)}})
it("accepts a finite loss even when its reverse-mode gradient overflows",()=>{const zero=Object.freeze(Array<number>(216).fill(0)),p={phiW:Object.freeze(zero.map((value,index)=>index===0?1e-154:value)),psiW:zero,unaryW:Object.freeze(Array.from({length:108},(_,index)=>index===0?1:0)),pairW:Object.freeze(Array<number>(324).fill(0)),outB:Object.freeze(Array<number>(6).fill(0))},input=Object.freeze(Array.from({length:24},(_,index)=>index===0?1e308:0)),bits=new DataView(new ArrayBuffer(8));bits.setFloat64(0,1e154);bits.setBigUint64(0,bits.getBigUint64(0)-1n);const target=Object.freeze(Array.from({length:12},(_,index)=>index===0?bits.getFloat64(0):0)),loss=lossForNativeS2SParameters("P_CAP18",p,input,target,Object.freeze([1,1,1,1,1,1])),gradient=lossAndGradientsNativeS2S("P_CAP18",p,input,target,Object.freeze([1,1,1,1,1,1]));expect(Either.isRight(loss)).toBe(true);if(Either.isRight(loss))expect(loss.right).toBe(1.8465232209337043e275);expect(Either.isLeft(gradient)).toBe(true)})
it("returns typed errors for runtime-malformed loss-only values",()=>{const invoke=lossForNativeS2SParameters as unknown as (arm:unknown,parameters:unknown,input:unknown,targets:unknown,weights:unknown)=>unknown;for(const arm of ["P_CAP18","T16","DS870"]){expect(Either.isLeft(invoke(arm,null,null,null,null) as Either.Either<number,unknown>)).toBe(true)}})
it("clips only over-threshold gradients and rejects malformed tensors",()=>{const g={a:Object.freeze([3,4])},small=clipNativeS2SGradients(g,6),large=clipNativeS2SGradients(g,4);expect(Either.isRight(small)&&Either.isRight(large)).toBe(true);if(Either.isRight(small)&&Either.isRight(large)){expect(small.right.clipped).toBe(false);expect(large.right.clipped).toBe(true);expect(large.right.norm).toBe(5)}expect(Either.isLeft(lossAndGradientsNativeS2S("P_CAP18",parameters("P_CAP18"),[NaN],targets,weights))).toBe(true);expect(Either.isLeft(lossAndGradientsNativeS2S("P_CAP18",parameters("P_CAP18"),inputs,targets,[0,1,1,1,1,1]))).toBe(true)})

it("preserves original weighted-sum overflow refusal before normalization",()=>{
 const p={phiW:Array(216).fill(0),psiW:Array(216).fill(0),unaryW:Array(108).fill(0),pairW:Array(324).fill(0),outB:Array(6).fill(0)},x=Array(24).fill(0),target=Array(12).fill(1e154),weights=Array(6).fill(1)
 expect(lossForNativeS2SParameters("P_CAP18",p,x,target,weights)).toMatchObject({_tag:"Left",left:{reason:"NUMERIC_INVALID"}})
 expect(lossAndGradientsNativeS2S("P_CAP18",p,x,target,weights)).toMatchObject({_tag:"Left",left:{reason:"NUMERIC_INVALID"}})
 expect(Reflect.apply(clipNativeS2SGradients,undefined,[null,1])).toMatchObject({_tag:"Left",left:{reason:"INPUT_INVALID"}})
})
