import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { Effect } from "effect";
import { expect, it } from "vitest";
import { NodePosixFileSystem, PosixFileSystem } from "../src/effect-posix-filesystem.js";
import { captureNativeP1ArtifactSnapshot } from "../src/native-p1-artifact-snapshot-runtime.js";
const hash = (x: Uint8Array) => createHash("sha256").update(x).digest("hex");
const run = <A>(x: Effect.Effect<A, unknown, PosixFileSystem | import("effect").Scope.Scope>) => Effect.runPromise(Effect.scoped(Effect.provideService(x, PosixFileSystem, NodePosixFileSystem)));
it("captures bytes before source mutation, preserves modes, and removes its scoped copy", async () => { const root = await mkdtemp(join(tmpdir(), "p1-snapshot-test-")), source = join(root, "config.json"), first = new TextEncoder().encode("first"); await writeFile(source, first); let captured = ""; await run(Effect.gen(function* () { const snap = yield* captureNativeP1ArtifactSnapshot(root, Object.freeze({ "config.json": hash(first) })); captured = snap.directory; yield* Effect.promise(() => writeFile(source, "changed")); const bytes = yield* Effect.promise(() => readFile(join(snap.directory, "config.json"), "utf8")), directoryStat = yield* Effect.promise(() => stat(snap.directory)), fileStat = yield* Effect.promise(() => stat(join(snap.directory, "config.json"))); expect(bytes).toBe("first"); expect(directoryStat.mode & 0o777).toBe(0o700); expect(fileStat.mode & 0o777).toBe(0o400); })); await expect(stat(captured)).rejects.toThrow(); await rm(root, { recursive: true, force: true }); });
it("refuses digest mismatches without creating a usable snapshot", async () => { const root = await mkdtemp(join(tmpdir(), "p1-snapshot-test-")); await writeFile(join(root, "config.json"), "x"); await expect(run(captureNativeP1ArtifactSnapshot(root, Object.freeze({ "config.json": "0".repeat(64) })))).rejects.toBeDefined(); await rm(root, { recursive: true, force: true }); });
it("removes a partially written snapshot when the second exclusive write fails",async()=>{const root=await mkdtemp(join(tmpdir(),"p1-snapshot-test-")),a=new TextEncoder().encode("a"),b=new TextEncoder().encode("b");await writeFile(join(root,"a.json"),a);await writeFile(join(root,"b.json"),b);let writes=0,firstTarget="";const fs={...NodePosixFileSystem,writeExclusive:(path:string,bytes:Uint8Array,options:{readonly mode:number;readonly sync:boolean;readonly operation:string})=>{writes+=1;if(writes===1){firstTarget=path;return NodePosixFileSystem.writeExclusive(path,bytes,options)}return Effect.fail(new (require("../src/effect-posix-filesystem.js").PosixIoError)({operation:options.operation,path,code:"EEXIST",detail:"injected"}))}};await expect(Effect.runPromise(Effect.scoped(Effect.provideService(captureNativeP1ArtifactSnapshot(root,Object.freeze({"a.json":hash(a),"b.json":hash(b)})),PosixFileSystem,fs)))).rejects.toBeDefined();expect(writes).toBe(2);await expect(stat(dirname(firstTarget))).rejects.toThrow();await rm(root,{recursive:true,force:true})})
it("refuses dot path segments before any filesystem read",async()=>{let reads=0;const fs={...NodePosixFileSystem,readRegularBounded:(...args:Parameters<typeof NodePosixFileSystem.readRegularBounded>)=>{reads+=1;return NodePosixFileSystem.readRegularBounded(...args)}};for(const path of ["./x","a/../x"]){await expect(Effect.runPromise(Effect.scoped(Effect.provideService(captureNativeP1ArtifactSnapshot("/unused",Object.freeze({[path]:"0".repeat(64)})),PosixFileSystem,fs)))).rejects.toBeDefined()}expect(reads).toBe(0)})
