import { describe, expect, it } from "vitest"
import { Either } from "effect"
import { RESEARCH_FABRIC_CLAIM_BOUNDARY, RESEARCH_FABRIC_PROCESS_V1, classifyFabricState, fabricSpecs, parseFabricRecord, readiness, renderFabricRecord, safeServiceEnvironment } from "../src/native-research-fabric-domain.js"

describe("native research fabric domain",()=>{
 it("keeps both managed service listeners on loopback with pinned behavior",()=>{const specs=fabricSpecs("/tmp/state","/tmp/bin");expect(Object.keys(specs).sort()).toEqual(["phoenix","temporal"]);expect(Object.values(specs).every((item)=>item.readyHost==="127.0.0.1")).toBe(true);expect(specs.phoenix.environment["PHOENIX_ENABLE_AUTH"]).toBe("true");expect(specs.phoenix.environment["PHOENIX_TELEMETRY_ENABLED"]).toBe("false");expect(specs.temporal.argv).toContain("--disable-config-env")})
 it("does not inherit ambient session secrets and refuses foreign listeners",()=>{const spec=fabricSpecs("/tmp/state","/tmp/bin").phoenix;const environment=safeServiceEnvironment({PATH:"/usr/bin",OPENAI_API_KEY:"secret",ORCA_AGENT_HOOK_TOKEN:"secret"},spec,{PHOENIX_SECRET:"x",PHOENIX_ADMIN_SECRET:"y"});expect(environment).toMatchObject({PATH:"/usr/bin",PHOENIX_HOST:"127.0.0.1"});expect(environment).not.toHaveProperty("OPENAI_API_KEY");expect(classifyFabricState("untracked",readiness(true,[true,200]))).toBe("foreign_or_untracked_listener")})
 it("reads Python integer-nanosecond records and preserves their numeric wire form",()=>{expect(Either.isLeft(parseFabricRecord("not-json","phoenix"))).toBe(true);const record=`{"schema":"${RESEARCH_FABRIC_PROCESS_V1}","claim_boundary":"${RESEARCH_FABRIC_CLAIM_BOUNDARY}","service":"phoenix","pid":1,"start_ticks":3,"executable":"/x","executable_sha256":"a","version":"1","public_argv":[],"log_path":"/log","started_unix_ns":1760000000000000001}`;const parsed=parseFabricRecord(record,"phoenix");expect(Either.isRight(parsed)).toBe(true);if(Either.isRight(parsed)){expect(parsed.right.started_unix_ns).toBe(1760000000000000001n);expect(renderFabricRecord(parsed.right)).toContain('"started_unix_ns": 1760000000000000001')}})
 it("refuses a record that claims a different service",()=>{const record=JSON.stringify({schema:RESEARCH_FABRIC_PROCESS_V1,claim_boundary:RESEARCH_FABRIC_CLAIM_BOUNDARY,service:"temporal",pid:1,start_ticks:3,executable:"/x",executable_sha256:"a",version:"1",public_argv:[],log_path:"/log",started_unix_ns:1});expect(Either.isLeft(parseFabricRecord(record,"phoenix"))).toBe(true)})
})
