import { describe, expect, it } from "vitest"
import { Either } from "effect"
import { compilePortableMarkdownMath } from "../src/native-markdown-math-domain.js"
describe("native portable markdown math",()=>{
 it("matches admitted operator, fence, code-span and legacy rewrites",()=>{const r=compilePortableMarkdownMath("Before $\\operatorname{Readout}(x)$.\n\n\\[\nz=\\operatorname*{argmax}_{i} x_i\n\\]\n`\\operatorname{x}`\n\n```python\n\\operatorname{x}\n```\n");expect(Either.isRight(r)).toBe(true);if(Either.isRight(r)){expect(r.right.text).toBe("Before $\\mathrm{Readout}(x)$.\n\n```math\nz=\\mathrm{argmax}_{i} x_i\n```\n`\\operatorname{x}`\n\n```python\n\\operatorname{x}\n```\n");expect(r.right.operatorname_rewrites).toBe(2)}})
 it("fails closed",()=>{for(const s of ["$\\operatorname{not closed$","\\[\nx=1\n","\\]\n","```math\nx=1\n"]){expect(Either.isLeft(compilePortableMarkdownMath(s))).toBe(true)}})
 it("preserves ordinary code while compiling fenced math",()=>{const r=compilePortableMarkdownMath("`\\operatorname{literal}`\n\n```python\nvalue = r\"\\operatorname{literal}\"\n```\n\n```math\nx=\\operatorname{clip}(y)\n```\n");expect(Either.isRight(r)).toBe(true);if(Either.isRight(r)){expect(r.right.text.match(/\\operatorname\{literal\}/g)).toHaveLength(2);expect(r.right.text).toContain("\\mathrm{clip}");expect(r.right.operatorname_rewrites).toBe(1)}})
 it("compiles each admitted immutable-legacy compatibility literal",()=>{const r=compilePortableMarkdownMath("\\mathsf{Owner}_{\\sigma}(a,p)\n\\centernot\\Rightarrow\n\\mathsf{Permit}_{\\sigma}(S,e).\n\n\\mathcal K={S:|A|\\le B_A\\}\n\np_j = 2^(-m_j) sum_{k=w_j}^{m_j} choose(m_j,k),\np_j_adjusted = min(1, 3 p_j).\n");expect(Either.isRight(r)).toBe(true);if(Either.isRight(r)){expect(r.right.text).toContain("\\not\\Rightarrow");expect(r.right.text).toContain("\\mathcal K=\\{S:");expect(r.right.text).toContain("2^{-m_j} \\sum_{k=w_j}^{m_j} \\binom{m_j}{k}");expect(r.right.text).toContain("p_{j,\\mathrm{adjusted}} = \\min(1, 3p_j)");expect(r.right.legacy_compatibility_rewrites).toBe(4)}})
})
