import { Effect, Layer } from "effect"
import { expect, it } from "vitest"
import { BoundedSubprocess } from "../src/effect-bounded-subprocess.js"
import { fabricSpecs } from "../src/native-research-fabric-domain.js"
import { ResearchFabricRuntime } from "../src/native-research-fabric-runtime.js"
import { researchFabricStatus, startResearchFabricService, stopResearchFabricService } from "../src/native-research-fabric.js"

const host={environment:Effect.succeed({PATH:"/usr/bin"}),processIdentity:()=>Effect.succeed(null),tcpReady:()=>Effect.succeed(true),httpReady:()=>Effect.succeed([true,200] as const),executable:()=>Effect.succeed(null),readText:()=>Effect.succeed(null),readPrivateText:()=>Effect.succeed(null),writePrivateExclusive:()=>Effect.void,ensurePrivateDirectory:()=>Effect.void,unlinkIfPresent:()=>Effect.void,randomHex:()=>Effect.succeed("x".repeat(64)),nowUnixNs:Effect.succeed(1760000000000000000n),monotonicMs:Effect.sync(()=>performance.now()),launch:()=>Effect.die("launch must not run"),signalGroup:()=>Effect.die("signal must not run"),sleep:()=>Effect.void}
const bounded=Layer.succeed(BoundedSubprocess,{observe:()=>Effect.succeed({exitCode:0,signal:null,timedOut:false,outputTruncated:false,launchError:null,stdout:new TextEncoder().encode("20.4.0\n"),stderr:new Uint8Array()})})
const services=Layer.succeed(ResearchFabricRuntime,host)
it("reports and refuses an untracked listener without launching or signalling it",async()=>{const spec=fabricSpecs("/isolated","/isolated/bin").temporal;const status=await Effect.runPromise(researchFabricStatus("/isolated",spec).pipe(Effect.provide(services)));expect(status["state"]).toBe("foreign_or_untracked_listener");const start=await Effect.runPromise(startResearchFabricService("/isolated",spec,1_000).pipe(Effect.provide(Layer.merge(services,bounded)),Effect.either));expect(start._tag).toBe("Left");if(start._tag==="Left")expect(start.left.detail).toContain("refusing to replace")})
it("simulates a successful start with a Python-compatible numeric record",async()=>{const spec=fabricSpecs("/isolated","/isolated/bin").phoenix;let launched=false,record:string|null=null;const identity={pid:91,startTicks:4,cmdline:["/isolated/bin/phoenix"] as const};const simulated={...host,tcpReady:()=>Effect.succeed(launched),readText:()=>Effect.succeed(record),writePrivateExclusive:(_path:string,text:string)=>Effect.sync(()=>{if(_path.endsWith(".json"))record=text}),executable:()=>Effect.succeed({sha256:"x",realpath:"/isolated/bin/phoenix"}),launch:()=>Effect.sync(()=>{launched=true;return identity}),processIdentity:()=>Effect.succeed(launched?identity:null)};const result=await Effect.runPromise(startResearchFabricService("/isolated",spec,1_000).pipe(Effect.provide(Layer.merge(Layer.succeed(ResearchFabricRuntime,simulated),bounded))));expect(result["state"]).toBe("ready");expect(record).toContain('"started_unix_ns": 1760000000000000000')})
it("simulates a tracked service stopping after SIGTERM",async()=>{const spec=fabricSpecs("/isolated","/isolated/bin").temporal;const record=`{"schema":"hswm-research-fabric-process/v1","claim_boundary":"bounded infrastructure observation; not HSWM cognition, canonical admission, causal credit, continuous-learning evidence, or efficacy","service":"temporal","pid":91,"start_ticks":4,"executable":"/isolated/bin/temporal","executable_sha256":"x","version":"1.8.2","public_argv":[],"log_path":"/log","started_unix_ns":1760000000000000000}`;const identity={pid:91,startTicks:4,cmdline:["/isolated/bin/temporal"] as const};const signals:string[]=[];let removed=false;const simulated={...host,tcpReady:()=>Effect.succeed(false),readText:()=>Effect.succeed(removed?null:record),processIdentity:()=>Effect.succeed(signals.length===0?identity:null),executable:()=>Effect.succeed({sha256:"x",realpath:"/isolated/bin/temporal"}),signalGroup:(_pid:number,signal:NodeJS.Signals)=>Effect.sync(()=>{signals.push(signal)}),unlinkIfPresent:()=>Effect.sync(()=>{removed=true})};const result=await Effect.runPromise(stopResearchFabricService("/isolated",spec,100).pipe(Effect.provide(Layer.succeed(ResearchFabricRuntime,simulated))));expect(result["state"]).toBe("not_running");expect(signals).toEqual(["SIGTERM"]);expect(removed).toBe(true)})
it("refuses PID reuse before SIGKILL",async()=>{const spec=fabricSpecs("/isolated","/isolated/bin").temporal;const record=`{"schema":"hswm-research-fabric-process/v1","claim_boundary":"bounded infrastructure observation; not HSWM cognition, canonical admission, causal credit, continuous-learning evidence, or efficacy","service":"temporal","pid":91,"start_ticks":4,"executable":"/isolated/bin/temporal","executable_sha256":"x","version":"1.8.2","public_argv":[],"log_path":"/log","started_unix_ns":1760000000000000000}`;let calls=0;const signals: string[]=[];const mismatch={...host,readText:()=>Effect.succeed(record),processIdentity:()=>Effect.succeed(++calls===1?{pid:91,startTicks:4,cmdline:["/isolated/bin/temporal"] as const}:{pid:91,startTicks:5,cmdline:["/isolated/bin/temporal"] as const}),executable:()=>Effect.succeed({sha256:"x",realpath:"/isolated/bin/temporal"}),signalGroup:(_pid:number,signal:NodeJS.Signals)=>Effect.sync(()=>{signals.push(signal)})};const result=await Effect.runPromise(stopResearchFabricService("/isolated",spec,1).pipe(Effect.provide(Layer.succeed(ResearchFabricRuntime,mismatch)),Effect.either));expect(result._tag).toBe("Left");expect(signals).toEqual(["SIGTERM"]);if(result._tag==="Left")expect(result.left.detail).toContain("identity changed")})
