import { readFile } from "node:fs/promises"
import { resolve } from "node:path"
import { Either } from "effect"
import { expect,it } from "vitest"
import { adaptNativeUslV1 } from "../src/native-usl-v1-domain.js"
import { decodeNativeTaskJson } from "../src/native-task-json-domain.js"
const fixture=async()=>JSON.parse(await readFile(resolve(import.meta.dirname,"../../../../_research/usl_adapter/examples/preview.v1.json"),"utf8"))
const request=(input:any)=>({plan:input.plan,report:input.report,policy:input.policy,allowed_reads:input.preview.checks.allowed_reads,now:input.preview.checks.now,revision:input.preview.checks.revision})
it("projects the pinned v1 fixture to the complete Python golden output",async()=>{const input=await fixture();const result=adaptNativeUslV1(request(input));expect(Either.isRight(result)).toBe(true);if(Either.isRight(result))expect(result.right).toEqual({schema_version:"hswm-usl-observation-projection/v1",status:"READY",plan_digest:"c7c316cb2b7294a4d5e715dece29ca61af15b2efb622e87764adaa4c3257eb18",report_digest:"5127ac150313b662be27fc55c5e99c77db1e5b4dd912bcad0bd9ce0a8b0fd8ed",policy_digest:"9519dd03912ef0df7f44ccc2b50851755c2c76efd45cde937311781223d8fef7",namespace:"hswm.usl.development.example",observations:[{role:"usl",field:"references_resolve",value:true,revision:"authored-observation-r1",expires_at:1788868920,source:"eef9335aab3777410a26b29b52529fa1bcb80e19d8ef6df8b9195f1b84c72752"}],links:[{name:"development",meaning:"documents",participants:[{role:"code",resource:"implementation"},{role:"target",resource:"concept"},{role:"context",resource:"context"}],status:"READY",reasons:[]}],mapping_loss:["reference resolution only","no semantic truth","caller-bound report not attestation","no content extraction/credit/admission"]})})
it("withholds stale caller observations without treating them as semantic truth",async()=>{const input=await fixture();input.preview.checks.now+=120;const result=adaptNativeUslV1(request(input));expect(Either.isRight(result)).toBe(true);if(Either.isRight(result))expect(result.right).toMatchObject({status:"UNRESOLVED",observations:[]})})
it("rejects a caller report whose resolved content no longer matches its policy pin",async()=>{const input=await fixture();input.report.resources[0].resolution.contentHash="0".repeat(64);const result=adaptNativeUslV1(request(input));expect(result).toMatchObject({_tag:"Left",left:{detail:"resource pin mismatch: implementation"}})})
it("preserves a raw Python float token in the policy digest and freshness outcome",async()=>{const input=await fixture();input.policy.max_age_seconds=60.0;const raw=new TextEncoder().encode(JSON.stringify(request(input)).replace('"max_age_seconds":60','"max_age_seconds":60.0'));const decoded=decodeNativeTaskJson(raw);expect(Either.isRight(decoded)).toBe(true);if(Either.isRight(decoded)){const result=adaptNativeUslV1(decoded.right);expect(result).toEqual(Either.right({schema_version:"hswm-usl-observation-projection/v1",status:"UNRESOLVED",plan_digest:"c7c316cb2b7294a4d5e715dece29ca61af15b2efb622e87764adaa4c3257eb18",report_digest:"5127ac150313b662be27fc55c5e99c77db1e5b4dd912bcad0bd9ce0a8b0fd8ed",policy_digest:"2ef0dd690c41d5ee5c71586d0124f55ed308d0f23944d901c10a72ed5059a264",namespace:"hswm.usl.development.example",observations:[],links:[{name:"development",meaning:"documents",participants:[{role:"code",resource:"implementation"},{role:"target",resource:"concept"},{role:"context",resource:"context"}],status:"UNKNOWN",reasons:["RESOURCE:implementation_STALE","RESOURCE:concept_STALE","RESOURCE:context_STALE"]}],mapping_loss:["reference resolution only","no semantic truth","caller-bound report not attestation","no content extraction/credit/admission"]}))}})
