/** Replay W1-v2 receipts; never sends model requests or changes canonical state. */
import { readFile } from 'node:fs/promises'
import { isAbsolute, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { verifyPlan, protocol, sha, json, readJson, saveNew } from './runner.mts'
import { parseResponse } from '../local_semantic_execution_v1/analyze.mts'

type Row = Record<string, any>
const MODES = ['E0', 'E1', 'E2']
const INVARIANTS = new Set(['original', 'paraphrase-a', 'paraphrase-b', 'rename', 'reorder'])
async function jsonLines(path: string): Promise<any[]> { try { return (await readFile(path, 'utf8')).split('\n').filter(Boolean).map(JSON.parse) } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []; throw error } }
const reported = (value: unknown): number | null => typeof value === 'number' && Number.isSafeInteger(value) && value >= 0 ? value : null
const finiteNonnegative = (value: unknown) => typeof value === 'number' && Number.isFinite(value) && value >= 0
const nameFor = (ordinal: number, extension: string) => `${String(ordinal).padStart(4, '0')}.${extension}`
function cost(rows: Row[], field: string) { const values = rows.map(row => row[field]).filter((value): value is number => value !== null); return { sum_reported: values.length ? values.reduce((sum, value) => sum + value, 0) : null, reported_records: values.length, unreported_records: rows.length - values.length, status: values.length === rows.length ? 'REPORTED_ALL' : values.length ? 'PARTIALLY_REPORTED' : 'UNREPORTED' } }
export function summarizeRows(rows: Row[]) { const scheduled = rows.length, valid = rows.filter(row => row.valid).length, correct = rows.filter(row => row.correct).length; return { scheduled, attempted: rows.filter(row => row.attempted).length, completed: rows.filter(row => row.complete).length, valid, correct, invalid: rows.filter(row => row.complete && !row.valid).length, missing: rows.filter(row => !row.complete).length, accuracy: scheduled ? correct / scheduled : 0, coverage: scheduled ? valid / scheduled : 0, refusals: rows.filter(row => row.reason).reduce((all, row) => ({ ...all, [row.reason]: (all[row.reason] ?? 0) + 1 }), {}), e2_intermediates_correct: rows.filter(row => row.intermediates_correct === true).length, e2_intermediates_consistent: rows.filter(row => row.intermediates_consistent === true).length, intermediate_incorrect: rows.filter(row => row.intermediates_correct === false).length, e0_emitted_readout_disagreements: rows.filter(row => row.emitted_readout_agree === false).length, cost: { request_intents: rows.filter(row => row.attempted).length, request_accounting: 'Intent persisted before send; a crash can make actual network submission unknown.', elapsed_ms: cost(rows, 'elapsed_ms'), prompt_tokens: cost(rows, 'prompt_tokens'), completion_tokens: cost(rows, 'completion_tokens'), reasoning_tokens: cost(rows, 'reasoning_tokens'), read_tokens: 'UNINSTRUMENTED_COMPONENT_OF_PROMPT', update_tokens: 0, retry_tokens: 0, zero_basis: 'No update or retry model calls in this fixed instrument; never imputes missing usage.' } } }
function probabilities(rows: Row[]) { const values = rows.map(row => row.p1).filter((value): value is number => typeof value === 'number'); return { min: values.length ? Math.min(...values) : null, max: values.length ? Math.max(...values) : null, span: values.length ? Math.max(...values) - Math.min(...values) : null, reported: values.length, missing: rows.length - values.length } }
function serialIndex(records: any[], plan: any, kind: 'ATTEMPT' | 'RESULT') { const map = new Map<number, any>(); for (const [serial, record] of records.entries()) { const item = plan.schedule[serial]; if (!item || !Number.isInteger(record.ordinal) || record.ordinal !== serial || record.request_sha256 !== item.request_sha256 || map.has(record.ordinal)) throw new Error(`INVALID_${kind}_ORDINAL_OR_REQUEST`); map.set(record.ordinal, record) } return map }
function terminalIsValid(terminal: any, freeze: any, attempts: any[], results: any[], planned: number) { if (!terminal) return true; if (terminal.evidence_kind !== freeze.evidence_kind || terminal.planned !== planned || terminal.attempted !== attempts.length || !finiteNonnegative(terminal.elapsed_ms) || !['SCHEDULE_COMPLETED', 'WALL_BUDGET_STOPPED', 'ORIGINAL_PILOT_FAILED'].includes(terminal.status) || results.length !== attempts.length) return false; if (terminal.status === 'SCHEDULE_COMPLETED') return attempts.length === planned; if (terminal.status === 'WALL_BUDGET_STOPPED') return attempts.length < planned; return attempts.length === 384 }
function pilotPassed(rows: Row[]) { return MODES.some(mode => rows.filter(row => row.ordinal < 384 && row.mode === mode && row.valid && row.correct).length === 128) }
async function validatePreflight(out: string, freeze: any) {
  const expected = [{ name: 'models', file: 'preflight-models.json' }, { name: 'token-0', file: 'preflight-token-0.json' }, { name: 'token-1', file: 'preflight-token-1.json' }]
  if (!Array.isArray(freeze.preflight) || freeze.preflight.length !== expected.length) throw new Error('PREFLIGHT_RECEIPT_MISMATCH')
  for (const [index, item] of expected.entries()) {
    const receipt = freeze.preflight[index]
    if (!receipt || receipt.name !== item.name || receipt.status !== 200 || !finiteNonnegative(receipt.elapsed_ms) || typeof receipt.response_sha256 !== 'string') throw new Error('PREFLIGHT_RECEIPT_MISMATCH')
    const raw = await readFile(join(out, item.file), 'utf8'); if (sha(raw) !== receipt.response_sha256) throw new Error('PREFLIGHT_RESPONSE_BYTES_MISMATCH')
    let body: any; try { body = JSON.parse(raw) } catch { throw new Error('PREFLIGHT_INVALID_JSON') }
    if (item.name === 'models' && !body.data?.some((model: any) => model?.id === protocol.model.served_name)) throw new Error('PREFLIGHT_SERVED_MODEL_MISMATCH')
    if (item.name.startsWith('token-') && JSON.stringify(body.tokens) !== JSON.stringify([protocol.model.candidate_token_ids[Number(item.name.at(-1))]])) throw new Error('PREFLIGHT_CANDIDATE_TOKEN_MISMATCH')
  }
}
function validateObservedAttestation(attestation: any, pins: any) {
  if (!attestation || attestation.schema_version !== 'hswm-local-semantic-serving-attestation/v1' || attestation.repository !== protocol.model.repository || attestation.revision !== protocol.model.revision || attestation.served_name !== protocol.model.served_name || attestation.vllm_version !== '0.25.1' || attestation.node_version !== pins.node || attestation.effect_version !== pins.effect || attestation.authority_class !== 'LOCAL_OPERATOR_DECLARATION' || attestation.checkpoint_set_complete !== true || !Array.isArray(attestation.artifacts)) throw new Error('SERVING_PIN_MISMATCH')
  for (const field of ['precision', 'model_license', 'serving_evidence_note']) if (typeof attestation[field] !== 'string' || !attestation[field].trim()) throw new Error(`MISSING_ATTESTATION_${field}`)
  const endpoint = new URL(attestation.base_url)
  if (endpoint.protocol !== 'http:' || endpoint.hostname !== '127.0.0.1' || endpoint.username || endpoint.password || endpoint.search || endpoint.hash || endpoint.pathname !== '/') throw new Error('ATTESTATION_ENDPOINT_MISMATCH')
  for (const role of ['checkpoint', 'tokenizer', 'chat_template', 'server_config', 'server_runtime']) if (!attestation.artifacts.some((artifact: any) => artifact?.role === role && typeof artifact.sha256 === 'string' && /^[a-f0-9]{64}$/.test(artifact.sha256))) throw new Error(`MISSING_ATTESTATION_ARTIFACT_${role}`)
  for (const artifact of attestation.artifacts) if (!artifact || typeof artifact.path !== 'string' || !isAbsolute(artifact.path) || typeof artifact.sha256 !== 'string' || !/^[a-f0-9]{64}$/.test(artifact.sha256)) throw new Error('ATTESTATION_ARTIFACT_RECEIPT_MISMATCH')
}

export async function analyze(out: string) {
  const plan: any = await verifyPlan(out), freeze: any = await readJson(join(out, 'freeze.json')), started: any = await readJson(join(out, 'started.json')), planHash = sha(json(plan))
  if (!['FIXTURE_ONLY', 'OBSERVED_MODEL_HTTP'].includes(freeze.evidence_kind) || freeze.plan_sha256 !== planHash || started.plan_sha256 !== planHash || started.evidence_kind !== freeze.evidence_kind || json(freeze.source_pins) !== json(plan.pins)) throw new Error('FREEZE_PLAN_MISMATCH')
  await validatePreflight(out, freeze)
  if (freeze.evidence_kind === 'OBSERVED_MODEL_HTTP') validateObservedAttestation(freeze.attestation, plan.pins)
  const referenceRaw = await readFile(join(out, 'reference.json'), 'utf8'); if (sha(referenceRaw) !== plan.reference_sha256) throw new Error('REFERENCE_DIGEST_MISMATCH')
  const reference = new Map(JSON.parse(referenceRaw).map((entry: any) => [entry.caseId, entry.expected])), frame = new Map(plan.frames.map((entry: any) => [entry.caseId, entry]))
  const attempts = await jsonLines(join(out, 'attempts.jsonl')), results = await jsonLines(join(out, 'results.jsonl'))
  if (results.length > attempts.length) throw new Error('RESULT_WITHOUT_ATTEMPT')
  const attemptsByOrdinal = serialIndex(attempts, plan, 'ATTEMPT'), resultsByOrdinal = serialIndex(results, plan, 'RESULT')
  for (const result of results) if (!attemptsByOrdinal.has(result.ordinal)) throw new Error('RESULT_WITHOUT_ATTEMPT')
  let terminal: any = null; try { terminal = await readJson(join(out, 'completed.json')) } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error }
  if (!terminalIsValid(terminal, freeze, attempts, results, plan.schedule.length)) throw new Error('TERMINAL_RECEIPT_MISMATCH')
  const rows: Row[] = []
  for (const item of plan.schedule) {
    const attempt = attemptsByOrdinal.get(item.ordinal), result = resultsByOrdinal.get(item.ordinal), metadata = frame.get(item.caseId)
    if (!metadata) throw new Error('SCHEDULE_CASE_NOT_IN_FRAME_MANIFEST')
    const base: Row = { ordinal: item.ordinal, caseId: item.caseId, baseCaseId: metadata.baseCaseId, transform: metadata.transform, familyIndex: metadata.familyIndex, mode: item.mode, kind: item.kind, repetition: item.repetition, sentinelId: item.sentinelId, attempted: !!attempt, complete: !!result, valid: false, correct: false, answer: null, p1: null, emitted_bit: null, elapsed_ms: result?.elapsed_ms ?? null, prompt_tokens: null, completion_tokens: null, reasoning_tokens: null }
    if (attempt) { if (attempt.caseId !== item.caseId || attempt.mode !== item.mode) throw new Error('ATTEMPT_CASE_OR_MODE_MISMATCH'); const body = await readFile(join(out, 'http', nameFor(item.ordinal, 'request.json'))); if (sha(body) !== item.request_sha256) throw new Error('REQUEST_BYTES_MISMATCH') }
    if (!result) { rows.push({ ...base, reason: attempt ? 'ATTEMPT_WITHOUT_COMPLETION' : 'NOT_ATTEMPTED' }); continue }
    if (!finiteNonnegative(result.elapsed_ms)) throw new Error('INVALID_ELAPSED_TIME')
    if (result.response_sha256 === null) { rows.push({ ...base, reason: result.transport_failure ?? 'NO_RESPONSE' }); continue }
    if (typeof result.response_sha256 !== 'string') throw new Error('INVALID_RESPONSE_HASH')
    const raw = await readFile(join(out, 'http', nameFor(item.ordinal, 'response.json')), 'utf8'); if (sha(raw) !== result.response_sha256) throw new Error('RESPONSE_BYTES_MISMATCH')
    let response: any; try { response = JSON.parse(raw) } catch { rows.push({ ...base, reason: 'INVALID_HTTP_JSON' }); continue }
    const usage = { prompt_tokens: reported(response?.usage?.prompt_tokens), completion_tokens: reported(response?.usage?.completion_tokens), reasoning_tokens: reported(response?.usage?.completion_tokens_details?.reasoning_tokens) }
    if (!Number.isInteger(result.status) || result.status < 200 || result.status >= 300) { rows.push({ ...base, ...usage, reason: `HTTP_${result.status}` }); continue }
    const parsed: any = parseResponse(item.mode, response); if (!parsed.valid) { rows.push({ ...base, ...usage, reason: parsed.reason }); continue }
    const output = parsed.output, expected = reference.get(item.caseId)
    rows.push({ ...base, ...usage, valid: true, correct: output.answer === expected?.answer, answer: output.answer, ...(item.mode === 'E0' ? { p1: parsed.p1, emitted_bit: parsed.emitted_bit, emitted_readout_agree: parsed.emitted_bit === output.answer } : {}), ...(item.mode === 'E2' ? { intermediates_correct: ['base', 'context_flip', 'exception_flip'].every(key => output[key] === expected?.[key]), intermediates_consistent: (output.base ^ output.context_flip ^ output.exception_flip) === output.answer } : {}) })
  }
  if (terminal?.status === 'ORIGINAL_PILOT_FAILED' && pilotPassed(rows)) throw new Error('ORIGINAL_PILOT_RECEIPT_LIES')
  if (terminal?.status === 'WALL_BUDGET_STOPPED' && attempts.length === 384 && !pilotPassed(rows)) throw new Error('WALL_STOPPED_AFTER_FAILED_ORIGINAL_PILOT')
  if (attempts.length > 384 && !pilotPassed(rows)) throw new Error('POST_PILOT_REQUESTS_AFTER_FAILED_ORIGINAL_PILOT')
  if (terminal && terminal.status !== 'SCHEDULE_COMPLETED' && results.length === plan.schedule.length) throw new Error('NONCOMPLETE_TERMINAL_HAS_FULL_RESULTS')
  const arms: any = {}; for (const mode of MODES) { const modeRows = rows.filter(row => row.mode === mode); arms[mode] = { all: summarizeRows(modeRows), census: summarizeRows(modeRows.filter(row => row.kind === 'census')), sentinel: summarizeRows(modeRows.filter(row => row.kind === 'sentinel')), probability: probabilities(modeRows) } }
  const byFamilyTransform: any = {}; for (const mode of MODES) { byFamilyTransform[mode] = {}; for (const transform of plan.transform_manifest) byFamilyTransform[mode][transform] = Object.fromEntries([0, 1, 2, 3].map(family => [String(family), summarizeRows(rows.filter(row => row.mode === mode && row.kind === 'census' && row.transform === transform && row.familyIndex === family))])) }
  const invariantInstability: any = {}; for (const mode of MODES) for (const baseCaseId of new Set(rows.map(row => row.baseCaseId))) { const values = rows.filter(row => row.mode === mode && row.kind === 'census' && row.baseCaseId === baseCaseId && INVARIANTS.has(row.transform)), answers = values.filter(row => row.valid).map(row => row.answer); invariantInstability[`${mode}:${baseCaseId}`] = { variants: values.length, valid: answers.length, missing: values.filter(row => !row.complete).length, invalid: values.filter(row => row.complete && !row.valid).length, bits: [...new Set(answers)], unstable: new Set(answers).size > 1 } }
  const sentinelStability: any = {}; for (const sentinel of plan.sentinels) for (const mode of MODES) { const baseline = rows.find(row => row.kind === 'census' && row.caseId === sentinel.caseId && row.mode === mode), repeats = rows.filter(row => row.kind === 'sentinel' && row.sentinelId === sentinel.sentinelId && row.mode === mode), sequence = [baseline, ...repeats], valid = sequence.filter((row): row is Row => !!row?.valid), p1s = valid.map(row => row.p1).filter((value): value is number => typeof value === 'number'); sentinelStability[`${mode}:${sentinel.sentinelId}`] = { comparisons: 21, sequence: sequence.map(row => row?.valid ? row.answer : null), valid: valid.length, missing: sequence.filter(row => !row || !row.complete).length, invalid: sequence.filter(row => row?.complete && !row.valid).length, bits: [...new Set(valid.map(row => row.answer))], bit_instability: new Set(valid.map(row => row.answer)).size > 1, p1: { min: p1s.length ? Math.min(...p1s) : null, max: p1s.length ? Math.max(...p1s) : null, span: p1s.length ? Math.max(...p1s) - Math.min(...p1s) : null } } }
  const roleExchange: any = {}; for (const mode of MODES) { const all = rows.filter(row => row.mode === mode && row.kind === 'census' && row.transform === 'role-exchange'), original = new Map(rows.filter(row => row.mode === mode && row.transform === 'original' && row.kind === 'census').map(row => [row.baseCaseId, row])); const changedInput = all.filter(row => frame.get(row.caseId).inputJson !== frame.get(`original:${row.baseCaseId}`).inputJson), changedAnswer = all.filter(row => reference.get(row.caseId)?.answer !== reference.get(`original:${row.baseCaseId}`)?.answer), changedIntermediate = all.filter(row => { const a = reference.get(row.caseId), b = reference.get(`original:${row.baseCaseId}`); return a && b && (a.base !== b.base || a.context_flip !== b.context_flip || a.exception_flip !== b.exception_flip) }); roleExchange[mode] = { all: summarizeRows(all), changed_input: summarizeRows(changedInput), changed_answer: summarizeRows(changedAnswer), changed_intermediate: summarizeRows(changedIntermediate), descriptive_answer_delta_from_original: all.filter(row => row.valid && original.get(row.baseCaseId)?.valid && row.answer !== original.get(row.baseCaseId).answer).length } }
  const readinessEligibleArms = MODES.filter(mode => { const metric = arms[mode].all; const invariantStable = Object.entries(invariantInstability).filter(([key]) => key.startsWith(`${mode}:`)).every(([, value]: any) => value.valid === 5 && !value.unstable); const sentinelStable = Object.entries(sentinelStability).filter(([key]) => key.startsWith(`${mode}:`)).every(([, value]: any) => value.valid === 21 && !value.bit_instability); return metric.scheduled === 928 && metric.valid === 928 && metric.correct === 928 && invariantStable && sentinelStable })
  const modelReady = freeze.evidence_kind === 'OBSERVED_MODEL_HTTP' && terminal?.status === 'SCHEDULE_COMPLETED' && readinessEligibleArms.length > 0
  return { schema_version: 'hswm-local-semantic-w1-v2-analysis/v2', evidence_kind: freeze.evidence_kind, status: terminal?.status === 'SCHEDULE_COMPLETED' && results.length === plan.schedule.length ? 'COMPLETE_CENSUS' : 'INCOMPLETE_OR_UNTERMINATED_CENSUS', terminal_receipt_present: terminal !== null, terminal_status: terminal?.status ?? null, planned: plan.schedule.length, attempted: attempts.length, completed_records: results.length, missing_results: plan.schedule.length - results.length, plan_sha256: planHash, freeze_sha256: sha(await readFile(join(out, 'freeze.json'))), arms, by_family_transform: byFamilyTransform, role_exchange: roleExchange, pairwise_correct_count_delta: { E1_minus_E0: arms.E1.all.correct - arms.E0.all.correct, E2_minus_E0: arms.E2.all.correct - arms.E0.all.correct, E2_minus_E1: arms.E2.all.correct - arms.E1.all.correct }, invariant_bit_instability: invariantInstability, sentinel_stability: sentinelStability, readiness_eligible_arms: readinessEligibleArms, readiness: modelReady ? 'OBSERVED_MODEL_HTTP_W1_READY' : freeze.evidence_kind === 'FIXTURE_ONLY' ? 'FIXTURE_ONLY_NOT_MODEL_READINESS' : 'NOT_READY', claim_ceiling: protocol.claim_ceiling, independent_world_claim: false, limitations: ['Finite authored census; no independent-world generalization or causal learning.', 'This instrument does not establish learning efficacy or CR/FCL.', 'Missing usage is unreported, never zero.'], observations: rows }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) { const [out, destination] = process.argv.slice(2); if (!out || !destination) throw new Error('Usage: node analyze.mts PRIVATE_RUN_DIR NEW_PRIVATE_ANALYSIS_JSON'); const result = await analyze(resolve(out)); await saveNew(resolve(destination), result); console.log(JSON.stringify({ status: result.status, evidence_kind: result.evidence_kind, attempted: result.attempted, readiness: result.readiness })) }
