import Std

/-!
# Constructive synthesis of a role-bearing relation

A bounded grammar grows candidate relation programs from primitive input
features.  Synthesis only reads generated programs and post-Step labelled
observations; it has no target-program or desired-gain parameter.  The theorems
show structural generation and finite, hypothesis-class-relative identification.
They do not claim open-world relation discovery, sample-efficient induction,
or an external source of certified labels.
-/

namespace HSWM.ConstructiveRelationSynthesis

/-- Three labelled input positions of one role-bearing relation. -/
abbrev Input := Fin 3 → Bool

/-- A small compositional grammar; `and` creates a relation not present as a primitive. -/
inductive Expr where
  | input (index : Fin 3)
  | and (left right : Expr)
deriving DecidableEq, Repr

/-- Interpret generated syntax as a Boolean semantic relation. -/
def eval : Expr → Input → Bool
  | .input index, input => input index
  | .and left right, input => eval left input && eval right input

/-- Initial primitive pool contains only the three individual role inputs. -/
def primitives : List Expr := [.input 0, .input 1, .input 2]

/-- One real grammar-growth pass retains old syntax and adds all binary conjunctions. -/
def grow (pool : List Expr) : List Expr :=
  pool ++ pool.flatMap (fun left => pool.map (fun right => Expr.and left right))

/-- Bounded enumerative candidate generation. -/
def generated : Nat → List Expr
  | 0 => primitives
  | depth + 1 => grow (generated depth)

/-- The syntactic construction depth used for a structural completeness theorem. -/
def depth : Expr → Nat
  | .input _ => 0
  | .and left right => Nat.succ (max (depth left) (depth right))

/-- Every existing candidate survives one grammar-growth pass. -/
theorem mem_grow_of_mem {pool : List Expr} {expression : Expr}
    (member : expression ∈ pool) : expression ∈ grow pool := by
  simp [grow, member]

/-- A conjunction of candidates already generated by depth `n` is generated by depth `n + 1`. -/
theorem and_mem_grow {pool : List Expr} {left right : Expr}
    (leftMember : left ∈ pool) (rightMember : right ∈ pool) :
    Expr.and left right ∈ grow pool := by
  simp [grow, leftMember, rightMember]

/-- Any expression of syntactic depth at most `n` occurs in the actual generated list. -/
theorem generated_complete (expression : Expr) (n : Nat)
    (bounded : depth expression ≤ n) : expression ∈ generated n := by
  induction n generalizing expression with
  | zero =>
    cases expression with
    | input index =>
      have possibilities : index = 0 ∨ index = 1 ∨ index = 2 := by omega
      rcases possibilities with h | h | h <;> simp [generated, primitives, h]
    | and left right => simp [depth] at bounded
  | succ n inductionHypothesis =>
    cases expression with
    | input index =>
      exact mem_grow_of_mem (by simpa [generated, primitives] using
        (show Expr.input index ∈ generated n from inductionHypothesis (Expr.input index) (by simp [depth])))
    | and left right =>
      have leftBound : depth left ≤ n := by
        simp [depth] at bounded
        omega
      have rightBound : depth right ≤ n := by
        simp [depth] at bounded
        omega
      exact and_mem_grow
        (inductionHypothesis left leftBound)
        (inductionHypothesis right rightBound)

/-- Role labels for the generated three-input relation. -/
inductive Role where
  | sourceOne | sourceTwo | sourceThree
deriving DecidableEq, Repr

/-- A relation factor with three explicitly addressed role-bearing incidences. -/
structure RoleRelation where
  payload : Expr
  member : Fin 3 → Role × Fin 3

/-- Express one generated program as a tagged-incidence n-ary relation. -/
def relation (program : Expr) : RoleRelation :=
  { payload := program
    member := fun slot =>
      if slot = 0 then (.sourceOne, 0)
      else if slot = 1 then (.sourceTwo, 1)
      else (.sourceThree, 2) }

/-- The relation payload evaluates by the same compositional grammar semantics. -/
theorem relation_payload_evaluates (program : Expr) (input : Input) :
    eval (relation program).payload input = eval program input := rfl

/-- An outcome observed after a local prediction. -/
structure Example where
  input : Input
  outcome : Bool

/-- Outcome consistency is computed from syntax and observations alone. -/
def consistent (program : Expr) (observations : List Example) : Bool :=
  observations.all (fun observation => decide (eval program observation.input = observation.outcome))

/-- Select the first outcome-consistent generated program. -/
def synthesizeFrom : List Expr → List Example → Option Expr
  | [], _ => none
  | program :: rest, observations =>
      if consistent program observations then some program else synthesizeFrom rest observations

/-- Bounded synthesis runs over exactly the generated syntax at the requested depth. -/
def synthesize (n : Nat) (observations : List Example) : Option Expr :=
  synthesizeFrom (generated n) observations

/-- A target that is generated and outcome-consistent guarantees a computed synthesis result. -/
theorem synthesizeFrom_some_of_member_consistent
    (pool : List Expr) (observations : List Example) (target : Expr)
    (member : target ∈ pool) (agrees : consistent target observations = true) :
    ∃ found, synthesizeFrom pool observations = some found ∧
      found ∈ pool ∧ consistent found observations = true := by
  induction pool with
  | nil => simp at member
  | cons program rest inductionHypothesis =>
    by_cases programAgrees : consistent program observations = true
    · exact ⟨program, by simp [synthesizeFrom, programAgrees], by simp, programAgrees⟩
    · simp only [List.mem_cons] at member
      rcases member with same | member
      · subst same
        exact False.elim (programAgrees agrees)
      · obtain ⟨found, result, foundMember, foundAgrees⟩ := inductionHypothesis member
        exact ⟨found, by simp [synthesizeFrom, programAgrees, result],
          by simp [foundMember], foundAgrees⟩

/-- All eight inputs, retained only for a finite semantic-equivalence check. -/
def allInputs : List Input :=
  [fun _ => false,
   fun index => index = 0,
   fun index => index = 1,
   fun index => index = 2,
   fun index => index = 0 || index = 1,
   fun index => index = 0 || index = 2,
   fun index => index = 1 || index = 2,
   fun _ => true]

/-- Equality of relation behavior on the declared finite input domain. -/
def sameOnAll (left right : Expr) : Bool :=
  allInputs.all (fun input => decide (eval left input = eval right input))

/-- A computable, hypothesis-class-relative identification check. -/
def identifies (observations : List Example) (target : Expr) (pool : List Expr) : Bool :=
  pool.all (fun candidate =>
    if consistent candidate observations then sameOnAll candidate target else true)

/-- Passing the finite check entails identification within exactly that finite pool. -/
theorem identifies_sound (observations : List Example) (target : Expr) (pool : List Expr)
    (checked : identifies observations target pool = true) (candidate : Expr)
    (member : candidate ∈ pool) (agrees : consistent candidate observations = true) :
    sameOnAll candidate target = true := by
  have each := List.all_eq_true.mp checked candidate member
  simpa [identifies, agrees] using each

/-- A generated and identified target yields a semantically equivalent computed candidate. -/
theorem synthesis_equivalent_of_identifies (n : Nat) (observations : List Example) (target : Expr)
    (generatedTarget : target ∈ generated n) (targetAgrees : consistent target observations = true)
    (identifiesCheck : identifies observations target (generated n) = true) :
    ∃ found, synthesize n observations = some found ∧ sameOnAll found target = true := by
  obtain ⟨found, foundResult, foundMember, foundAgrees⟩ :=
    synthesizeFrom_some_of_member_consistent (generated n) observations target generatedTarget targetAgrees
  exact ⟨found, foundResult,
    identifies_sound observations target (generated n) identifiesCheck found foundMember foundAgrees⟩

/-- A genuinely ternary conjunction absent from the initial primitive pool. -/
def conjunction : Expr := Expr.and (.input 0) (Expr.and (.input 1) (.input 2))

theorem conjunction_not_primitive : conjunction ∉ primitives := by decide

theorem conjunction_generated : conjunction ∈ generated 2 := by
  apply generated_complete conjunction 2
  decide

/-- Four separating outcomes for this bounded conjunction grammar. -/
def separatingExamples : List Example :=
  [⟨fun _ => true, true⟩,
   ⟨fun index => index = 0 || index = 1, false⟩,
   ⟨fun index => index = 0 || index = 2, false⟩,
   ⟨fun index => index = 1 || index = 2, false⟩]

theorem conjunction_consistent : consistent conjunction separatingExamples = true := by decide

/-- The bounded enumerative search computes this exact generated syntax. -/
theorem synthesis_returns_conjunction :
    synthesize 2 separatingExamples = some conjunction := by rfl

/-- The computed result has the conjunction semantics on every input, not only `allInputs`. -/
theorem computed_synthesis_correct_forall (found : Expr) (input : Input)
    (returned : synthesize 2 separatingExamples = some found) :
    eval found input = eval conjunction input := by
  rw [synthesis_returns_conjunction] at returned
  injection returned with equal
  subst found
  rfl

/-- Every primitive input feature differs semantically from the generated ternary conjunction. -/
theorem conjunction_semantically_novel_from_every_primitive (index : Fin 3) :
    ∃ input : Input, eval conjunction input ≠ eval (.input index) input := by
  refine ⟨fun position => decide (position = index), ?_⟩
  have possibilities : index = 0 ∨ index = 1 ∨ index = 2 := by omega
  rcases possibilities with first | second | third
  · subst index
    decide
  · subst index
    decide
  · subst index
    decide

/-- This input is intentionally held out from the separating outcome list. -/
def allFalse : Input := fun _ => false

theorem allFalse_not_in_separating_inputs :
    allFalse ∉ separatingExamples.map Example.input := by
  change allFalse ∉
    [fun _ => true,
     fun index => index = 0 || index = 1,
     fun index => index = 0 || index = 2,
     fun index => index = 1 || index = 2]
  intro member
  simp only [List.mem_cons, List.not_mem_nil, or_false] at member
  rcases member with first | second | third | fourth
  · have atZero := congrFun first 0
    simp [allFalse] at atZero
  · have atZero := congrFun second 0
    simp [allFalse] at atZero
  · have atZero := congrFun third 0
    simp [allFalse] at atZero
  · have atOne := congrFun fourth 1
    simp [allFalse] at atOne

/-- Exhaustive finite check: depth-two grammar candidates matching those outcomes have the same law. -/
theorem separating_observations_identify_conjunction :
    identifies separatingExamples conjunction (generated 2) = true := by decide

/-- The computed search returns a generated semantic relation equivalent on all eight inputs. -/
theorem conjunction_synthesized_semantically :
    ∃ found, synthesize 2 separatingExamples = some found ∧ sameOnAll found conjunction = true :=
  synthesis_equivalent_of_identifies 2 separatingExamples conjunction conjunction_generated
    conjunction_consistent separating_observations_identify_conjunction

/-- A held-out all-false input is predicted correctly by every such synthesized result. -/
theorem conjunction_synthesis_predicts_untrained_false :
    ∃ found, synthesize 2 separatingExamples = some found ∧
      eval found (fun _ => false) = false := by
  obtain ⟨found, foundResult, equivalent⟩ := conjunction_synthesized_semantically
  refine ⟨found, foundResult, ?_⟩
  have atFalse : eval found (fun _ => false) = eval conjunction (fun _ => false) := by
    unfold sameOnAll at equivalent
    exact of_decide_eq_true
      (List.all_eq_true.mp equivalent (fun _ => false) (by simp [allInputs]))
  rw [atFalse]
  decide

end HSWM.ConstructiveRelationSynthesis
