import { createHash } from "node:crypto"
import { readFile, writeFile } from "node:fs/promises"
import { createRequire } from "node:module"
const require=createRequire(new URL("../../src/hswm/effect-runtime/package.json",import.meta.url));const {Either}=require("effect") as typeof import("effect")
const {decodeKgBundleSource}=await import("../../src/hswm/effect-runtime/dist/native-kg-bundle-domain.js")
const sha=(x:Uint8Array|string)=>createHash("sha256").update(x).digest("hex"), out="ontology/development/HSWM_VALIDATION_GRAPH_2026-09-22.v1.json", profilePath="_research/hswm_validation_graph_2026-09-22/profile.v1.json"
const paths=[profilePath,"ontology/queries/hswm_validation_graph_2026-09-22/README.md","docs/operations/HSWM_VALIDATION_GRAPH_2026-09-22.md","docs/operations/artifacts/hswm_validation_graph_2026-09-22/skill-use.v1.json","docs/operations/artifacts/hswm_validation_graph_2026-09-22/standard-review.v1.json","ontology/workspace/HSWM_WORKSPACE.v1.json","src/hswm/effect-runtime/package-lock.json","schemas/HSWM_KG_BUNDLE_RDF_PROJECTION_SHACL_1_0_V2.ttl","_research/hswm_validation_graph_2026-09-22/fixtures.mjs","_research/hswm_validation_graph_2026-09-22/build.mts","_research/hswm_validation_graph_2026-09-22/verify.mjs","_research/jev_research_work_plan_2026-09-22/plan.v1.json","ontology/development/HSWM_JEV_RESEARCH_WORK_PLAN_2026-09-22.v1.json","ontology/development/HSWM_JEV_GRAPH_ENGINEERING_2026-09-22.v1.json","schemas/HSWM_VALIDATION_RECORDS_SHACL_1_0.v1.ttl",...['lineage_violations.rq','split_violations.rq','accounting_violations.rq','joint_scale_violations.rq','unresolved_evidence.rq'].map(x=>`ontology/queries/hswm_validation_graph_2026-09-22/${x}`)]
const bindings=await Promise.all(paths.map(async path=>({path,sha256:sha(await readFile(path))}))), by=new Map(bindings.map(x=>[x.path,x.sha256])), profile=JSON.parse(await readFile(profilePath,"utf8")), prior=JSON.parse(await readFile("ontology/development/HSWM_JEV_RESEARCH_WORK_PLAN_2026-09-22.v1.json","utf8"))
const nodes:any[]=[],relations:any[]=[];const root="sym:AbstractNode:hswm-validation-graph-2026-09-22",id=(k:string,x:string)=>`sym:${k}:hswm-validation-20260922-${sha(x).slice(0,18)}`
const add=(uid:string,label:string,role:string,name:string,props:any={})=>{const ref=props.source_ref;nodes.push({uid,labels:label==='AbstractNode'?['Concept','AbstractNode']:[label],properties:{name,description:"Declared future validation contract; not a completed run or efficacy evidence.",standard_graph_role:role,authority_class:"SECONDARY_AI",ontology_authority_class_v1:"SECONDARY_AI",ontology_kind_v1:"CONCEPT",ontology_domain_v1:"ENGINEERING",ontology_plane_v1:"RESEARCH_PROJECTION",ontology_canonical_scope_v1:"PENDING",ontology_epistemic_state_v1:"PENDING",ontology_record_lifecycle_v1:"ACTIVE",ontology_review_required_v1:true,ontology_sensitivity_v1:"NORMAL",responsibility_owner:"validation_graph_research_2026_09_22",claim_boundary:"DECLARED_STRUCTURE_NOT_EFFICACY",projection_nonclaim:"NOT_COGNITION_ROUTING_ADMISSION_OR_LEARNING",cr_fcl_promotion:false,status:"NOT_RUN",...props,...(ref?{source_sha256:by.get(ref)}:{})}});return uid}
const link=(a:string,t:string,b:string)=>relations.push({from_uid:a,type:t,to_uid:b,authority_class:"SECONDARY_AI",scope:"FUTURE_VALIDATION_CONTRACT",status:"NOT_RUN"})
const sourceNodes=new Map<string,string>();const source=(p:string)=>sourceNodes.get(p)??(sourceNodes.set(p,add(id("Reference",p),"Reference","ENGINEERING_SOURCE",p,{source_ref:p,source_path:p})),sourceNodes.get(p)!)
const r=add(root,"AbstractNode","VALIDATION_GRAPH_ROOT","HSWM validation graph 2026-09-22",{source_ref:profilePath,claim_ceiling:profile.claim_ceiling});for(const p of paths)link(r,"HAS_SOURCE",source(p))
const priorNodes=new Map(prior.nodes.map((n:any)=>[n.properties.task_id,n]));for(const track of profile.tracks){const t=add(id("Concept",track.id),"Concept","VALIDATION_TRACK",track.id,{source_ref:profilePath,track_id:track.id,contract:track.contract??track.id,status:"NOT_ASSESSED"});link(r,"HAS_CONCEPT",t);for(const task of track.tasks){const pn=priorNodes.get(task);if(!pn)throw Error(`missing prior task ${task}`);const n=add(id("Concept",task),"Concept","VALIDATION_TRACK_TASK",task,{source_ref:profilePath,track_id:track.id,task_id:task,status:track.id==='HYPERON'?"NOT_EVALUATED":"NOT_RUN"});link(t,"HAS_CONCEPT",n);link(n,"ABOUT",pn.uid)}}
const c=add(id("Concept","record"),"Concept","VALIDATION_RECORD_PROFILE","Reusable future evidence record profile",{source_ref:profilePath,required_fields:profile.common_record.required_scalar_fields,record_roles:profile.record_roles,status:"NOT_ASSESSED"});link(r,"HAS_CONCEPT",c)
const anchors=[...priorNodes.values()].filter((n:any)=>profile.tracks.some((t:any)=>t.tasks.includes(n.properties.task_id))).map((n:any)=>({uid:n.uid,name:n.properties.name,required_labels:n.labels}));const b={schema_version:"hswm-kg-bundle/v1",bundle_uid:root,status:"PLANNED_NOT_EXECUTED",nonclaim:"FUTURE_VALIDATION_CONTRACT_NOT_ACTUAL_EVIDENCE_OR_EFFICACY",source_accessed_on:"2026-09-22",authority_boundary:"SECONDARY_AI planning projection only",artifact_bindings:bindings,expected_counts:{nodes:nodes.length,anchors:anchors.length,relations:relations.length},anchors,nodes,relations}, bytes=Buffer.from(JSON.stringify(b,null,2)+"\n");Either.getOrThrowWith(decodeKgBundleSource({sourceId:"validation",rawBytes:bytes},"v2"),(e:any)=>e);await writeFile(out,bytes,{flag:"wx"});console.log(JSON.stringify({path:out,sha256:sha(bytes),...b.expected_counts}))
