/** Effect shell for reproducible, source-bound knowledge catalog projections. */
import { createHash } from "node:crypto"
import { Effect, Either } from "effect"
import { decodeCanonicalJsonBytes } from "./canonical-atom-v2-json.js"
import { BoundedSubprocess, PosixFileSystem } from "./effect-posix-services.js"
import { compileKnowledgeMap, declareKnowledgeMapCatalogPaths, knowledgeMapSourceIndex, type SourceBytes } from "./knowledge-map-domain.js"
import { compileResearchTooling, researchToolingSourceIndex, type FixedGitSource } from "./research-tooling-domain.js"

export const KNOWLEDGE_CATALOG_CURATOR_COMMIT = "974c64418c9f29248eb538ffa78912bfa12eb0ea" as const
const MAP = { catalog: "docs/operations/artifacts/hswm_knowledge_map_2026-09-13/source-catalog.json", bundle: "ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_2026-09-13.v1.json", index: "docs/operations/artifacts/hswm_knowledge_map_2026-09-13/source-index.md" }
const RESEARCH = { catalog: "docs/research/artifacts/hswm_research_tooling_2026-09-13/source-catalog.json", bundle: "ontology/research_tooling/HSWM_SCIENTIFIC_RESEARCH_TOOLING_2026-09-13.v1.json", index: "docs/research/artifacts/hswm_research_tooling_2026-09-13/source-index.md" }
const MAP_RAW: readonly string[] = Object.freeze(["ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_TOPICS_2026-09-13.v1.json", "ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_COVERAGE_2026-09-13.v1.json", "docs/operations/artifacts/hswm_knowledge_map_2026-09-13/live-resolution.json"])
const RESEARCH_PREFIX = "_research/graph_standards/research_tooling_2026-09-13/"
export class KnowledgeCatalogRuntimeError extends Error { readonly _tag = "KnowledgeCatalogRuntimeError" }
export interface CatalogArtifacts { readonly catalog: Readonly<Record<string, unknown>>; readonly bundle: Readonly<Record<string, unknown>>; readonly sourceIndex: Uint8Array }
interface Pin { readonly path: string; readonly sha256: string }
const sha = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex")
const obj = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v)
const sortJson = (v: unknown): unknown => Array.isArray(v) ? v.map(sortJson) : obj(v) ? Object.fromEntries(Object.keys(v).sort().map(k => [k, sortJson(v[k])])) : v
export const catalogJsonBytes = (v: unknown): Uint8Array => new TextEncoder().encode(`${JSON.stringify(sortJson(v), null, 2)}\n`)
const same = (a: unknown, b: unknown): boolean => JSON.stringify(sortJson(a)) === JSON.stringify(sortJson(b))
const extractPins = (v: unknown, key: string): ReadonlyArray<Pin> => obj(v) && Array.isArray(v[key]) ? v[key].flatMap(x => obj(x) && typeof x["path"] === "string" && typeof x["sha256"] === "string" ? [{ path: x["path"], sha256: x["sha256"] }] : []) : []
const requiredText = (v: unknown, label: string): Effect.Effect<string, KnowledgeCatalogRuntimeError> => typeof v === "string" && v.length > 0 ? Effect.succeed(v) : Effect.fail(new KnowledgeCatalogRuntimeError(`published ${label} is invalid`))
const parse = (bytes: Uint8Array, path: string): Effect.Effect<unknown, KnowledgeCatalogRuntimeError> => { const decoded = decodeCanonicalJsonBytes(bytes); return Either.isLeft(decoded) ? Effect.fail(new KnowledgeCatalogRuntimeError(`${path}: input must be canonical JSON`)) : Effect.succeed(decoded.right) }
const git = (checkout: string, args: ReadonlyArray<string>, maximumOutputBytes = 16 * 1024 * 1024) => Effect.gen(function* () { const subprocess = yield* BoundedSubprocess; const result = yield* subprocess.observe({ argv: ["git", "-C", checkout, ...args], cwd: checkout, environment: { PATH: process.env["PATH"] ?? "/usr/bin:/bin" }, timeoutMs: 20_000, maximumOutputBytes }); if (result.exitCode !== 0 || result.timedOut || result.outputTruncated || result.launchError !== null) return yield* Effect.fail(new KnowledgeCatalogRuntimeError(`fixed Git read unavailable: ${args.join(" ")}`)); return result.stdout }).pipe(Effect.mapError(error => error instanceof KnowledgeCatalogRuntimeError ? error : new KnowledgeCatalogRuntimeError(error.detail)))
export const fixedGitBlob = (checkout: string, path: string, cut: string): Effect.Effect<SourceBytes, KnowledgeCatalogRuntimeError, BoundedSubprocess> => git(checkout, ["show", `${cut}:${path}`]).pipe(Effect.map(bytes => Object.freeze({ path, bytes })))
const readPublished = (checkout: string, path: string) => Effect.gen(function* () { const source = yield* fixedGitBlob(checkout, path, KNOWLEDGE_CATALOG_CURATOR_COMMIT); return yield* parse(source.bytes, path) })
const readPin = (checkout: string, cut: string, pin: Pin) => Effect.gen(function* () { const source = yield* fixedGitBlob(checkout, pin.path, cut); if (sha(source.bytes) !== pin.sha256) return yield* Effect.fail(new KnowledgeCatalogRuntimeError(`pinned hash differs: ${pin.path}`)); return source })
const fixedTree = (checkout: string, cut: string) => git(checkout, ["ls-tree", "-r", "--name-only", cut], 4 * 1024 * 1024).pipe(Effect.map(bytes => new TextDecoder().decode(bytes).split("\n").filter(Boolean).sort((a, b) => a.localeCompare(b))))
const complete = (catalog: Readonly<Record<string, unknown>>, bundle: Readonly<Record<string, unknown>>, index: Either.Either<Uint8Array, { readonly detail: string }>, expectedCatalog: unknown, expectedBundle: unknown, expectedIndex: Uint8Array) => Effect.gen(function* () { if (Either.isLeft(index)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError(index.left.detail)); if (!same(catalog, expectedCatalog) || !same(bundle, expectedBundle) || sha(index.right) !== sha(expectedIndex)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published catalog, bundle, or source index differs from reproduced output")); return Object.freeze({ catalog, bundle, sourceIndex: index.right } satisfies CatalogArtifacts) })

export const compilePublishedKnowledgeMap = (checkout: string): Effect.Effect<CatalogArtifacts, KnowledgeCatalogRuntimeError, BoundedSubprocess> => Effect.gen(function* () {
  const expectedCatalog = yield* readPublished(checkout, MAP.catalog); if (!obj(expectedCatalog)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published map catalog is invalid"))
  const inputPins = extractPins(expectedCatalog, "curation_inputs"), curation = yield* Effect.forEach(inputPins, pin => readPin(checkout, KNOWLEDGE_CATALOG_CURATOR_COMMIT, pin), { concurrency: 1 })
  const raw = curation.filter(x => MAP_RAW.includes(x.path)); if (inputPins.length !== curation.length || raw.length !== 3) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published map curation inputs are incomplete"))
  const values = new Map<string, unknown>(); for (const item of raw) values.set(item.path, yield* parse(item.bytes, item.path))
  const sourceCut = yield* requiredText(expectedCatalog["source_commit"], "map source commit"), declared = declareKnowledgeMapCatalogPaths(values.get("ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_TOPICS_2026-09-13.v1.json"), values.get("ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_COVERAGE_2026-09-13.v1.json"), yield* fixedTree(checkout, sourceCut)); if (Either.isLeft(declared)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError(declared.left.detail))
  const sources = yield* Effect.forEach(declared.right, path => fixedGitBlob(checkout, path, sourceCut), { concurrency: 1 }), expectedSources = extractPins(expectedCatalog, "sources")
  const expectedSourceHashes = new Map(expectedSources.map(pin => [pin.path, pin.sha256] as const))
  if (sources.length !== expectedSources.length || sources.some(x => expectedSourceHashes.get(x.path) !== sha(x.bytes))) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published map fixed-source catalog differs"))
  const result = compileKnowledgeMap({ topics: values.get("ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_TOPICS_2026-09-13.v1.json"), coverage: values.get("ontology/knowledge_map/HSWM_KNOWLEDGE_MAP_COVERAGE_2026-09-13.v1.json"), live: values.get("docs/operations/artifacts/hswm_knowledge_map_2026-09-13/live-resolution.json"), sources, rawCurationFiles: raw, compilerAndQueryPins: curation.filter(x => !MAP_RAW.includes(x.path)) }); if (Either.isLeft(result)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError(result.left.detail))
  const expectedBundle = yield* readPublished(checkout, MAP.bundle), expectedIndex = yield* fixedGitBlob(checkout, MAP.index, KNOWLEDGE_CATALOG_CURATOR_COMMIT)
  return yield* complete(result.right.catalog, result.right.bundle, knowledgeMapSourceIndex(result.right.catalog), expectedCatalog, expectedBundle, expectedIndex.bytes)
})

export const compilePublishedResearchTooling = (checkout: string): Effect.Effect<CatalogArtifacts, KnowledgeCatalogRuntimeError, BoundedSubprocess> => Effect.gen(function* () {
  const expectedCatalog = yield* readPublished(checkout, RESEARCH.catalog); if (!obj(expectedCatalog)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published research catalog is invalid"))
  const inputPins = extractPins(expectedCatalog, "inputs"), curation = yield* Effect.forEach(inputPins, pin => readPin(checkout, KNOWLEDGE_CATALOG_CURATOR_COMMIT, pin), { concurrency: 1 }), raw = curation.filter(x => x.path.startsWith(RESEARCH_PREFIX)); if (inputPins.length !== curation.length || raw.length !== 5) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published research curation inputs are incomplete"))
  const descriptorRows = expectedCatalog["fixed_git_source_descriptors"], descriptorPins = Array.isArray(descriptorRows) ? descriptorRows.flatMap(x => obj(x) && typeof x["source_path"] === "string" && typeof x["sha256"] === "string" ? [{ path: x["source_path"], sha256: x["sha256"] }] : []) : []; if (descriptorPins.length === 0) return yield* Effect.fail(new KnowledgeCatalogRuntimeError("published research fixed-source descriptors are invalid"))
  const sourceCut = yield* requiredText(expectedCatalog["source_commit"], "research source commit")
  const fixedGitSources = yield* Effect.forEach(descriptorPins, pin => readPin(checkout, sourceCut, pin), { concurrency: 1 }), values = new Map<string, unknown>(); for (const item of raw) values.set(item.path, yield* parse(item.bytes, item.path))
  const result = compileResearchTooling({ inventory: values.get(`${RESEARCH_PREFIX}repository-gap-inventory.json`), findings: [values.get(`${RESEARCH_PREFIX}reproducibility-findings.json`), values.get(`${RESEARCH_PREFIX}evaluation-formal-findings.json`), values.get(`${RESEARCH_PREFIX}graph-standards-findings.json`)], integrated: values.get(`${RESEARCH_PREFIX}integrated-assessment.json`), fixedGitSources: fixedGitSources as ReadonlyArray<FixedGitSource>, rawCurationFiles: raw, compilerAndQueryPins: curation.filter(x => !x.path.startsWith(RESEARCH_PREFIX)) }); if (Either.isLeft(result)) return yield* Effect.fail(new KnowledgeCatalogRuntimeError(result.left.detail))
  const expectedBundle = yield* readPublished(checkout, RESEARCH.bundle), expectedIndex = yield* fixedGitBlob(checkout, RESEARCH.index, KNOWLEDGE_CATALOG_CURATOR_COMMIT)
  return yield* complete(result.right.catalog, result.right.bundle, researchToolingSourceIndex(result.right.catalog), expectedCatalog, expectedBundle, expectedIndex.bytes)
})

export const writeCatalogArtifacts = (directory: string, artifacts: CatalogArtifacts): Effect.Effect<void, KnowledgeCatalogRuntimeError, PosixFileSystem> => Effect.gen(function* () { const fs = yield* PosixFileSystem; yield* fs.makeDirectory(directory, { mode: 0o755, operation: "knowledge-catalog-new-output-directory" }).pipe(Effect.mapError(x => new KnowledgeCatalogRuntimeError(x.detail))); for (const [name, bytes] of [["source-catalog.json", catalogJsonBytes(artifacts.catalog)], ["bundle.json", catalogJsonBytes(artifacts.bundle)], ["source-index.md", artifacts.sourceIndex]] as const) yield* fs.writeExclusive(`${directory}/${name}`, bytes, { mode: 0o644, sync: true, operation: "knowledge-catalog-output-artifact" }).pipe(Effect.mapError(x => new KnowledgeCatalogRuntimeError(x.detail))); yield* fs.syncDirectory(directory, "knowledge-catalog-output-sync").pipe(Effect.mapError(x => new KnowledgeCatalogRuntimeError(x.detail))) })
