/** Effect-native bounded research-fabric operations.  These services are projections, never HSWM authority. */
import { Effect, Either } from "effect"
import type { TaskJson } from "./native-task-json-domain.js"
import { NativeResearchFabricError, RESEARCH_FABRIC_CLAIM_BOUNDARY, RESEARCH_FABRIC_PROCESS_V1, RESEARCH_FABRIC_SECRET_V1, RESEARCH_FABRIC_STATUS_V1, classifyFabricState, fabricRefusal, parseFabricRecord, readiness, renderFabricRecord, safeServiceEnvironment } from "./native-research-fabric-domain.js"
import type { FabricProcessIdentity, FabricRecord, FabricServiceSpec } from "./native-research-fabric-domain.js"
import { ResearchFabricRuntime } from "./native-research-fabric-runtime.js"
import { BoundedSubprocess } from "./effect-bounded-subprocess.js"

const recordPath=(root:string,name:string)=>`${root}/run/${name}.json`
const secretPath=(root:string)=>`${root}/secrets/phoenix.json`
const line=(value:unknown)=>JSON.stringify(value,null,2)+"\n"
const fabricError=(detail:string)=>new NativeResearchFabricError({detail})
export const observedVersion=(spec:FabricServiceSpec,executable:string,environment:Readonly<Record<string,string>>):Effect.Effect<string|null,NativeResearchFabricError,BoundedSubprocess>=>Effect.gen(function*(){const subprocess=yield* BoundedSubprocess;const argv=spec.name==="temporal"?[executable,"--version"]:[`${executable.slice(0,executable.lastIndexOf("/"))}/python`,`-c`,`from importlib.metadata import version; print(version('arize-phoenix'))`];const result=yield* subprocess.observe({argv,cwd:process.cwd(),environment:safeServiceEnvironment(environment,{...spec,environment:Object.freeze({})},{}),timeoutMs:10_000,maximumOutputBytes:32*1024}).pipe(Effect.mapError(error=>fabricError(error.detail)));if(result.launchError!==null||result.timedOut||result.outputTruncated||result.exitCode!==0||result.signal!==null)return null;const output=new TextDecoder().decode(result.stdout).trim();return spec.name==="temporal"&&output.startsWith("temporal version ")?output.split(/\s+/)[2]??null:output||null})
const ensure=(path:string):Effect.Effect<void,NativeResearchFabricError,ResearchFabricRuntime>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime;yield* host.ensurePrivateDirectory(path).pipe(Effect.mapError((e)=>fabricError(e.detail)))})
const privateSecrets=(root:string):Effect.Effect<Readonly<Record<string,string>>,NativeResearchFabricError,ResearchFabricRuntime>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime;yield* ensure(`${root}/secrets`);const path=secretPath(root);const existing=yield* host.readPrivateText(path,16*1024).pipe(Effect.mapError((e)=>fabricError(e.detail)));if(existing===null){const left=yield* host.randomHex(32),right=yield* host.randomHex(32);const payload=line({schema:RESEARCH_FABRIC_SECRET_V1,phoenix_secret:`jwt1_${left}`,phoenix_admin_secret:`admin1_${right}`});yield* host.writePrivateExclusive(path,payload).pipe(Effect.mapError((e)=>fabricError(e.detail)));return Object.freeze({PHOENIX_SECRET:`jwt1_${left}`,PHOENIX_ADMIN_SECRET:`admin1_${right}`})}let value:unknown;try{value=JSON.parse(existing)}catch{return yield* Effect.fail(fabricRefusal("invalid Phoenix secret file"))}if(value===null||typeof value!=="object"||Array.isArray(value))return yield* Effect.fail(fabricRefusal("invalid Phoenix secret file"));const object=value as Readonly<Record<string,TaskJson>>;const a=object["phoenix_secret"],b=object["phoenix_admin_secret"];if(object["schema"]!==RESEARCH_FABRIC_SECRET_V1||typeof a!=="string"||typeof b!=="string"||a.length<32||b.length<32||a===b)return yield* Effect.fail(fabricRefusal("invalid Phoenix secret file"));return Object.freeze({PHOENIX_SECRET:a,PHOENIX_ADMIN_SECRET:b})})
interface TrackedFabricProcess { readonly tracking:string; readonly identity:FabricProcessIdentity|null; readonly record:FabricRecord|null }
const tracked=(root:string,spec:FabricServiceSpec):Effect.Effect<TrackedFabricProcess,NativeResearchFabricError,ResearchFabricRuntime>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime;const text=yield* host.readText(recordPath(root,spec.name),64*1024).pipe(Effect.mapError((e)=>fabricError(e.detail)));if(text===null)return {tracking:"untracked",identity:null,record:null};const parsed=parseFabricRecord(text,spec.name);if(Either.isLeft(parsed))return {tracking:"invalid_record",identity:null,record:null};const identity=yield* host.processIdentity(parsed.right.pid);if(identity===null)return {tracking:"stale_record",identity:null,record:parsed.right};if(identity.startTicks!==parsed.right.startTicks)return {tracking:"identity_mismatch",identity,record:parsed.right};const executable=yield* host.executable(spec.executable).pipe(Effect.mapError((e)=>fabricError(e.detail)));if(executable===null)return {tracking:"executable_missing",identity,record:parsed.right};if(executable.sha256!==parsed.right.executable_sha256)return {tracking:"executable_drift",identity,record:parsed.right};const observed=new Set(identity.cmdline.filter((arg)=>arg.startsWith("/")));if(!observed.has(executable.realpath)&&!identity.cmdline.join(" ").includes(spec.name))return {tracking:"identity_mismatch",identity,record:parsed.right};return {tracking:"tracked",identity,record:parsed.right}})
const observedReadiness=(spec:FabricServiceSpec):Effect.Effect<ReturnType<typeof readiness>,NativeResearchFabricError,ResearchFabricRuntime>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime;const tcp=yield* host.tcpReady(spec.readyHost,spec.readyPort);const http=spec.healthUrl===null?null:yield* host.httpReady(spec.healthUrl);return readiness(tcp,http)})
export const researchFabricStatus=(root:string,spec:FabricServiceSpec):Effect.Effect<Readonly<Record<string,TaskJson>>,NativeResearchFabricError,ResearchFabricRuntime>=>Effect.gen(function*(){const current=yield* tracked(root,spec),probe=yield* observedReadiness(spec);return Object.freeze({service:spec.name,state:classifyFabricState(current.tracking,probe),tracking:current.tracking,pid:current.identity?.pid??null,ready_host:spec.readyHost,ready_port:spec.readyPort,health_url:spec.healthUrl,readiness:{...probe},responsibility:spec.responsibility,recorded_pid:current.record?.pid??null})})
const installation=(spec:FabricServiceSpec,environment:Readonly<Record<string,string>>):Effect.Effect<{readonly version:string;readonly sha256:string;readonly path:string},NativeResearchFabricError,ResearchFabricRuntime|BoundedSubprocess>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime;const executable=yield* host.executable(spec.executable).pipe(Effect.mapError((e)=>fabricError(e.detail)));if(executable===null)return yield* Effect.fail(fabricRefusal(`missing executable: ${spec.executable}`));if(spec.expectedExecutableSha256!==null&&executable.sha256!==spec.expectedExecutableSha256)return yield* Effect.fail(fabricRefusal(`${spec.name} executable SHA-256 drift: ${executable.sha256}`));const version=yield* observedVersion(spec,executable.realpath,environment);if(version!==spec.expectedVersion)return yield* Effect.fail(fabricRefusal(`${spec.name} version drift: expected ${spec.expectedVersion}, observed ${String(version)}`));return {version,sha256:executable.sha256,path:executable.realpath}})
export const startResearchFabricService=(root:string,spec:FabricServiceSpec,timeoutMs:number):Effect.Effect<Readonly<Record<string,TaskJson>>,NativeResearchFabricError,ResearchFabricRuntime|BoundedSubprocess>=>Effect.gen(function*(){if(!Number.isFinite(timeoutMs)||timeoutMs<=0)return yield* Effect.fail(fabricRefusal("--timeout must be a positive number of seconds"));const current=yield* researchFabricStatus(root,spec);if(current["state"]==="ready")return current;if(current["state"]==="foreign_or_untracked_listener")return yield* Effect.fail(fabricRefusal(`${spec.name} port is owned by an untracked process; refusing to replace it`));const host=yield* ResearchFabricRuntime;const state=String(current["tracking"]);if(state==="stale_record"||state==="invalid_record")yield* host.unlinkIfPresent(recordPath(root,spec.name)).pipe(Effect.mapError((e)=>fabricError(e.detail)));else if(state!=="untracked")return yield* Effect.fail(fabricRefusal(`${spec.name} has unsafe process state ${state}`));const source=yield* host.environment;const secrets=spec.name==="phoenix"?yield* privateSecrets(root):Object.freeze({});const environment=safeServiceEnvironment(source,spec,secrets);const install=yield* installation(spec,environment);yield* ensure(`${root}/${spec.name}`);yield* ensure(`${root}/logs`);yield* ensure(`${root}/run`);const logPath=`${root}/logs/${spec.name}.log`;const identity=yield* host.launch(spec,environment,logPath).pipe(Effect.mapError((e)=>fabricError(e.detail)));const started=yield* host.nowUnixNs;const record={schema:RESEARCH_FABRIC_PROCESS_V1,claim_boundary:RESEARCH_FABRIC_CLAIM_BOUNDARY,service:spec.name,pid:identity.pid,startTicks:identity.startTicks,cmdline:identity.cmdline,executable:install.path,executable_sha256:install.sha256,version:install.version,public_argv:spec.argv,log_path:logPath,started_unix_ns:started} as const;yield* host.writePrivateExclusive(recordPath(root,spec.name),renderFabricRecord(record)).pipe(Effect.mapError((e)=>fabricError(e.detail)));const deadline=(yield* host.monotonicMs)+timeoutMs;while((yield* host.monotonicMs)<deadline){const result=yield* researchFabricStatus(root,spec);if(result["state"]==="ready")return result;const live=yield* host.processIdentity(identity.pid);if(live===null)return yield* Effect.fail(fabricRefusal(`${spec.name} exited during startup; inspect ${logPath}`));const remaining=deadline-(yield* host.monotonicMs);if(remaining>0)yield* host.sleep(Math.min(250,remaining))}yield* stopResearchFabricService(root,spec,10_000);return yield* Effect.fail(fabricRefusal(`${spec.name} did not become ready within ${timeoutMs}ms`) )})
export const stopResearchFabricService=(root:string,spec:FabricServiceSpec,graceMs:number):Effect.Effect<Readonly<Record<string,TaskJson>>,NativeResearchFabricError,ResearchFabricRuntime>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime,current=yield* tracked(root,spec);if(["untracked","stale_record","invalid_record"].includes(current.tracking)){yield* host.unlinkIfPresent(recordPath(root,spec.name)).pipe(Effect.mapError((e)=>fabricError(e.detail)));return yield* researchFabricStatus(root,spec)}if(current.tracking!=="tracked"||current.identity===null)return yield* Effect.fail(fabricRefusal(`refusing to signal ${spec.name} with unsafe process state ${current.tracking}`));yield* host.signalGroup(current.identity.pid,"SIGTERM").pipe(Effect.mapError((e)=>fabricError(e.detail)));const deadline=(yield* host.monotonicMs)+graceMs;while((yield* host.monotonicMs)<deadline){const live=yield* host.processIdentity(current.identity.pid);if(live===null)break;if(live.startTicks!==current.identity.startTicks)return yield* Effect.fail(fabricRefusal(`refusing to signal ${spec.name}: process identity changed`));const remaining=deadline-(yield* host.monotonicMs);if(remaining>0)yield* host.sleep(Math.min(100,remaining))}const live=yield* host.processIdentity(current.identity.pid);if(live!==null){if(live.startTicks!==current.identity.startTicks)return yield* Effect.fail(fabricRefusal(`refusing to signal ${spec.name}: process identity changed`));yield* host.signalGroup(current.identity.pid,"SIGKILL").pipe(Effect.mapError((e)=>fabricError(e.detail)))}yield* host.unlinkIfPresent(recordPath(root,spec.name)).pipe(Effect.mapError((e)=>fabricError(e.detail)));return yield* researchFabricStatus(root,spec)})
export const researchFabricEnvelope=(root:string,services:ReadonlyArray<Readonly<Record<string,TaskJson>>>)=>Object.freeze({schema:RESEARCH_FABRIC_STATUS_V1,claim_boundary:RESEARCH_FABRIC_CLAIM_BOUNDARY,state_root:root,services})
