import { Effect, Either } from "effect"
import { dirname, basename, join, resolve } from "node:path"
import { PosixFileSystem } from "./effect-posix-filesystem.js"
import { canonicalJsonBytes } from "./canonical-atom-v2-json.js"
import { describeNativeOccurrenceBytes, nativeInTotoStatement, nativeWorkflowOptions, nativeWormCommand, nativeCosignAttestArgv, nativeRfcQueryArgv, nativeRfcVerifyArgv, parseNativeDsse, NativeOccurrenceCliError } from "./native-occurrence-cli-domain.js"
import { nativeHandoffTemplate, validateNativeHandoff } from "./native-occurrence-handoff-domain.js"
import { nativeOsfReadback } from "./native-occurrence-readback-domain.js"
import { observeOccurrencePreflight } from "./native-occurrence-preflight-runtime.js"
const fail=(detail:string)=>new NativeOccurrenceCliError({detail})
const render=(value:unknown):Effect.Effect<string,NativeOccurrenceCliError>=>{const bytes=canonicalJsonBytes(value);return Either.isLeft(bytes)?Effect.fail(fail("output cannot canonicalize")):Effect.succeed(`${new TextDecoder().decode(bytes.right)}\n`)}
const read=(path:string,label:string):Effect.Effect<Uint8Array,NativeOccurrenceCliError,PosixFileSystem>=>Effect.gen(function*(){const fs=yield* PosixFileSystem;const result=yield* fs.readRegularBounded(path,{maximumBytes:16*1024*1024,operation:`read ${label}`}).pipe(Effect.mapError((e)=>fail(`${label}: ${e.detail}`)));return result.bytes})
const toolchain=()=>Effect.gen(function*(){
 const fs=yield* PosixFileSystem
 const source=resolve(import.meta.dirname,"../../../../_research/g0_occurrence/HSWM_G0_OCCURRENCE_TOOLCHAIN_CANDIDATES.v1.json")
 const result=yield* fs.readRegularBounded(source,{maximumBytes:1048576,minimumBytes:1,operation:"fixed toolchain candidates"}).pipe(Effect.either)
 if(Either.isRight(result))return result.right.bytes
 if(result.left.code!=="ENOENT")return yield* Effect.fail(fail(result.left.detail))
 return yield* read(resolve(import.meta.dirname,"../assets/g0-occurrence-toolchain-candidates.v1.json"),"packaged toolchain candidates")
})
const flags=(args:ReadonlyArray<string>):Record<string,string>|null=>{if(args.length%2!==0)return null;const result:Record<string,string>={};for(let n=0;n<args.length;n+=2){const key=args[n],value=args[n+1];if(key===undefined||value===undefined||!key.startsWith("--")||Object.hasOwn(result,key))return null;result[key]=value}return result}
const namedAndPositionals=(args:ReadonlyArray<string>,names:ReadonlyArray<string>):{readonly flags:Record<string,string>;readonly positionals:ReadonlyArray<string>}|null=>{const result:Record<string,string>={},positionals:string[]=[];for(let n=0;n<args.length;n+=1){const value=args[n];if(value===undefined)return null;if(!value.startsWith("--")){positionals.push(value);continue}const next=args[n+1];if(!names.includes(value)||next===undefined||next.startsWith("--")||Object.hasOwn(result,value))return null;result[value]=next;n+=1}return {flags:result,positionals}}
const required=(v:Record<string,string>|null,...names:ReadonlyArray<string>):string[]|null=>v===null||!names.every((n)=>typeof v[n]==="string")?null:names.map((n)=>v[n]!)
const allowed=(v:Record<string,string>|null,names:ReadonlyArray<string>):boolean=>v!==null&&Object.keys(v).every(name=>names.includes(name))
const existing=(path:string,label:string):Effect.Effect<string,NativeOccurrenceCliError,PosixFileSystem>=>Effect.gen(function*(){const fs=yield* PosixFileSystem;const id=yield* fs.identity(path,`inspect ${label}`).pipe(Effect.mapError((e)=>fail(`${label}: ${e.detail}`)));if(id.kind!=="FILE")return yield* Effect.fail(fail(`${label} must be an existing regular file`));return yield* fs.realpath(path,`resolve ${label}`).pipe(Effect.mapError((e)=>fail(`${label}: ${e.detail}`)))} )
const newOutput=(path:string,label:string):Effect.Effect<string,NativeOccurrenceCliError,PosixFileSystem>=>Effect.gen(function*(){const fs=yield* PosixFileSystem;const parent=yield* fs.identity(dirname(path),`inspect ${label} parent`).pipe(Effect.mapError(()=>fail(`${label} parent must already exist`)));if(parent.kind!=="DIRECTORY")return yield* Effect.fail(fail(`${label} parent must already exist`));const realParent=yield* fs.realpath(dirname(path),`resolve ${label} parent`).pipe(Effect.mapError(()=>fail(`${label} parent must already exist`)));const resolved=join(realParent,basename(path));const probe=yield* fs.identity(resolved,`inspect ${label}`).pipe(Effect.either);if(Either.isRight(probe))return yield* Effect.fail(fail(`${label} output must not already exist`));if(probe.left.code!=="ENOENT")return yield* Effect.fail(fail(`${label}: ${probe.left.detail}`));return resolved})
export const runNativeOccurrenceCli=(argv:ReadonlyArray<string>)=>Effect.gen(function*(){
 const [command,...args]=argv
 if(command==="--help"||command==="-h")return "usage: hswm-g0-occurrence <preflight|describe|workflow-options|statement|parse-dsse|osf-readback|worm-command|cosign-attest-command|rfc3161-query-command|rfc3161-verify-command|external-handoff-template|external-handoff-validate>\n"
 if(command==="preflight"&&args.length===0){const report=yield* observeOccurrencePreflight(),output=yield* render(report);return report["status"]==="READY_FOR_EXTERNAL_QUALIFICATION_NOT_LIVE_EXECUTION"?output:{stdout:output,exitCode:3}}
 if(command==="describe"){const parsed=namedAndPositionals(args,["--media-type"]);if(parsed===null||parsed.positionals.length!==1||parsed.flags["--media-type"]===undefined)return yield* Effect.fail(fail("describe flags invalid"));const value=yield* read(parsed.positionals[0]!,"subject").pipe(Effect.flatMap((b)=>{const r=describeNativeOccurrenceBytes(b,parsed.flags["--media-type"]!);return Either.isLeft(r)?Effect.fail(r.left):Effect.succeed(r.right)}));return yield* render(value)}
 if(command==="workflow-options"&&args.length===1){const r=nativeWorkflowOptions(args[0]!);if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render(r.right)}
 if(command==="external-handoff-template"&&args.length===1){const r=nativeHandoffTemplate(args[0]!,yield* toolchain());if(Either.isLeft(r))return yield* Effect.fail(r.left);return new TextDecoder().decode(r.right)}
 if(command==="external-handoff-validate"&&args.length===1){const r=validateNativeHandoff(yield* read(args[0]!,"handoff"),yield* toolchain());if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render(r.right)}
 if(command==="statement"){const names=["--subject","--subject-name","--media-type","--predicate-type","--predicate"],f=flags(args),v=required(f,...names);if(v===null||!allowed(f,names))return yield* Effect.fail(fail("statement flags invalid"));const [subject,subjectName,mediaType,predicateType,predicate]=v;const r=nativeInTotoStatement(yield* read(subject!,"subject"),subjectName!,mediaType!,predicateType!,yield* read(predicate!,"predicate"));if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render(r.right)}
 if(command==="parse-dsse"&&args.length===1){const value=yield* read(args[0]!,"DSSE envelope").pipe(Effect.flatMap((b)=>{const r=parseNativeDsse(b);return Either.isLeft(r)?Effect.fail(r.left):Effect.succeed(r.right)}));return yield* render(value)}
 if(command==="osf-readback"){const f=flags(args),names=["--registration","--file-metadata","--expected-package","--read-back-package","--read-back-download-url","--registered-path","--pulse-timestamp"],v=required(f,...names);if(v===null||!allowed(f,names))return yield* Effect.fail(fail("osf-readback flags invalid"));const [registration,file,expected,readback,url,path,pulse]=v;const r=nativeOsfReadback(yield* read(registration!,"OSF registration readback"),yield* read(file!,"OSF file readback"),yield* read(expected!,"registration package"),yield* read(readback!,"read-back package"),path!,url!,pulse!);if(Either.isLeft(r))return yield* Effect.fail(r.left);const output=yield* render(r.right);return r.right["status"]==="CANDIDATE_FOR_EXTERNAL_AUDIT"?output:{stdout:output,exitCode:4}}
 if(command==="worm-command"){const f=flags(args),names=["--bucket","--occurrence-uid","--body","--retain-until","--claimant-account-id","--admin-account-id","--aws-cli"],v=required(f,...names.slice(0,6));if(v===null||!allowed(f,names))return yield* Effect.fail(fail("worm-command flags invalid"));const [bucket,uid,body,retain,claimant,admin]=v as [string,string,string,string,string,string],path=yield* existing(body,"WORM claim body"),r=nativeWormCommand(yield* read(path,"WORM claim body"),path,bucket,uid,retain,claimant,admin,f!["--aws-cli"]??"aws");if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render(r.right)}
 if(command==="cosign-attest-command"){const f=flags(args),names=["--blob","--statement","--bundle","--cosign"],v=required(f,...names.slice(0,3));if(v===null||!allowed(f,names))return yield* Effect.fail(fail("cosign-attest-command flags invalid"));const [blob,statement,bundle]=v as [string,string,string],r=nativeCosignAttestArgv(f!["--cosign"]??"cosign",yield* existing(blob,"blob"),yield* existing(statement,"statement"),yield* newOutput(bundle,"bundle"));if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render({argv:r.right,claim_boundary:"local deterministic preparation and inspection only; not external registration, signature verification, execution, publication, outcome truth, Permit, causal credit, canonical admission, learning, or G0 evidence",execution:"NOT_EXECUTED",schema_version:"hswm-g0-occurrence-local-cli/v1"})}
 if(command==="rfc3161-query-command"){const f=flags(args),names=["--blob","--request","--openssl"],v=required(f,...names.slice(0,2));if(v===null||!allowed(f,names))return yield* Effect.fail(fail("rfc3161-query-command flags invalid"));const [blob,request]=v as [string,string],r=nativeRfcQueryArgv(f!["--openssl"]??"openssl",yield* existing(blob,"blob"),yield* newOutput(request,"RFC3161 request"));if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render({argv:r.right,claim_boundary:"local deterministic preparation and inspection only; not external registration, signature verification, execution, publication, outcome truth, Permit, causal credit, canonical admission, learning, or G0 evidence",execution:"NOT_EXECUTED",schema_version:"hswm-g0-occurrence-local-cli/v1"})}
 if(command==="rfc3161-verify-command"){const f=flags(args),names=["--request","--response","--ca-file","--untrusted","--openssl"],v=required(f,...names.slice(0,3));if(v===null||!allowed(f,names))return yield* Effect.fail(fail("rfc3161-verify-command flags invalid"));const [request,response,ca]=v as [string,string,string],untrusted=f!["--untrusted"],r=nativeRfcVerifyArgv(f!["--openssl"]??"openssl",yield* existing(request,"RFC3161 request"),yield* existing(response,"response"),yield* existing(ca,"CA file"),untrusted===undefined?null:yield* existing(untrusted,"untrusted chain"));if(Either.isLeft(r))return yield* Effect.fail(r.left);return yield* render({argv:r.right,claim_boundary:"local deterministic preparation and inspection only; not external registration, signature verification, execution, publication, outcome truth, Permit, causal credit, canonical admission, learning, or G0 evidence",execution:"NOT_EXECUTED",schema_version:"hswm-g0-occurrence-local-cli/v1"})}
 return yield* Effect.fail(fail("usage: hswm-g0-occurrence <describe|workflow-options|statement|parse-dsse>"))
})
