/** Pure, presence-only classification for occurrence preflight observations. */
export const REQUIRED_BINDINGS=["HSWM_G0_OSF_REGISTRATION_BINDING","HSWM_G0_WORM_ENDPOINT","HSWM_G0_WORM_POLICY_AUDIT_BINDING","HSWM_G0_SIGSTORE_REKOR_ENDPOINT","HSWM_G0_RFC3161_TSA_ENDPOINT","HSWM_G0_PRODUCTION_TEMPORAL_ENDPOINT","HSWM_G0_TEMPORAL_SIGNAL_AUTHORIZATION_BINDING","HSWM_G0_TOOLCHAIN_QUALIFICATION_BINDING","HSWM_G0_COMPLETION_AUDIT_QUALIFICATION_BINDING","HSWM_G0_DRAND_VERIFIER_BINDING","HSWM_G0_CUSTODIAN_ENDPOINT","HSWM_G0_EVALUATOR_A_ENDPOINT","HSWM_G0_EVALUATOR_B_ENDPOINT"] as const
export const ROLE_BINDINGS=[["actor","HSWM_G0_ACTOR_ROLE_ID"],["revision_proposer","HSWM_G0_REVISION_PROPOSER_ROLE_ID"],["occurrence_claimant","HSWM_G0_OCCURRENCE_CLAIMANT_ROLE_ID"],["worm_administrator","HSWM_G0_WORM_ADMINISTRATOR_ROLE_ID"],["custodian","HSWM_G0_CUSTODIAN_ROLE_ID"],["drand_verifier","HSWM_G0_DRAND_VERIFIER_ROLE_ID"],["evaluator_a","HSWM_G0_EVALUATOR_A_ROLE_ID"],["evaluator_b","HSWM_G0_EVALUATOR_B_ROLE_ID"],["external_auditor","HSWM_G0_EXTERNAL_AUDITOR_ROLE_ID"]] as const
export const PREFLIGHT_BINARIES=[{name:"cosign",candidateVersion:"3.1.3",arguments:["version"]},{name:"temporal",candidateVersion:"1.8.3",arguments:["version"]},{name:"aws",candidateVersion:"2.36.36",arguments:["--version"]},{name:"openssl",candidateVersion:"3.5.6",arguments:["version"]}] as const
export interface PreflightBinaryObservation { readonly name:string; readonly candidateVersion:string; readonly present:boolean; readonly versionOutput:string|null }
export interface PreflightInputs { readonly environment: Readonly<Record<string,string>>; readonly binaries:ReadonlyArray<PreflightBinaryObservation> }
const present=(environment:Readonly<Record<string,string>>,name:string):boolean=>(environment[name]?.trim().length??0)>0
const version=(output:string|null,candidate:string):boolean=>output!==null&&new RegExp(`(^|[^0-9.])${candidate.replaceAll(".","\\.")}([^0-9.]|$)`).test(output)
export const classifyOccurrencePreflight=(input:PreflightInputs):Readonly<Record<string,unknown>>=>{
 const bindings=[...REQUIRED_BINDINGS,...ROLE_BINDINGS.map((x)=>x[1])].map(name=>Object.freeze({name,present:present(input.environment,name)}));const identities=ROLE_BINDINGS.map(([role,name])=>[role,input.environment[name]?.trim()??""] as const)
 const same=identities.flatMap(([role,value],index)=>value?identities.slice(index+1).filter(([,other])=>other===value).map(([other])=>`${role}=${other}`):[]),missing=bindings.filter(item=>!item.present).map(item=>item.name),external=missing.length===0&&same.length===0
 // The runtime observes each fixed candidate once.  Do not let a malformed
 // adapter input turn an empty (or duplicated) observation list into READY.
 const binaries=PREFLIGHT_BINARIES.map(expected=>{const matches=input.binaries.filter(item=>item.name===expected.name&&item.candidateVersion===expected.candidateVersion);const item=matches.length===1?matches[0]:undefined;return Object.freeze({name:expected.name,candidate_version:expected.candidateVersion,present:item?.present===true,candidate_version_observed:item?.present===true&&version(item.versionOutput,expected.candidateVersion),artifact_integrity_verified:false})});const local=input.binaries.length===PREFLIGHT_BINARIES.length&&binaries.every(item=>item.present&&item.candidate_version_observed),status=!external?"BLOCKED_EXTERNAL":!local?"BLOCKED_LOCAL_ENGINEERING":"READY_FOR_EXTERNAL_QUALIFICATION_NOT_LIVE_EXECUTION"
 return Object.freeze({schema_version:"hswm-g0-occurrence-live-preflight/v1",status,claim_boundary:"presence-only qualification-input check; version strings are not artifact qualification and declared role identifiers are not an external independence proof; not registration, artifact integrity verification, live execution readiness or authorization, outcome truth, Permit, causal credit, canonical admission, learning, or efficacy evidence",local_engineering_ready:local,artifact_qualification_proven:false,live_execution_ready:false,external_bindings_declared:external,external_independence_proven:false,bindings,binaries,declared_role_identities_distinct:same.length===0&&ROLE_BINDINGS.every(([,name])=>present(input.environment,name)),missing_external_bindings:missing,same_role_identities:same})
}
