/** Pure derived projection compiler. It never mutates source Markdown bytes. */
import { Data, Either } from "effect"
export class NativeMarkdownMathError extends Data.TaggedError("NativeMarkdownMathError")<{ readonly detail: string }> {}
export interface MarkdownMathProjection { readonly text: string; readonly operatorname_rewrites: number; readonly legacy_compatibility_rewrites: number; readonly display_fence_rewrites: number; readonly math_fences_seen: number }
const fail=<A=never>(detail:string):Either.Either<A,NativeMarkdownMathError>=>Either.left(new NativeMarkdownMathError({detail}))
const operator=/\\operatorname(?:\*)?\s*\{([A-Za-z][A-Za-z0-9]*)\}/g
const literal:ReadonlyArray<readonly[string,string]>=[["\\centernot\\Rightarrow","\\not\\Rightarrow"],["\\mathcal K={S:","\\mathcal K=\\{S:"],["p_j = 2^(-m_j) sum_{k=w_j}^{m_j} choose(m_j,k),","p_j = 2^{-m_j} \\sum_{k=w_j}^{m_j} \\binom{m_j}{k},"],["p_j_adjusted = min(1, 3 p_j).","p_{j,\\mathrm{adjusted}} = \\min(1, 3p_j)."]]
const ending=(line:string)=>line.endsWith("\r\n")?"\r\n":line.endsWith("\n")?"\n":""
const rewrite=(part:string,line:number):Either.Either<readonly[string,number,number],NativeMarkdownMathError>=>{let count=0;let out=part.replace(operator,(_,name:string)=>{count++;return `\\mathrm{${name}}`});let legacy=0;for(const [from,to] of literal){const n=out.split(from).length-1;if(n){out=out.split(from).join(to);legacy+=n}}return out.includes("\\operatorname")?fail(`line ${line}: unsupported or malformed \\operatorname expression`):Either.right([out,count,legacy])}
const outside=(line:string,n:number):Either.Either<readonly[string,number,number],NativeMarkdownMathError>=>{const parts=line.split(/(`+)/);let ticks:number|undefined, count=0,legacy=0;for(let i=0;i<parts.length;i++){const part=parts[i]!;if(part.length>0&&/^`+$/.test(part)){if(ticks===undefined)ticks=part.length;else if(ticks===part.length)ticks=undefined;continue}if(ticks===undefined){const r=rewrite(part,n);if(Either.isLeft(r))return Either.left(r.left);parts[i]=r.right[0];count+=r.right[1];legacy+=r.right[2]}}return Either.right([parts.join(""),count,legacy])}
export const compilePortableMarkdownMath=(text:string):Either.Either<MarkdownMathProjection,NativeMarkdownMathError>=>{const out:string[]=[];let marker:string|undefined, math=false, display=false, operators=0,legacy=0,displayRewrites=0,mathFences=0;const lines=text.match(/.*(?:\r\n|\n|$)/g)?.filter(x=>x!=="")??[];for(let i=0;i<lines.length;i++){const line=lines[i]!,lineNo=i+1;if(marker!==undefined){const stripped=line.trim();if(stripped.length>=marker.length&&new Set(stripped).size===1&&stripped[0]===marker[0]){out.push(line);marker=undefined;math=false;continue}if(math){const r=rewrite(line,lineNo);if(Either.isLeft(r))return Either.left(r.left);out.push(r.right[0]);operators+=r.right[1];legacy+=r.right[2]}else out.push(line);continue}const fence=/^([ \t]*)(`{3,}|~{3,})(.*)$/.exec(line.replace(/\r?\n$/,""));if(fence){marker=fence[2]!;const info=fence[3]!.trim().split(/\s+/,1)[0]?.toLowerCase();math=info==="math"||info==="latex"||info==="tex";if(math)mathFences++;out.push(line);continue}const stripped=line.trim();if(stripped==="\\["){if(display)return fail(`line ${lineNo}: nested \\[ display delimiter`);out.push(`${line.slice(0,line.length-line.trimStart().length)}\`\`\`math${ending(line)}`);display=true;displayRewrites++;mathFences++;continue}if(stripped==="\\]"){if(!display)return fail(`line ${lineNo}: unmatched \\] display delimiter`);out.push(`${line.slice(0,line.length-line.trimStart().length)}\`\`\`${ending(line)}`);display=false;continue}const r=display?rewrite(line,lineNo):outside(line,lineNo);if(Either.isLeft(r))return Either.left(r.left);out.push(r.right[0]);operators+=r.right[1];legacy+=r.right[2]}if(display)return fail("unclosed \\[ display delimiter");if(marker!==undefined&&math)return fail("unclosed fenced math block");return Either.right(Object.freeze({text:out.join(""),operatorname_rewrites:operators,legacy_compatibility_rewrites:legacy,display_fence_rewrites:displayRewrites,math_fences_seen:mathFences}))}
