import { access, constants } from "node:fs/promises"
import { Context, Effect, Layer } from "effect"
import { BoundedSubprocess } from "./effect-bounded-subprocess.js"
import { PREFLIGHT_BINARIES, classifyOccurrencePreflight, type PreflightBinaryObservation } from "./native-occurrence-preflight-domain.js"
import { NativeOccurrenceCliError } from "./native-occurrence-cli-domain.js"
export interface OccurrenceEnvironment { readonly values:Readonly<Record<string,string>>; readonly path:string; readonly cwd:string }
export interface OccurrenceEnvironmentShape { readonly snapshot:Effect.Effect<OccurrenceEnvironment> }
export class OccurrenceEnvironmentService extends Context.Tag("hswm/OccurrenceEnvironment")<OccurrenceEnvironmentService,OccurrenceEnvironmentShape>() {}
export interface ExecutableLocatorShape { readonly locate:(name:string,environment:OccurrenceEnvironment)=>Effect.Effect<string|null> }
export class ExecutableLocator extends Context.Tag("hswm/OccurrenceExecutableLocator")<ExecutableLocator,ExecutableLocatorShape>() {}
const nodeEnvironment:OccurrenceEnvironmentShape={snapshot:Effect.sync(()=>{const values:Record<string,string>={};for(const [name,value] of Object.entries(process.env))if(typeof value==="string")values[name]=value;return Object.freeze({values:Object.freeze(values),path:values["PATH"]??"",cwd:process.cwd()})})}
const nodeLocator:ExecutableLocatorShape={locate:(name,environment)=>{const candidates=environment.path.split(":").filter(part=>part.length>0).map(part=>`${part}/${name}`);const find=(index:number):Effect.Effect<string|null>=>{const candidate=candidates[index];return candidate===undefined?Effect.succeed(null):Effect.tryPromise({try:()=>access(candidate,constants.X_OK),catch:()=>"ACCESS_FAILED" as const}).pipe(Effect.map(()=>candidate),Effect.catchAll(()=>find(index+1)))};return find(0)}}
export const NodeOccurrencePreflightLive:Layer.Layer<OccurrenceEnvironmentService|ExecutableLocator>=Layer.merge(Layer.succeed(OccurrenceEnvironmentService,Object.freeze(nodeEnvironment)),Layer.succeed(ExecutableLocator,Object.freeze(nodeLocator)))
const observed=(output:Uint8Array):string=>new TextDecoder().decode(output)
export const observeOccurrencePreflight=():Effect.Effect<Readonly<Record<string,unknown>>,NativeOccurrenceCliError,OccurrenceEnvironmentService|ExecutableLocator|BoundedSubprocess>=>Effect.gen(function*(){const environment=yield* OccurrenceEnvironmentService;const locator=yield* ExecutableLocator;const subprocess=yield* BoundedSubprocess;const source=yield* environment.snapshot;const binaries:PreflightBinaryObservation[]=[];for(const item of PREFLIGHT_BINARIES){const executable=yield* locator.locate(item.name,source);if(executable===null){binaries.push({name:item.name,candidateVersion:item.candidateVersion,present:false,versionOutput:null});continue}const result=yield* subprocess.observe({argv:[executable,...item.arguments],cwd:source.cwd,environment:{PATH:source.path},timeoutMs:10_000,maximumOutputBytes:32*1024}).pipe(Effect.mapError(()=>new NativeOccurrenceCliError({detail:"preflight subprocess observation failed"})));binaries.push({name:item.name,candidateVersion:item.candidateVersion,present:true,versionOutput:result.exitCode===0&&!result.timedOut&&!result.outputTruncated?`${observed(result.stdout)}${observed(result.stderr)}`:null})}return classifyOccurrencePreflight({environment:source.values,binaries})})
