/** Effect-only loader that freezes source bytes before pure projection validation. */
import { Data, Effect } from "effect"
import { BoundedSubprocess, PosixFileSystem } from "./effect-posix-services.js"
import type { HistoricalBlobSource } from "./native-development-projection-domain.js"
export class NativeDevelopmentProjectionIoError extends Data.TaggedError("NativeDevelopmentProjectionIoError")<{ readonly detail: string }> {}
export interface DevelopmentProjectionSourceRequest { readonly currentPaths: readonly string[]; readonly historical: readonly { readonly commit: string; readonly path: string }[] }
const error=(detail:string)=>new NativeDevelopmentProjectionIoError({detail})
/** Returned callbacks are immutable Map lookups; the pure domain cannot trigger I/O. */
export const preloadDevelopmentProjectionSources=(root:string,request:DevelopmentProjectionSourceRequest):Effect.Effect<HistoricalBlobSource,NativeDevelopmentProjectionIoError,PosixFileSystem|BoundedSubprocess>=>Effect.gen(function*(){const fs=yield* PosixFileSystem,subprocess=yield* BoundedSubprocess,current=new Map<string,Uint8Array>(),historical=new Map<string,Uint8Array>();for(const path of request.currentPaths){const item=yield* fs.readRegularBounded(`${root}/${path}`,{maximumBytes:16*1024*1024,minimumBytes:1,operation:"preload development projection source"}).pipe(Effect.mapError(e=>error(e.detail)));current.set(path,item.bytes)}for(const item of request.historical){const result=yield* subprocess.observe({argv:["git","-C",root,"show",`${item.commit}:${item.path}`],cwd:root,environment:{},timeoutMs:30_000,maximumOutputBytes:16*1024*1024}).pipe(Effect.mapError(e=>error(e.detail)));if(result.launchError!==null||result.timedOut||result.outputTruncated||result.exitCode!==0||result.signal!==null)return yield* Effect.fail(error(`cannot read historical source: ${item.path}`));historical.set(`${item.commit}\u0000${item.path}`,result.stdout)}return Object.freeze({readPath:(path:string)=>current.get(path),readBlob:(commit:string,path:string)=>historical.get(`${commit}\u0000${path}`)})})
