/** Pure fail-closed validator for the graph-standard acceptance lock. */
import { createHash } from "node:crypto"
import { Data, Either } from "effect"
import { renderNativeTaskJson, taskJsonRecord, type TaskJson } from "./native-task-json-domain.js"

export const GRAPH_STANDARDS_LOCK_SCHEMA="hswm-graph-standards-acceptance/v1" as const
export const GRAPH_STANDARDS_RECEIPT_SCHEMA="hswm-graph-standard-qualification-receipt/v1" as const
export class NativeGraphStandardsError extends Data.TaggedError("NativeGraphStandardsError")<{readonly detail:string}>{}
export type GraphStandardsInventory=Readonly<Record<string,Uint8Array>>
type Row=Readonly<Record<string,TaskJson>>
const fail=<A=never>(detail:string):Either.Either<A,NativeGraphStandardsError>=>Either.left(new NativeGraphStandardsError({detail}))
const req=(ok:boolean,detail:string):Either.Either<void,NativeGraphStandardsError>=>ok?Either.right(undefined):fail(detail)
const row=(v:TaskJson|undefined,label:string):Either.Either<Row,NativeGraphStandardsError>=>taskJsonRecord(v as TaskJson)?Either.right(v as Row):fail(`${label} must be an object`)
const list=(v:TaskJson|undefined,label:string):Either.Either<readonly TaskJson[],NativeGraphStandardsError>=>Array.isArray(v)?Either.right(v):fail(`${label} must be an array`)
const str=(v:TaskJson|undefined,label:string):Either.Either<string,NativeGraphStandardsError>=>typeof v==="string"&&v.length>0?Either.right(v):fail(`${label} must be a non-empty string`)
const digest=(v:TaskJson|undefined,label:string):Either.Either<string,NativeGraphStandardsError>=>Either.gen(function*(){const x=yield* str(v,label);return yield* /^[0-9a-f]{64}$/.test(x)?Either.right(x):fail(`${label} must be a lowercase SHA-256`)})
const commit=(v:TaskJson|undefined,label:string):Either.Either<string,NativeGraphStandardsError>=>Either.gen(function*(){const x=yield* str(v,label);return yield* /^[0-9a-f]{40}$/.test(x)?Either.right(x):fail(`${label} must be a 40-character git id`)})
const rel=(v:TaskJson|undefined,label:string):Either.Either<string,NativeGraphStandardsError>=>Either.gen(function*(){const x=yield* str(v,label);return yield* (!x.startsWith("/")&&!x.split("/").includes(".."))?Either.right(x):fail(`${label} must stay repository-relative`)})
const https=(v:TaskJson|undefined,label:string,git=false):Either.Either<string,NativeGraphStandardsError>=>Either.gen(function*(){const x=yield* str(v,label);return yield* (x.startsWith("https://")&&!x.slice(8).split("/")[0]!.includes("@")&&(!git||x.endsWith(".git")))?Either.right(x):fail(`${label} must be credential-free HTTPS`)})
const sha=(bytes:Uint8Array|string)=>createHash("sha256").update(bytes).digest("hex")
const parse=(bytes:Uint8Array,label:string):Either.Either<TaskJson,NativeGraphStandardsError>=>{try{return Either.right(JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(bytes)) as TaskJson)}catch{return fail(`${label} is unavailable`)}}
const index=(v:TaskJson|undefined,label:string):Either.Either<Readonly<Record<string,Row>>,NativeGraphStandardsError>=>Either.gen(function*(){const xs=yield* list(v,label),out:Record<string,Row>={};for(let i=0;i<xs.length;i++){const r=yield* row(xs[i],`${label}[${i}]`),id=yield* str(r["id"],`${label}[${i}].id`);if(out[id]!==undefined)return yield* fail(`duplicate ${label} id: ${id}`);out[id]=r}return Object.freeze(out)})
const file=(i:GraphStandardsInventory,path:string,label:string):Either.Either<Uint8Array,NativeGraphStandardsError>=>path.startsWith("/")||path.split("/").includes("..")?fail(`${label} escapes or is unavailable`):i[path]===undefined?fail(`${label} escapes or is unavailable`):Either.right(i[path]!)
const canonical=(v:TaskJson)=>renderNativeTaskJson(v)
const receiptAdapter=(a:Row):TaskJson=>a["ecosystem"]==="npm"?{authority_class:a["authority_class"]!,ecosystem:a["ecosystem"]!,package:a["package"]!,source_commit:a["source_commit"]!,version:a["version"]!,npm_integrity:a["npm_integrity"]!}:{authority_class:a["authority_class"]!,ecosystem:a["ecosystem"]!,package:a["package"]!,source_commit:a["source_commit"]!,version:a["version"]!,sdist_sha256:a["sdist_sha256"]!,wheel_sha256:a["wheel_sha256"]!}
const runtimeReceipt=(lock:Row,profile:Row):Either.Either<TaskJson,NativeGraphStandardsError>=>Either.gen(function*(){if((profile["runner_runtime"]??"node")==="node"){const r=yield* row(lock["runtime_lock"],"runtime_lock");return{installation:"CLEAN_TEMPORARY_NPM_CI_IGNORE_SCRIPTS",kind:"node-npm",node:`v${r["node"]}`,npm:r["npm"]!,package_lock_sha256:r["package_lock_sha256"]!}}const r=yield* row(lock["python_runtime_lock"],"python_runtime_lock");return{installation:"CLEAN_ISOLATED_UV_RUN_LOCKED",kind:"python-uv",python:r["python"]!,uv:r["uv"]!,extra:r["extra"]!,project_manifest_sha256:r["project_manifest_sha256"]!,uv_lock_sha256:r["uv_lock_sha256"]!}})
const same=(a:TaskJson|undefined,b:TaskJson|undefined):boolean=>canonical(a??null)===canonical(b??null)
export const verifyNativeGraphStandardsLock=(lock:TaskJson,inventory:GraphStandardsInventory,verifyReceipts=true):Either.Either<{readonly adapters:Readonly<Record<string,Row>>;readonly profiles:Readonly<Record<string,Row>>;readonly sources:Readonly<Record<string,Row>>;readonly standards:Readonly<Record<string,Row>>},NativeGraphStandardsError>=>Either.gen(function*(){
 const l=yield* row(lock,"graph standards lock");yield* req(l["schema_version"]===GRAPH_STANDARDS_LOCK_SCHEMA,"graph standards lock schema drift");const policy=yield* row(l["policy"],"policy");for(const [k,v] of Object.entries({official_standard_sdk_suite_first:true,openai_system_or_curated_skill_first:true,exact_version_commit_digest_and_lock_required:true,mcp_role:"LIVE_DATA_ACTION_AUTH_BOUNDARY",skill_role:"REUSABLE_WORKFLOW_INSTRUCTIONS_RESOURCES",hswm_adapter_rule:"ONLY_WHERE_NO_SUITABLE_STANDARD_SURFACE_AND_THEN_THIN_BOUNDED_AND_CLAIM_LIMITED",mcp_registry_role:"DISCOVERY_ONLY_NO_AUTO_TRUST_NO_AUTO_INSTALL"}))yield* req(policy[k]===v,"standard-first policy is not fail-closed");
 const lanes=yield* row(l["lanes"],"lanes");yield* req(Object.keys(lanes).sort().join(",")==="experimental,metadata_only,stable","standards lanes must be explicit and closed");const standards=yield* index(l["standards"],"standards");for(const [id,s] of Object.entries(standards)){const lane=yield* str(s["lane"],`standard ${id} lane`);yield* req(lanes[lane]!==undefined,`standard ${id} has an unknown lane`);yield* https(s["official_url"],`standard ${id} URL`);yield* req(s["status"]!=="DRAFT_STANDARD"||lane==="experimental",`draft standard ${id} escaped experimental lane`)}
 const sources=yield* index(l["suite_sources"],"suite_sources");for(const [id,s] of Object.entries(sources)){yield* req(s["authority"]==="W3C",`suite ${id} is not an official W3C source`);yield* https(s["repository"],`source ${id} repository`,true);yield* commit(s["commit"],`source ${id} commit`);yield* rel(s["selected_path"],`source ${id} selected path`);yield* commit(s["git_tree_sha1"],`source ${id} tree`);yield* digest(s["git_archive_sha256"],`source ${id} archive`);for(const x of ["manifest","license"] as const){const p=yield* rel(s[`${x}_path`],`source ${id} ${x} path`);yield* digest(s[`${x}_sha256`],`source ${id} ${x}`);yield* req(p.length>0,`source ${id} ${x} path drift`)}}
 const adapters=yield* index(l["tool_adapters"],"tool_adapters");for(const [id,a] of Object.entries(adapters)){yield* req((yield* str(a["authority_class"],`adapter ${id} authority`)).endsWith("NOT_W3C"),`adapter ${id} hides its non-W3C authority`);const pkg=yield* str(a["package"],`adapter ${id} package`),version=yield* str(a["version"],`adapter ${id} version`),eco=yield* str(a["ecosystem"],`adapter ${id} ecosystem`);yield* req(eco==="npm"||eco==="pypi",`adapter ${id} has an unknown ecosystem`);yield* https(a["source_repository"],`adapter ${id} source`,true);yield* commit(a["source_commit"],`adapter ${id} source commit`);const lockPath=yield* rel(a["lockfile"],`adapter ${id} lockfile`),bytes=yield* file(inventory,lockPath,`adapter ${id} lockfile`);if(eco==="npm"){const integrity=yield* str(a["npm_integrity"],`adapter ${id} integrity`);yield* req(integrity.startsWith("sha512-"),`adapter ${id} lacks npm SHA-512 integrity`);const pl=yield* row(yield* parse(bytes,`adapter ${id} package lock`),`adapter ${id} package lock`),packages=yield* row(pl["packages"],"npm packages"),entry=yield* row(packages[`node_modules/${pkg}`],`adapter ${id} package entry`);yield* req(pl["lockfileVersion"]===3,"npm package lock format drift");for(const [p,v] of Object.entries(packages)){if(p!==""){const q=yield* row(v,`npm package ${p}`);yield* req(q["link"]!==true&&typeof q["resolved"]==="string"&&q["resolved"].startsWith("https://registry.npmjs.org/")&&typeof q["integrity"]==="string"&&q["integrity"].startsWith("sha512-"),`npm package lock contains an unbound dependency: ${p}`)}}yield* req(entry["version"]===version&&entry["integrity"]===integrity,`adapter ${id} package lock drift`);yield* req(entry["license"]===a["license"],`adapter ${id} license drift`)}else{const py=yield* row(l["python_runtime_lock"],"python_runtime_lock");yield* req(a["project_manifest"]===py["project_manifest"]&&a["lockfile"]===py["uv_lock"]&&a["project_extra"]===py["extra"],`adapter ${id} escapes the Python runtime lock`);yield* digest(a["sdist_sha256"],`adapter ${id} sdist`);yield* digest(a["wheel_sha256"],`adapter ${id} wheel`);yield* file(inventory,yield* rel(a["project_manifest"],`adapter ${id} project manifest`),`adapter ${id} project manifest`);yield* req(new TextDecoder().decode(bytes).includes(`name = "${pkg}"`)&&new TextDecoder().decode(bytes).includes(`version = "${version}"`),`adapter ${id} Python package lock drift`)}}
 const runtime=yield* row(l["runtime_lock"],"runtime_lock");for(const [field,label] of [["package_manifest","runtime package manifest"],["package_lock","runtime package lock"]] as const){const p=yield* rel(runtime[field],label),b=yield* file(inventory,p,label);yield* req(sha(b)===String(runtime[`${field}_sha256`]),`${label} digest drift`)}const manifest=yield* row(yield* parse(yield* file(inventory,yield* rel(runtime["package_manifest"],"runtime package manifest"),"runtime package manifest"),"runtime package manifest"),"runtime package manifest");yield* req(row(manifest["engines"],"runtime engines").pipe(Either.match({onLeft:()=>false,onRight:e=>e["node"]===runtime["node"]}))&&manifest["packageManager"]===`npm@${runtime["npm"]}`,"Node runtime lock drift");
 const py=yield* row(l["python_runtime_lock"],"python_runtime_lock");for(const field of ["project_manifest","uv_lock"] as const){const p=yield* rel(py[field],`Python runtime ${field}`),b=yield* file(inventory,p,`Python runtime ${field}`);yield* req(sha(b)===String(py[`${field}_sha256`]),`Python runtime ${field} digest drift`)}
 const profiles=yield* index(l["qualification_profiles"],"qualification_profiles"),runnable:string[]=[];for(const [id,p] of Object.entries(profiles)){const lane=yield* str(p["lane"],`profile ${id} lane`),ids=yield* list(p["standard_ids"],`profile ${id} standards`);yield* req(lanes[lane]!==undefined&&ids.length>0&&ids.every(x=>typeof x==="string"&&standards[x]!==undefined),`profile ${id} references an unknown standard`);yield* req(lane!=="stable"||!ids.some(x=>standards[x as string]!["lane"]==="experimental"),`profile ${id} promotes a draft standard`);const status=yield* str(p["status"],`profile ${id} status`);for(const art of yield* list(p["implementation_artifacts"]??[],`profile ${id} artifacts`)){const x=yield* row(art,`profile ${id} artifact`),path=yield* rel(x["path"],`profile ${id} artifact path`),b=yield* file(inventory,path,`profile ${id} implementation artifact`);yield* req(sha(b)===String(x["sha256"]),`profile ${id} implementation artifact drift`)}if(status.startsWith("RUNNABLE_")){runnable.push(id);const sourceId=yield* str(p["suite_source_id"],`profile ${id} suite source`),adapterId=yield* str(p["adapter_id"],`profile ${id} adapter`);yield* req(sources[sourceId]!==undefined&&adapters[adapterId]!==undefined,`profile ${id} has no locked suite`);const runner=yield* rel(p["runner"],`profile ${id} runner`),b=yield* file(inventory,runner,`profile ${id} runner`);yield* req(sha(b)===(yield* digest(p["runner_sha256"],`profile  runner digest`)),`profile ${id} runner digest drift`);const runtime=yield* str(p["runner_runtime"]??"node",`profile ${id} runner runtime`);yield* req(runtime==="node"||runtime==="python",`profile ${id} runner runtime is unsupported`);yield* req((p["runner_suite_scope"]??"selected_path")==="selected_path"||(p["runner_suite_scope"]??"selected_path")==="checkout_root",`profile ${id} runner suite scope is unsupported`);yield* req((p["runner_suite_argument"]??"--suite-root")==="--suite-root"||(p["runner_suite_argument"]??"--suite-root")==="--suite-checkout",`profile ${id} runner suite argument is unsupported`);const manifestPath=yield* rel(p["qualification_manifest_path"],`profile ${id} qualification manifest path`),selected=String(sources[sourceId]!["selected_path"]);yield* req(manifestPath.startsWith(`${selected}/`),`profile ${id} qualification manifest escapes selected source`);yield* digest(p["qualification_manifest_sha256"],`profile ${id} qualification manifest`);const expected=yield* row(p["expected"],`profile ${id} expected counts`),denominator=yield* str(p["pass_count_field"]??"total",`profile ${id} pass count field`);yield* req(Object.keys(expected).length>0&&Object.values(expected).every(v=>typeof v==="number"&&Number.isInteger(v)&&v>=0)&&typeof expected[denominator]==="number"&&expected[denominator]>0,`profile ${id} expected counts are invalid`)}}
 if(verifyReceipts){const seen:string[]=[];for(const r of yield* list(l["qualification_receipts"],"qualification_receipts")){const q=yield* row(r,"qualification receipt"),id=yield* str(q["profile_id"],"qualification receipt profile_id");yield* req(profiles[id]!==undefined&&!seen.includes(id),`invalid or duplicate receipt profile: ${id}`);seen.push(id);const path=yield* rel(q["path"],`qualification receipt ${id} path`),receipt=yield* row(yield* parse(yield* file(inventory,path,`qualification receipt ${id}`),`qualification receipt ${id}`),`qualification receipt ${id}`),declared=yield* digest(q["receipt_sha256"],`qualification receipt ${id} digest`),unsigned=Object.fromEntries(Object.entries(receipt).filter(([k])=>k!=="receipt_sha256"));yield* req(receipt["receipt_sha256"]===declared&&sha(canonical(unsigned))===declared,`qualification receipt digest drift: ${id}`);const p=profiles[id]!,result=yield* row(receipt["result"],`qualification receipt ${id} result`),counts=yield* row(result["counts"],`qualification receipt ${id} counts`),adapter=yield* row(receipt["adapter"],`qualification receipt  adapter`),expected=yield* row(p["expected"],`qualification profile  expected`),sourceReceipt=yield* row(receipt["source"],`qualification receipt  source`),runtime=yield* row(receipt["runtime"],`qualification receipt  runtime`),expectedRuntime=yield* runtimeReceipt(l,p);yield* req(receipt["schema_version"]===GRAPH_STANDARDS_RECEIPT_SCHEMA&&receipt["profile_id"]===id&&receipt["lane"]===p["lane"]&&same(receipt["standards"],p["standard_ids"])&&result["status"]==="PASS"&&counts["failed"]===0&&counts["passed"]===counts[String(p["pass_count_field"]??"total")]&&Object.entries(expected).every(([k,v])=>counts[k]===v)&&receipt["claim_ceiling"]===p["claim_ceiling"]&&same(adapter,receiptAdapter(adapters[p["adapter_id"] as string]!))&&sourceReceipt["repository"]===sources[p["suite_source_id"] as string]!["repository"]&&sourceReceipt["commit"]===sources[p["suite_source_id"] as string]!["commit"]&&sourceReceipt["selected_path"]===sources[p["suite_source_id"] as string]!["selected_path"]&&sourceReceipt["tree_sha1"]===sources[p["suite_source_id"] as string]!["git_tree_sha1"]&&sourceReceipt["archive_sha256"]===sources[p["suite_source_id"] as string]!["git_archive_sha256"]&&sourceReceipt["license_sha256"]===sources[p["suite_source_id"] as string]!["license_sha256"]&&sourceReceipt["source_manifest_sha256"]===sources[p["suite_source_id"] as string]!["manifest_sha256"]&&sourceReceipt["qualification_manifest_path"]===p["qualification_manifest_path"]&&sourceReceipt["qualification_manifest_sha256"]===p["qualification_manifest_sha256"]&&same(runtime,expectedRuntime)&&same(receipt["runner"],{path:p["runner"]!,sha256:p["runner_sha256"]!}),`qualification receipt boundary drift: ${id}`)}yield* req([...seen].sort().join(",")===[...runnable].sort().join(","),"qualification receipt coverage drift: missing=[], extra=[]")}
 const mcp=yield* row(l["mcp"],"mcp"),registry=yield* row(mcp["registry"],"mcp.registry");yield* req(registry["use"]==="DISCOVERY_ONLY"&&registry["auto_trust"]===false&&registry["auto_install"]===false,"MCP Registry boundary drift");const sdk=yield* row(mcp["new_typescript_sdk"],"MCP TypeScript SDK"),packages=yield* list(sdk["packages"],"MCP SDK packages"),tags=yield* row(sdk["source_tags"],"MCP SDK source tags"),integrities=yield* row(sdk["npm_integrities"],"MCP SDK npm integrities");yield* req(packages.length>0&&packages.every(x=>typeof x==="string"&&tags[x]===`${x}@${sdk["version"]}`&&typeof integrities[x]==="string"&&integrities[x].startsWith("sha512-")),"MCP SDK package pin coverage drift");const skills=yield* row(l["skills"],"skills");yield* req(Array.isArray(skills["required_new_installations"])&&skills["required_new_installations"].length===0,"unexpected Skill installation entered the graph toolchain");return{adapters,profiles,sources,standards}
})
