import { createHash } from "node:crypto"
import { isAbsolute, normalize, parse, sep } from "node:path"
import { Data, Either } from "effect"

export const LEGACY_REPLAY_LIST_V1="hswm-legacy-replay-list/v1" as const
export const LEGACY_REPLAY_VERIFICATION_V1="hswm-legacy-replay-verification/v1" as const
export const LEGACY_REPLAY_RECEIPT_V1="hswm-legacy-replay-workspace-receipt/v1" as const
export const LEGACY_REPLAY_RECEIPT_NAME="hswm-legacy-replay.json" as const
export const LEGACY_REPLAY_ONTOLOGY="ontology/HSWM_REPOSITORY_ONTOLOGY.v1.json" as const
export class NativeLegacyReplayError extends Data.TaggedError("NativeLegacyReplayError")<{readonly detail:string}>{}
export const legacyRefusal=(detail:string):NativeLegacyReplayError=>new NativeLegacyReplayError({detail})
export type LegacyJson=null|boolean|number|string|ReadonlyArray<LegacyJson>|{readonly [key:string]:LegacyJson}
export interface LegacyMigrationEntry extends Readonly<Record<string,LegacyJson>> {readonly old_path:string;readonly canonical_path:string;readonly source_commit:string;readonly source_sha256:string;readonly migration_manifest:string;readonly destination_kind:string|null}
export type MigrationFamily="python"|"asset"
export type ManifestSource=readonly [string,MigrationFamily,string]
const commit=/^[0-9a-f]{40}$/,digest=/^[0-9a-f]{64}$/,pyOld=/^[^/\\]+\.py$/,assetOld=/^[^/\\]+\.(?:md|json|txt|log|sh)$/
const pyPrefixes:Readonly<Record<string,string>>=Object.freeze({"canonical-package":"src/hswm/","research-source":"_research/","maintenance-script":"scripts/",test:"tests/"})
const assetPrefixes:Readonly<Record<string,string>>=Object.freeze({"compatibility-record":"_research/root_compat/","canon-document":"docs/canon/","research-document":"docs/research/","archive-document":"docs/archive/",evidence:"evidence/",preregistration:"prereg/",manifest:"manifests/","research-record":"research/",result:"results/",receipt:"receipts/","source-text":"docs/canon/sources/","run-log":"results/logs/","maintenance-shell":"scripts/"})
export const sha256=(bytes:Uint8Array):string=>createHash("sha256").update(bytes).digest("hex")
/** Python's JSON sort_keys orders Unicode code points; Array.sort orders UTF-16 units. */
const codePointOrder=(first:string,second:string):number=>{const a=Array.from(first),b=Array.from(second),length=Math.min(a.length,b.length);for(let index=0;index<length;index+=1){const left=a[index]!.codePointAt(0)!,right=b[index]!.codePointAt(0)!;if(left!==right)return left-right}return a.length-b.length}
export const renderCanonicalJson=(v:LegacyJson):string=>v===null||typeof v==="boolean"||typeof v==="number"||typeof v==="string"?JSON.stringify(v):Array.isArray(v)?`[${v.map(renderCanonicalJson).join(",")}]`:(()=>{const record=v as Readonly<Record<string,LegacyJson>>;return `{${Object.keys(record).sort(codePointOrder).map(k=>`${JSON.stringify(k)}:${renderCanonicalJson(record[k]!)}`).join(",")}}`})()
export const receiptHash=(v:Readonly<Record<string,LegacyJson>>):string=>sha256(new TextEncoder().encode(renderCanonicalJson(v)))
const object=(v:LegacyJson,detail:string):Either.Either<Readonly<Record<string,LegacyJson>>,NativeLegacyReplayError>=>v!==null&&typeof v==="object"&&!Array.isArray(v)?Either.right(v as Readonly<Record<string,LegacyJson>>):Either.left(legacyRefusal(detail))

/** Strict JSON parser: validates syntax and rejects duplicate object keys before JSON.parse. */
export const strictJsonObject=(source:string,label:string):Either.Either<Readonly<Record<string,LegacyJson>>,NativeLegacyReplayError>=>{
 let at=0;const space=():void=>{while(/\s/.test(source[at]??""))at+=1}
 const string=():string|undefined=>{if(source[at]!=="\"")return undefined;const start=at++;let escaped=false;while(at<source.length){const c=source[at++]!;if(!escaped&&c==="\""){try{return JSON.parse(source.slice(start,at)) as string}catch{return undefined}}escaped=!escaped&&c==="\\"}return undefined}
 const value=():boolean=>{space();const c=source[at];if(c==="\"")return string()!==undefined;if(c==="{"){at+=1;space();const keys=new Set<string>();if(source[at]==="}"){at+=1;return true}while(true){space();const key=string();if(key===undefined||keys.has(key))return false;keys.add(key);space();if(source[at++]!==":")return false;if(!value())return false;space();if(source[at]==="}"){at+=1;return true}if(source[at++]!==",")return false}}if(c==="["){at+=1;space();if(source[at]==="]"){at+=1;return true}while(true){if(!value())return false;space();if(source[at]==="]"){at+=1;return true}if(source[at++]!==",")return false}}const m=/^(?:true|false|null|-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)/.exec(source.slice(at));if(m===null)return false;at+=m[0].length;return true}
 if(!value()){return Either.left(legacyRefusal(`cannot load strict JSON for ${label}`))}space();if(at!==source.length)return Either.left(legacyRefusal(`cannot load strict JSON for ${label}`));try{const parsed=object(JSON.parse(source) as LegacyJson,`${label} must be a JSON object`);return Either.isLeft(parsed)?Either.left(parsed.left):Either.right(parsed.right)}catch{return Either.left(legacyRefusal(`cannot load strict JSON for ${label}`))}
}
export const canonicalRepositoryPath=(v:unknown):v is string=>typeof v==="string"&&v.length>0&&!v.includes("\\")&&!isAbsolute(v)&&!v.split("/").includes("..")&&normalize(v)===v
const refs=(o:Readonly<Record<string,LegacyJson>>,key:string,required:boolean):Either.Either<ReadonlyArray<string>,NativeLegacyReplayError>=>{const v=o[key];const paths=typeof v==="string"?[v]:Array.isArray(v)&&v.length>0&&v.every((x):x is string=>typeof x==="string"&&x.length>0)?v:!required&&v===undefined?[]:undefined;return paths===undefined||!paths.every(canonicalRepositoryPath)||new Set(paths).size!==paths.length?Either.left(legacyRefusal(`repository ontology has invalid ${key}`)):Either.right(paths)}
export const selectedManifestReferences=(text:string):Either.Either<ReadonlyArray<readonly [string,MigrationFamily]>,NativeLegacyReplayError>=>{const onto=strictJsonObject(text,"repository ontology");if(Either.isLeft(onto))return Either.left(onto.left);const p=refs(onto.right,"python_root_migrations",true),a=refs(onto.right,"asset_root_migrations",false);if(Either.isLeft(p))return Either.left(p.left);if(Either.isLeft(a))return Either.left(a.left);const result=[...p.right.map(x=>[x,"python"] as const),...a.right.map(x=>[x,"asset"] as const)];return new Set(result.map(x=>x[0])).size===result.length?Either.right(Object.freeze(result)):Either.left(legacyRefusal("repository ontology repeats a migration manifest"))}
export const parseEntries=(ontologyText:string,manifests:ReadonlyArray<ManifestSource>):Either.Either<ReadonlyArray<LegacyMigrationEntry>,NativeLegacyReplayError>=>{
 const selected=selectedManifestReferences(ontologyText);if(Either.isLeft(selected))return Either.left(selected.left);const supplied=new Map(manifests.map(x=>[x[0],x] as const)),entries:LegacyMigrationEntry[]=[];const old=new Set<string>(),canonical=new Set<string>()
 for(const [path,family] of selected.right){const source=supplied.get(path);if(source===undefined)return Either.left(legacyRefusal(`migration manifest is missing: ${path}`));const parsed=strictJsonObject(source[2],"migration manifest");if(Either.isLeft(parsed))return Either.left(legacyRefusal(`cannot load strict JSON for migration manifest: ${path}`));const m=parsed.right,version=m["schema_version"],rows=m["migrations"],schema=family==="python"?version==="hswm-python-root-migrations/v1"&&m["$schema"]==="../../schemas/hswm_python_root_migrations.v1.schema.json"||version==="hswm-python-root-migrations/v2"&&m["$schema"]==="../../schemas/hswm_python_root_migrations.v2.schema.json":version==="hswm-root-asset-migrations/v1"&&m["$schema"]==="../../schemas/hswm_root_asset_migrations.v1.schema.json";if(!schema)return Either.left(legacyRefusal(`invalid ${family==="python"?"Python":"asset"} migration schema in ${path}`));if(m["status"]!=="SOURCE_PINNED_PATH_MIGRATION"||typeof m["source_commit"]!=="string"||!commit.test(m["source_commit"])||!Array.isArray(rows)||rows.length===0)return Either.left(legacyRefusal(`invalid migration manifest: ${path}`))
  for(const row of rows){const record=object(row,`migration row must be an object: ${path}`);if(Either.isLeft(record))return Either.left(record.left);const r=record.right,op=r["old_path"],cp=r["canonical_path"],hash=r["source_sha256"],kind=r["destination_kind"];if(typeof op!=="string"||!(family==="python"?pyOld:assetOld).test(op))return Either.left(legacyRefusal(`invalid old_path in ${path}: ${String(op)}`));if(old.has(op))return Either.left(legacyRefusal(`duplicate migrated old_path: ${op}`));if(!canonicalRepositoryPath(cp))return Either.left(legacyRefusal(`invalid canonical_path in ${path}: ${String(cp)}`));if(canonical.has(cp))return Either.left(legacyRefusal(`duplicate canonical_path: ${cp}`));const prefix=family==="python"?version==="hswm-python-root-migrations/v1"?kind===undefined?"src/hswm/":undefined:typeof kind==="string"?pyPrefixes[kind]:undefined:typeof kind==="string"?assetPrefixes[kind]:undefined;if(prefix===undefined||!cp.startsWith(prefix)||(family==="python"&&!cp.endsWith(".py"))||(family==="asset"&&parse(cp).ext!==parse(op).ext))return Either.left(legacyRefusal(`${family==="asset"?"asset ":""}destination kind/path mismatch: ${String(kind)} -> ${cp}`));if(typeof hash!=="string"||!digest.test(hash))return Either.left(legacyRefusal(`invalid source_sha256 for ${op}`));old.add(op);canonical.add(cp);entries.push(Object.freeze({old_path:op,canonical_path:cp,source_commit:m["source_commit"],source_sha256:hash,migration_manifest:path,destination_kind:typeof kind==="string"?kind:null}))}
 }
 return Either.right(Object.freeze(entries.sort((a,b)=>codePointOrder(a.old_path,b.old_path))))
}
export const destinationOverlaps=(root:string,target:string):boolean=>target===root||target.startsWith(`${root}${sep}`)||root.startsWith(`${target}${sep}`)
