import { applyReviewedNativeDevelopmentProjection, compileNativeDevelopmentProjection, exportNativeDevelopmentProjection, exportValidatedNativeDevelopmentProjection, validateNativeDevelopmentProjection, type HistoricalBlobSource, type NativeDevelopmentProjectionExportWriter, type NativeDevelopmentProjectionPublisher, type ProjectionContract } from "./native-development-projection-domain.js"
import { Data, Effect, Either } from "effect"
import { kgSha256 } from "./native-kg-bundle-domain.js"
export const FRONTIER_LEARNING_CONTRACT: ProjectionContract = Object.freeze({ kind:"frontier-learning", sourceId:"frontier-learning-theory", bundleUid:"sym:AbstractNode:hswm-frontier-learning-theory-2026-09-07-v1", schemaVersion:"hswm-frontier-learning-theory/v1", sourceCommit:"6e2e49f881ac96cd24cc3064d87273075be339a6", bindingOrigin:"historical", expectedStatus:"LITERATURE_REFERENCE_HSWM_BRIDGES_UNTESTED", relations:Object.freeze(["HAS_SOURCE","HAS_CONCEPT","SPECULATIVE_LINK","REQUIRES","PRESERVES","TESTS"]), requiredTop:Object.freeze(["schema_version","bundle_uid","status","nonclaim","artifact_bindings","expected_counts","anchors","nodes","relations"]), optionalTop:Object.freeze(["authority_boundary","source_accessed_on"]) })
export const validateFrontierLearningProjection = (value: unknown, blobs: HistoricalBlobSource) => validateNativeDevelopmentProjection(value, FRONTIER_LEARNING_CONTRACT, blobs)
export const compileFrontierLearningProjection = (value: unknown, rawBytes: Uint8Array, blobs: HistoricalBlobSource) => compileNativeDevelopmentProjection(value, rawBytes, FRONTIER_LEARNING_CONTRACT, blobs)
export const applyReviewedFrontierLearningProjection = (value: unknown, rawBytes: Uint8Array, reviewedSha256: string, blobs: HistoricalBlobSource, publisher: NativeDevelopmentProjectionPublisher) => applyReviewedNativeDevelopmentProjection(value, rawBytes, reviewedSha256, FRONTIER_LEARNING_CONTRACT, blobs, publisher)
export const exportFrontierLearningProjection = (value: unknown, rawBytes: Uint8Array, blobs: HistoricalBlobSource, writer: NativeDevelopmentProjectionExportWriter) => { const compiled = compileFrontierLearningProjection(value, rawBytes, blobs); return Either.isLeft(compiled) ? Effect.fail(compiled.left) : exportNativeDevelopmentProjection(compiled.right, writer) }
export const exportValidatedFrontierLearningProjection = (value: unknown, rawBytes: Uint8Array, blobs: HistoricalBlobSource, shapes: Uint8Array, writer: NativeDevelopmentProjectionExportWriter) => { const compiled = compileFrontierLearningProjection(value, rawBytes, blobs); return Either.isLeft(compiled) ? Effect.fail(compiled.left) : exportValidatedNativeDevelopmentProjection(compiled.right, shapes, writer) }
export class NativeFrontierHistoricalError extends Data.TaggedError("NativeFrontierHistoricalError")<{ readonly detail: string }> {}
const historicalFail = (detail: string): Either.Either<never, NativeFrontierHistoricalError> => Either.left(new NativeFrontierHistoricalError({ detail }))
const object = (value: unknown): value is Readonly<Record<string, unknown>> => typeof value === "object" && value !== null && !Array.isArray(value)
const snapshotPath = "ontology/identity/hswm_core/HSWM_FRONTIER_LEARNING_THEORY_ONTOLOGY.v1.json"
/** Replays the fixed historical source index entirely through injected Git blobs. */
export const validateFrontierHistoricalSnapshot = (snapshot: unknown, rawBundle: Uint8Array, blobs: HistoricalBlobSource): Either.Either<{ readonly historical_source_commit: string; readonly artifact_bindings: number }, NativeFrontierHistoricalError> => {
  if (!object(snapshot) || JSON.stringify(Object.keys(snapshot).sort()) !== JSON.stringify(["artifact_bindings","bundle_path","bundle_sha256","schema_version","source_commit"]) || snapshot["schema_version"] !== "hswm-frontier-learning-theory-source-snapshot/v1" || snapshot["bundle_path"] !== snapshotPath || typeof snapshot["bundle_sha256"] !== "string" || typeof snapshot["source_commit"] !== "string" || !/^[0-9a-f]{40}$/.test(snapshot["source_commit"])) return historicalFail("historical snapshot shape or schema drift")
  if (kgSha256(rawBundle) !== "47fe62066a03f7b8556e9d3f5b45cc583d75ab6696d515a59088cd37d462159a") return historicalFail("historical ontology differs from reviewed artifact SHA pin")
  if (snapshot["bundle_sha256"] !== kgSha256(rawBundle)) return historicalFail("historical ontology raw hash drift")
  const historicalBundle = blobs.readBlob(snapshot["source_commit"], snapshotPath)
  if (historicalBundle === undefined || historicalBundle.byteLength !== rawBundle.byteLength || !historicalBundle.every((byte, index) => byte === rawBundle[index])) return historicalFail("historical ontology Git blob mismatch")
  if (!Array.isArray(snapshot["artifact_bindings"]) || snapshot["artifact_bindings"].length === 0) return historicalFail("historical snapshot bindings are invalid")
  const seen = new Set<string>()
  for (const row of snapshot["artifact_bindings"]) { if (!object(row) || JSON.stringify(Object.keys(row).sort()) !== JSON.stringify(["path","sha256","source_commit"]) || typeof row["path"] !== "string" || !/^[A-Za-z0-9_][A-Za-z0-9_./:+-]{0,255}$/.test(row["path"]) || row["path"].split("/").includes("..") || typeof row["sha256"] !== "string" || !/^[0-9a-f]{64}$/.test(row["sha256"]) || row["source_commit"] !== snapshot["source_commit"] || seen.has(row["path"])) return historicalFail("historical snapshot binding shape drift"); const blob=blobs.readBlob(snapshot["source_commit"],row["path"]); if(blob===undefined||kgSha256(blob)!==row["sha256"])return historicalFail(`historical source hash drift: ${row["path"]}`);seen.add(row["path"]) }
  return Either.right({ historical_source_commit: snapshot["source_commit"], artifact_bindings: seen.size })
}
/** Keeps each reported paper linked to one mechanism, bridge, and falsifier without promoting efficacy. */
interface FrontierNode { readonly uid:string; readonly properties:Readonly<Record<string,unknown>> }
interface FrontierRelation { readonly from:string; readonly to:string; readonly type:string }
export const validateFrontierPaperTopology=(value:unknown):Either.Either<void,NativeFrontierHistoricalError>=>{if(!object(value)||!Array.isArray(value["nodes"])||!Array.isArray(value["relations"])||!object(value["expected_counts"]))return historicalFail("frontier topology shape");const nodes=new Map<string,FrontierNode>();for(const row of value["nodes"]){if(!object(row)||typeof row["uid"]!=="string"||!object(row["properties"]))return historicalFail("frontier node shape");const labels=row["labels"];if(!Array.isArray(labels)||!labels.every(label=>typeof label==="string"))return historicalFail("frontier node labels");nodes.set(row["uid"],{uid:row["uid"],properties:row["properties"]})}const outgoing=new Map<string,FrontierRelation[]>();for(const row of value["relations"]){if(!object(row)||typeof row["from_uid"]!=="string"||typeof row["to_uid"]!=="string"||typeof row["type"]!=="string"||row["authority_class"]!=="SECONDARY_AI")return historicalFail("frontier relation authority or shape");const relation={from:row["from_uid"],to:row["to_uid"],type:row["type"]};outgoing.set(relation.from,[...(outgoing.get(relation.from)??[]),relation])}const papers=[...nodes.values()].filter(node=>node.properties["standard_graph_role"]==="LITERATURE_SOURCE");if(papers.length!==35||value["expected_counts"]["papers"]!==35)return historicalFail("frontier paper count");const keys=["url","authors","year","source_date","source_version","source_verified_on","source_status","inspected_scope","verification_note","source_authority_class","source_paths","primary_artifact_path","primary_artifact_json_pointer"];const one=(from:string,type:string,role:string)=> (outgoing.get(from)??[]).filter(edge=>edge.type===type&&nodes.get(edge.to)?.properties["standard_graph_role"]===role);for(const paper of papers){const p=paper.properties;if(keys.some(key=>p[key]===undefined||p[key]===""||Array.isArray(p[key])&&p[key].length===0)||p["source_authority_class"]!=="EXTERNAL_PRIMARY_SOURCE_REPORTED")return historicalFail("frontier paper provenance");const mechanisms=one(paper.uid,"HAS_CONCEPT","REPORTED_MECHANISM");if(mechanisms.length!==1)return historicalFail("frontier paper mechanism");const bridges=one(mechanisms[0]!.to,"SPECULATIVE_LINK","HSWM_BRIDGE_CANDIDATE");if(bridges.length!==1)return historicalFail("frontier mechanism bridge");const falsifiers=one(bridges[0]!.to,"REQUIRES","PROPOSED_FALSIFIER");if(falsifiers.length!==1)return historicalFail("frontier bridge falsifier");if(!(outgoing.get(falsifiers[0]!.to)??[]).some(edge=>edge.type==="TESTS"&&edge.to===bridges[0]!.to))return historicalFail("frontier falsifier tests bridge")}return Either.right(undefined)}
