/** Pure local-only adapters for describe, workflow-options, statement and parse-dsse. */
import { createHash } from "node:crypto"
import { Data, Either } from "effect"
import { decodeGeneralJsonBytes } from "./general-json-domain.js"
export const HSWM_OCCURRENCE_CLI_SCHEMA="hswm-g0-occurrence-local-cli/v1" as const
export const HSWM_OCCURRENCE_CLI_CLAIM_BOUNDARY="local deterministic preparation and inspection only; not external registration, signature verification, execution, publication, outcome truth, Permit, causal credit, canonical admission, learning, or G0 evidence" as const
export class NativeOccurrenceCliError extends Data.TaggedError("NativeOccurrenceCliError")<{readonly detail:string}>{}
const fail=<A=never>(detail:string):Either.Either<A,NativeOccurrenceCliError>=>Either.left(new NativeOccurrenceCliError({detail}))
const sha=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex")
const text=(v:unknown):v is string=>typeof v==="string"&&v.length>0&&v.length<=1024
const base64=(value:string):Uint8Array|null=>{if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/u.test(value))return null;const decoded=Uint8Array.from(Buffer.from(value,"base64"));return Buffer.from(decoded).toString("base64")===value?decoded:null}
export const describeNativeOccurrenceBytes=(bytes:Uint8Array,mediaType:string):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceCliError>=>!text(mediaType)?fail("media_type must be bounded"):Either.right(Object.freeze({byte_length:bytes.byteLength,media_type:mediaType,sha256:sha(bytes)}))
export const nativeWorkflowOptions=(occurrenceUid:string):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceCliError>=>!text(occurrenceUid)?fail("occurrence_uid must be bounded"):Either.right(Object.freeze({claim_boundary:"one-shot Temporal launch contract only; not execution, outcome truth, Permit, canonical admission, learning, or G0 evidence",workflow_id:`g0-occurrence/${occurrenceUid}`,workflow_id_reuse_policy:"REJECT_DUPLICATE",workflow_maximum_attempts:1,activity_maximum_attempts:1,replacement_round_allowed:false}))
export const nativeInTotoStatement=(subject:Uint8Array,subjectName:string,mediaType:string,predicateType:string,predicateBytes:Uint8Array):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceCliError>=>{const predicate=decodeGeneralJsonBytes(predicateBytes);if(Either.isLeft(predicate)||typeof predicate.right!=="object"||predicate.right===null||Array.isArray(predicate.right)||![subjectName,mediaType,predicateType].every(text))return fail("statement inputs must be strict JSON and bounded text");return Either.right(Object.freeze({_type:"https://in-toto.io/Statement/v1",predicate:predicate.right,predicateType,subject:[{digest:{sha256:sha(subject)},name:subjectName}]}))}
export const parseNativeDsse=(bytes:Uint8Array):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceCliError>=>{const decoded=decodeGeneralJsonBytes(bytes);if(Either.isLeft(decoded)||typeof decoded.right!=="object"||decoded.right===null||Array.isArray(decoded.right))return fail("DSSE envelope must be strict JSON");const e=decoded.right as Record<string,unknown>;if(Object.keys(e).sort().join(",")!=="payload,payloadType,signatures"||e["payloadType"]!=="application/vnd.in-toto+json"||typeof e["payload"]!=="string"||!Array.isArray(e["signatures"])||e["signatures"].length===0)return fail("DSSE strict profile differs");const payload=base64(e["payload"]);if(payload===null)return fail("DSSE payload invalid standard base64");const parsed=decodeGeneralJsonBytes(payload);if(Either.isLeft(parsed)||typeof parsed.right!=="object"||parsed.right===null||Array.isArray(parsed.right))return fail("DSSE payload is not strict in-toto statement");const s=parsed.right as Record<string,unknown>,subjects=s["subject"];if(Object.keys(s).sort().join(",")!=="_type,predicate,predicateType,subject"||s["_type"]!=="https://in-toto.io/Statement/v1"||!text(s["predicateType"])||typeof s["predicate"]!=="object"||s["predicate"]===null||Array.isArray(s["predicate"])||!Array.isArray(subjects)||subjects.length!==1||typeof subjects[0]!=="object"||subjects[0]===null)return fail("DSSE payload is not strict in-toto statement");const subject=subjects[0] as Record<string,unknown>,sd=subject["digest"] as Record<string,unknown>,keys:string[]=[];if(Object.keys(subject).sort().join(",")!=="digest,name"||!text(subject["name"])||typeof sd!=="object"||sd===null||Array.isArray(sd)||Object.keys(sd).join(",")!=="sha256"||typeof sd["sha256"]!=="string"||!/^[0-9a-f]{64}$/u.test(sd["sha256"]))return fail("DSSE subject invalid");for(const sig of e["signatures"]){if(typeof sig!=="object"||sig===null||Array.isArray(sig)||Object.keys(sig as object).sort().join(",")!=="keyid,sig"||!text((sig as Record<string,unknown>)["keyid"])||typeof (sig as Record<string,unknown>)["sig"]!=="string"||base64((sig as Record<string,string>)["sig"]!)===null)return fail("DSSE signatures invalid");keys.push((sig as Record<string,string>)["keyid"]!)}if(new Set(keys).size!==keys.length)return fail("DSSE signature keyids must be unique");return Either.right(Object.freeze({claim_boundary:HSWM_OCCURRENCE_CLI_CLAIM_BOUNDARY,cryptographically_verified:false,payload_sha256:sha(payload),predicate_type:s["predicateType"],schema_version:HSWM_OCCURRENCE_CLI_SCHEMA,signature_count:keys.length,signature_keyids:keys,subject_name:subject["name"],subject_sha256:sd["sha256"]}))}
export const nativeWormCommand=(body:Uint8Array,bodyPath:string,bucket:string,occurrenceUid:string,retainUntil:string,claimant:string,admin:string,aws="aws"):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceCliError>=>{if(!/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/u.test(bucket)||!/^[A-Za-z][A-Za-z0-9._:-]{0,127}$/u.test(occurrenceUid)||!/^[0-9]{12}$/u.test(claimant)||!/^[0-9]{12}$/u.test(admin)||claimant===admin||!text(aws)||!/^\d{4}-\d\d-\d\dT.*Z$/u.test(retainUntil))return fail("invalid WORM command inputs");const digest=sha(body),checksum=Buffer.from(digest,"hex").toString("base64"),key=`occurrences/${occurrenceUid}/claim.json`,argv=[aws,"s3api","put-object","--bucket",bucket,"--key",key,"--body",bodyPath,"--if-none-match","*","--checksum-algorithm","SHA256","--checksum-sha256",checksum,"--object-lock-mode","COMPLIANCE","--object-lock-retain-until-date",retainUntil,"--expected-bucket-owner",admin,"--no-cli-pager"];return Either.right(Object.freeze({argv,body_sha256:digest,claim_boundary:"S3 put-object plus version-pinned readback classification only; bucket policy, Object Lock configuration, conditional-write enforcement, external time, and claimant/admin organizational independence require separate verification",execution:"NOT_EXECUTED",key,schema_version:"hswm-g0-occurrence-s3-worm-claim-command/v1"}))}
const argv=(exe:string,parts:ReadonlyArray<string>):Either.Either<ReadonlyArray<string>,NativeOccurrenceCliError>=>!text(exe)?fail("executable must be non-empty"):Either.right(Object.freeze([exe,...parts]))
export const nativeCosignAttestArgv=(cosign:string,blob:string,statement:string,bundle:string)=>argv(cosign,["attest-blob","--statement",statement,"--bundle",bundle,"--yes",blob])
export const nativeRfcQueryArgv=(openssl:string,blob:string,request:string)=>argv(openssl,["ts","-query","-data",blob,"-sha256","-cert","-out",request])
export const nativeRfcVerifyArgv=(openssl:string,request:string,response:string,ca:string,untrusted:string|null)=>argv(openssl,["ts","-verify","-queryfile",request,"-in",response,"-CAfile",ca,...(untrusted===null?[]:["-untrusted",untrusted])])
