import { createHash } from "node:crypto"
import { Either } from "effect"
import { canonicalJsonBytes } from "./canonical-atom-v2-json.js"
import { decodeGeneralJsonBytes } from "./general-json-domain.js"
import { NativeOccurrenceCliError } from "./native-occurrence-cli-domain.js"
export const HSWM_HANDOFF_SCHEMA="hswm-g0-external-qualification-handoff/v1",HSWM_HANDOFF_STATUS="BLOCKED_EXTERNAL",HSWM_HANDOFF_BOUNDARY="descriptor-only external-operator handoff and structural validation only; not external independence, artifact qualification, live readiness, registration, execution, outcome truth, G0, Permit, canonical admission, causal credit, or learning evidence"
export const HSWM_HANDOFF_ROLES=["actor","revision_proposer","occurrence_claimant","worm_administrator","custodian","drand_verifier","evaluator_a","evaluator_b","external_auditor"] as const
export const HSWM_HANDOFF_BINDINGS=["HSWM_G0_OSF_REGISTRATION_BINDING","HSWM_G0_WORM_ENDPOINT","HSWM_G0_WORM_POLICY_AUDIT_BINDING","HSWM_G0_SIGSTORE_REKOR_ENDPOINT","HSWM_G0_RFC3161_TSA_ENDPOINT","HSWM_G0_PRODUCTION_TEMPORAL_ENDPOINT","HSWM_G0_TEMPORAL_SIGNAL_AUTHORIZATION_BINDING","HSWM_G0_TOOLCHAIN_QUALIFICATION_BINDING","HSWM_G0_COMPLETION_AUDIT_QUALIFICATION_BINDING","HSWM_G0_DRAND_VERIFIER_BINDING","HSWM_G0_CUSTODIAN_ENDPOINT","HSWM_G0_EVALUATOR_A_ENDPOINT","HSWM_G0_EVALUATOR_B_ENDPOINT","HSWM_G0_DGX_EXECUTION_SURFACE_BINDING","HSWM_G0_PRIVATE_LINEAGE_DISJOINT_HOLDOUT_BINDING"] as const
export const HSWM_HANDOFF_RETURNS=["osf_immutable_registration_readback","dsse_envelope","rekor_inclusion_verification","rfc3161_verified_token","toolchain_qualification_receipt","worm_claim_and_policy_audit","pre_pulse_actor_material_seal","drand_pulse_verification","temporal_history_export","temporal_terminal_audit_receipt","all_run_manifest","custodian_reveal_receipt","evaluator_a_receipt","evaluator_b_receipt","pending_external_audit_candidate_receipt","external_audit_manifest","external_audit_cosign_bundle","final_terminal_receipt"] as const
const fail=<A=never>(detail:string):Either.Either<A,NativeOccurrenceCliError>=>Either.left(new NativeOccurrenceCliError({detail})),sha=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex"),uid=(v:unknown)=>typeof v==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:@-]{0,159}$/u.test(v), slots=(names:readonly string[])=>Object.fromEntries(names.map((x)=>[x,null]))
const canonical=(value:unknown):Either.Either<Uint8Array,NativeOccurrenceCliError>=>{const b=canonicalJsonBytes(value);return Either.isLeft(b)?fail("handoff cannot canonicalize"):Either.right(b.right)}
export const nativeHandoffTemplate=(occurrenceUid:string,toolchainBytes:Uint8Array):Either.Either<Uint8Array,NativeOccurrenceCliError>=>!uid(occurrenceUid)?fail("occurrence_uid must be a bounded ASCII identifier"):canonical({claim_boundary:HSWM_HANDOFF_BOUNDARY,external_binding_descriptors:slots(HSWM_HANDOFF_BINDINGS),occurrence_uid:occurrenceUid,operator_return_checklist:[...HSWM_HANDOFF_RETURNS],operator_return_descriptors:slots(HSWM_HANDOFF_RETURNS),protocol_package_descriptor:null,role_binding_descriptors:slots(HSWM_HANDOFF_ROLES),schema_version:HSWM_HANDOFF_SCHEMA,status:HSWM_HANDOFF_STATUS,toolchain_candidates_sha256:sha(toolchainBytes)})
const descriptor=(v:unknown):boolean=>{if(v===null)return true;if(typeof v!=="object"||Array.isArray(v)||Object.keys(v).sort().join(",")!=="byte_length,media_type,sha256")return false;const r=v as Record<string,unknown>,length=r["byte_length"],media=r["media_type"],digest=r["sha256"];return typeof media==="string"&&typeof length==="number"&&Number.isSafeInteger(length)&&length>=0&&typeof digest==="string"&&/^[0-9a-f]{64}$/u.test(digest)}
const descriptorSlots=(v:unknown,names:readonly string[])=>typeof v==="object"&&v!==null&&!Array.isArray(v)&&Object.keys(v as object).length===names.length&&names.every((n)=>Object.hasOwn(v,n)&&descriptor((v as Record<string,unknown>)[n]))
export const validateNativeHandoff=(raw:Uint8Array,toolchainBytes:Uint8Array):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceCliError>=>{if(raw.byteLength>64*1024)return fail("handoff exceeds byte limit");const d=decodeGeneralJsonBytes(raw);if(Either.isLeft(d)||typeof d.right!=="object"||d.right===null||Array.isArray(d.right))return fail("handoff must be strict UTF-8 JSON");const v=d.right as Record<string,unknown>,b=canonical(v);if(Either.isLeft(b)||Buffer.compare(Buffer.from(b.right),Buffer.from(raw))!==0)return fail("handoff must use canonical JSON bytes");const fields=["claim_boundary","external_binding_descriptors","occurrence_uid","operator_return_checklist","operator_return_descriptors","protocol_package_descriptor","role_binding_descriptors","schema_version","status","toolchain_candidates_sha256"];if(Object.keys(v).length!==fields.length||!fields.every((x)=>Object.hasOwn(v,x))||v["schema_version"]!==HSWM_HANDOFF_SCHEMA||v["status"]!==HSWM_HANDOFF_STATUS||v["claim_boundary"]!==HSWM_HANDOFF_BOUNDARY||v["toolchain_candidates_sha256"]!==sha(toolchainBytes)||!uid(v["occurrence_uid"])||JSON.stringify(v["operator_return_checklist"])!==JSON.stringify(HSWM_HANDOFF_RETURNS)||!descriptor(v["protocol_package_descriptor"])||!descriptorSlots(v["role_binding_descriptors"],HSWM_HANDOFF_ROLES)||!descriptorSlots(v["external_binding_descriptors"],HSWM_HANDOFF_BINDINGS)||!descriptorSlots(v["operator_return_descriptors"],HSWM_HANDOFF_RETURNS))return fail("handoff schema is invalid");const missing=[...(v["protocol_package_descriptor"]===null?["protocol_package_descriptor"]:[]),...HSWM_HANDOFF_ROLES.filter((x)=>(v["role_binding_descriptors"] as Record<string,unknown>)[x]===null).map((x)=>`role_binding_descriptors.${x}`),...HSWM_HANDOFF_BINDINGS.filter((x)=>(v["external_binding_descriptors"] as Record<string,unknown>)[x]===null).map((x)=>`external_binding_descriptors.${x}`),...HSWM_HANDOFF_RETURNS.filter((x)=>(v["operator_return_descriptors"] as Record<string,unknown>)[x]===null).map((x)=>`operator_return_descriptors.${x}`)],roles=HSWM_HANDOFF_ROLES.map((x)=>(v["role_binding_descriptors"] as Record<string,any>)[x]).filter((x)=>x!==null),digests=roles.map((x)=>x.sha256);return Either.right(Object.freeze({claim_boundary:HSWM_HANDOFF_BOUNDARY,declared_role_descriptor_digests_distinct:roles.length===HSWM_HANDOFF_ROLES.length&&new Set(digests).size===digests.length,external_independence_proven:false,g0_passed:false,live_execution_ready:false,missing_descriptor_slots:missing,occurrence_uid:v["occurrence_uid"],schema_version:HSWM_HANDOFF_SCHEMA,status:HSWM_HANDOFF_STATUS,descriptor_graph_complete:missing.length===0,schema_structure_valid:true,structural_validation_only:true,toolchain_candidates_sha256:sha(toolchainBytes)}))}
