/** Effect file boundary for the native efficacy ledger. */
import { resolve } from "node:path"
import { Effect, Either } from "effect"
import { PosixFileSystem, type PosixFileSystemShape } from "./effect-posix-filesystem.js"
import { decodeNativeTaskJson, type TaskJson } from "./native-task-json-domain.js"
import { NativeEfficacyError, verifyNativeEfficacy } from "./native-efficacy-domain.js"

const raw=Object.freeze(["substrate_bench_results.json","ab_p5_full_results.json","ab_p5_full_musique_s7.json","ab_p5_full_musique_s13.json","ab_p5_full_2wiki_s7.json","traversal_bench_results.json","cert_musique_result.json","cert_2wiki_result.json","stale_poisoning_musique_result.json","stale_poisoning_2wiki_result.json","certified_cut_comparison_result.json","h3_title_anchor_result.json","qkv_routing_result.json","qkv_b1_development_result.json","semantic_layer_result.json","semantic_2wiki_oracle_result.json"])
const evidence=Object.freeze(["EVIDENCE_P1_CLOSED_LEARNING_LOOP_2026-07-23.json","P1_GATE_DIAGNOSTIC_R2_2026-07-23.json","P1_RANK_INVARIANCE_DIAGNOSTIC_R2_2026-07-23.json"])
const prereg=(name:string)=>name.startsWith("PREREG_")?"prereg":undefined
const paths=(root:string,name:string):readonly string[]=>name.includes("/")?[resolve(root,name)]:[...(raw.includes(name)?[resolve(root,"results/raw",name)]:[]),...(evidence.includes(name)?[resolve(root,"evidence",name)]:[]),...(prereg(name)?[resolve(root,"prereg",name)]:[]),resolve(root,"_research/root_compat",name),resolve(root,name)]
const names=Object.freeze({semanticPlan:"SEMANTIC_QKV_EXPERIMENT_PLAN_2026-07-20.md",qkvRouting:"qkv_routing.py",semanticFalsifier:"semantic_layer_falsifier.py",semanticManifest:"semantic_layer_fixture_manifest.json",semanticRouting:"semantic_layer_routing.py",semantic2Wiki:"semantic_2wiki_oracle.py",substrate:"substrate_bench_results.json",p5:"ab_p5_full_results.json",p5Musique7:"ab_p5_full_musique_s7.json",p5Musique13:"ab_p5_full_musique_s13.json",p5TwoWiki7:"ab_p5_full_2wiki_s7.json",traversal:"traversal_bench_results.json",certMusique:"cert_musique_result.json",certTwoWiki:"cert_2wiki_result.json",staleMusique:"stale_poisoning_musique_result.json",staleTwoWiki:"stale_poisoning_2wiki_result.json",cut:"certified_cut_comparison_result.json",title:"h3_title_anchor_result.json",qkv:"qkv_routing_result.json",qkvB1:"qkv_b1_development_result.json",semantic:"semantic_layer_result.json",semantic2:"semantic_2wiki_oracle_result.json",p1:"EVIDENCE_P1_CLOSED_LEARNING_LOOP_2026-07-23.json",p1Gate:"P1_GATE_DIAGNOSTIC_R2_2026-07-23.json",p1Rank:"P1_RANK_INVARIANCE_DIAGNOSTIC_R2_2026-07-23.json",p1v2:"receipts/p1v2_l0_r2_512_closeout_20260724.json",p1v3Prereg:"prereg/PREREG_P1V3_POLICY_ACTUATION_2026-07-24.json",p1v3Judge:"receipts/p1v3_policy_heldout_judge_seed3_20260724.json",p1v4Prereg:"prereg/PREREG_P1V4_FRESH_POLICY_REPLICATION_2026-07-24.json",p1v4Judge:"receipts/p1v4_policy_heldout_judge_seed5_r2_20260724.json",l1:"prereg/PREREG_P1V3V4_L1_CAUSAL_LESSON_2026-07-25.json",preregP1:"PREREG_P1_CLOSED_LEARNING_LOOP_2026-07-23.json",diagnosis:"receipts/p1v2_l0_diagnosis_r2_512_20260724.json"})
const sourceKeys=Object.freeze(["semanticPlan","qkvRouting","semanticFalsifier","semanticManifest","semanticRouting","semantic2Wiki"] as const)
const error=(detail:string)=>new NativeEfficacyError({detail})
const readOne=(fs:PosixFileSystemShape,root:string,name:string):Effect.Effect<Uint8Array,NativeEfficacyError>=>Effect.gen(function*(){let last:string="",found:Uint8Array|undefined;for(const path of paths(root,name)){const result=yield* fs.readRegularBounded(path,{maximumBytes:64*1024*1024,minimumBytes:1,operation:"native-efficacy-artifact"}).pipe(Effect.either);if(Either.isLeft(result)){if(result.left.code!=="ENOENT")return yield* Effect.fail(error(`cannot read ${name}: ${result.left.detail}`));last=result.left.detail;continue}if(found!==undefined)return yield* Effect.fail(error(`ambiguous artifact layout for ${name}`));found=result.right.bytes}if(found!==undefined)return found;return yield* Effect.fail(error(`cannot read ${name}: ${last}`))})
export const verifyNativeEfficacyCheckout=(root:string):Effect.Effect<TaskJson,NativeEfficacyError,PosixFileSystem>=>Effect.gen(function*(){const fs=yield* PosixFileSystem;const entries=yield* Effect.forEach(Object.entries(names).filter(([key])=>!sourceKeys.includes(key as typeof sourceKeys[number])),([key,name])=>readOne(fs,root,name).pipe(Effect.map(bytes=>[key,bytes] as const)),{concurrency:1});const sources=yield* Effect.forEach(sourceKeys,key=>readOne(fs,root,names[key]).pipe(Effect.map(bytes=>[key,bytes] as const)),{concurrency:1});const bytes=Object.freeze(Object.fromEntries([...entries,...sources]));const decoded=Object.entries(bytes).filter(([key])=>!sourceKeys.includes(key as typeof sourceKeys[number])).map(([key,value])=>[key,decodeNativeTaskJson(value)] as const);for(const [key,value] of decoded)if(Either.isLeft(value))return yield* Effect.fail(error(`${names[key as keyof typeof names]} must contain a JSON object`));const artifacts=Object.fromEntries(decoded.map(([key,value])=>[key,(value as { readonly right: TaskJson }).right]));for(const [key,value] of Object.entries(artifacts))if(typeof value!=="object"||value===null||Array.isArray(value))return yield* Effect.fail(error(`${names[key as keyof typeof names]} must contain a JSON object`));const result=verifyNativeEfficacy(artifacts,bytes);return Either.isLeft(result)?yield* Effect.fail(result.left):result.right})
