import { makeNativeIssuedRecordFactory } from "./native-issued-record-domain.js"
/** Pure, fail-closed port of infrastructure/occurrence_integrity.py. */
import { createHash } from "node:crypto"
import { Either } from "effect"
import { renderNativeTaskJson, taskJsonRecord, type TaskJson } from "./native-task-json-domain.js"
type KnownField = "media_type" | "sha256" | "byte_length" | "role" | "issuer" | "subject" | "account" | "admin_domain" | "key_ref" | "operations" | "kind" | "authority" | "receipt" | "bound" | "observed_unix" | "duplicate_seen" | "retry_seen" | "registration" | "dsse" | "rekor" | "rfc3161" | "revision_proposer" | "preregistration_binding" | "worm" | "temporal" | "actor_seal" | "drand_proof" | "custodian_reveal" | "evaluator_a" | "evaluator_b" | "dual_evaluation_bridge" | "external_audit"
type ObjectJson = { readonly [key: string]: TaskJson } & { readonly [K in KnownField]?: TaskJson }

export const NATIVE_OCCURRENCE_INTEGRITY_SCHEMA = "hswm-occurrence-integrity/v2" as const
export const NATIVE_OCCURRENCE_INTEGRITY_CLAIM_CEILING = "EXTERNAL_OCCURRENCE_INTEGRITY_CONTRACT_ONLY_NOT_OUTCOME_TRUTH_NOT_CF07_NOT_G0_NOT_G1_NOT_CANONICAL_LEARNING" as const
export type NativeOccurrenceTerminal = "BLOCKED_EXTERNAL" | "INCONCLUSIVE_EXTERNAL_VERIFICATION_REQUIRED" | "CANDIDATE_REQUIRES_EXTERNAL_AUDIT" | "VOID_DUPLICATE_OCCURRENCE" | "VOID_RETRY" | "VOID_LATE_EVIDENCE" | "VOID_EVALUATOR_DISAGREEMENT" | "VOID_ROLE_SEPARATION" | "VOID_BINDING_CHAIN"
export class NativeOccurrenceIntegrityError extends Error { readonly _tag = "NativeOccurrenceIntegrityError"; constructor(readonly detail: string) { super(detail) } }
const fail = <A = never>(detail: string): Either.Either<A, NativeOccurrenceIntegrityError> => Either.left(new NativeOccurrenceIntegrityError(detail))
const id = (x: unknown): x is string => typeof x === "string" && /^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,159}$/u.test(x)
const sha = (x: unknown): x is string => typeof x === "string" && /^[0-9a-f]{64}$/u.test(x)
const integer = (x: unknown): x is number | bigint => typeof x === "bigint" || typeof x === "number" && Number.isSafeInteger(x)
const obj = (x: unknown): x is ObjectJson => taskJsonRecord(x as TaskJson)
const exact = (x: ObjectJson, keys: readonly string[]): boolean => Object.keys(x).length === keys.length && keys.every(k => Object.hasOwn(x, k))
const digest = (x: TaskJson): string => createHash("sha256").update(renderNativeTaskJson(x), "utf8").digest("hex")
const frozen = <A extends object>(x: A): Readonly<A> => Object.freeze(x)
type Descriptor = Readonly<{ mediaType: string; sha256: string; byteLength: number | bigint }>
type Role = Readonly<{ role: string; issuer: string; subject: string; account: string; adminDomain: string; keyRef: string; operations: readonly string[] }>
type Evidence = Readonly<{ kind: string; authority: string; receipt: Descriptor; bound: Descriptor; observed: number | bigint }>
const cd = (x: TaskJson | undefined): Either.Either<Descriptor, NativeOccurrenceIntegrityError> => {
  if (!obj(x) || !exact(x, ["media_type", "sha256", "byte_length"]) || typeof x.media_type !== "string" || x.media_type.length === 0 || x.media_type.length > 160 || !sha(x.sha256) || !integer(x.byte_length) || x.byte_length < 0) return fail("content descriptor")
  return Either.right(frozen({ mediaType: x.media_type, sha256: x.sha256, byteLength: x.byte_length }))
}
const ccd = (x: Descriptor): ObjectJson => ({ byte_length: x.byteLength, media_type: x.mediaType, sha256: x.sha256 })
const role = (x: TaskJson | undefined): Either.Either<Role, NativeOccurrenceIntegrityError> => {
  if (!obj(x) || !exact(x, ["role", "issuer", "subject", "account", "admin_domain", "key_ref", "operations"]) || ![x.role,x.issuer,x.subject,x.account,x.admin_domain,x.key_ref].every(id) || !Array.isArray(x.operations) || x.operations.length === 0 || x.operations.some(v => !id(v)) || new Set(x.operations).size !== x.operations.length || x.operations.includes("*") || x.operations.includes("canonical_write") || x.operations.includes("permit_issue")) return fail("role binding")
  return Either.right(frozen({ role: x.role as string, issuer: x.issuer as string, subject: x.subject as string, account: x.account as string, adminDomain: x.admin_domain as string, keyRef: x.key_ref as string, operations: Object.freeze([...x.operations] as string[]) }))
}
const cr = (x: Role): ObjectJson => ({ account:x.account, admin_domain:x.adminDomain, issuer:x.issuer, key_ref:x.keyRef, operations:x.operations, role:x.role, subject:x.subject })
const evidence = (x: TaskJson | undefined): Either.Either<Evidence, NativeOccurrenceIntegrityError> => {
  if (!obj(x) || !exact(x,["kind","authority","receipt","bound","observed_unix"]) || typeof x.kind !== "string" || !["registration","dsse","rekor","rfc3161","worm_claim","temporal"].includes(x.kind) || !id(x.authority) || !integer(x.observed_unix) || x.observed_unix < 0) return fail("external evidence")
  const receipt=cd(x.receipt), bound=cd(x.bound); if(Either.isLeft(receipt)||Either.isLeft(bound)) return fail("external evidence requires descriptors")
  return Either.right(frozen({kind:x.kind,authority:x.authority as string,receipt:receipt.right,bound:bound.right,observed:x.observed_unix}))
}
const ce = (x: Evidence): ObjectJson => ({authority:x.authority,bound:ccd(x.bound),kind:x.kind,observed_unix:x.observed,receipt:ccd(x.receipt)})
const same = (a: Descriptor,b: Descriptor): boolean => a.mediaType===b.mediaType&&a.sha256===b.sha256&&a.byteLength===b.byteLength
const separate = (roles: readonly Role[]): boolean => new Set(roles.map(x=>x.role)).size===roles.length && roles.every((a,i)=>roles.slice(i+1).every(b=>["issuer","subject","account","adminDomain","keyRef"].every(k=>a[k as keyof Role]!==b[k as keyof Role])))
type Parsed = Readonly<{ registration:Evidence|null;dsse:Evidence|null;rekor:Evidence|null;rfc3161:Evidence|null; prereg:TaskJson|null;worm:TaskJson|null;temporal:TaskJson|null;actor:TaskJson|null;drand:TaskJson|null;reveal:TaskJson|null;a:TaskJson|null;b:TaskJson|null;bridge:TaskJson|null;revision:Role|null;audit:TaskJson|null;duplicate:boolean;retry:boolean; canonical: ObjectJson }>
const nullable = <A>(v: TaskJson | undefined, f:(x:TaskJson)=>Either.Either<A,NativeOccurrenceIntegrityError>): Either.Either<A|null,NativeOccurrenceIntegrityError> => v===null ? Either.right(null) : v===undefined ? fail("missing field") : f(v)
const parse = (value: TaskJson): Either.Either<Parsed,NativeOccurrenceIntegrityError> => {
  if(!obj(value) || !exact(value,["registration","dsse","rekor","rfc3161","preregistration_binding","worm","temporal","actor_seal","drand_proof","custodian_reveal","evaluator_a","evaluator_b","dual_evaluation_bridge","revision_proposer","external_audit","duplicate_seen","retry_seen"]) || typeof value.duplicate_seen!=="boolean" || typeof value.retry_seen!=="boolean") return fail("integrity assessment input")
  const registrationResult=nullable(value.registration,evidence), dsseResult=nullable(value.dsse,evidence), rekorResult=nullable(value.rekor,evidence), rfcResult=nullable(value.rfc3161,evidence), revisionResult=nullable(value.revision_proposer,role)
  if(Either.isLeft(registrationResult)||Either.isLeft(dsseResult)||Either.isLeft(rekorResult)||Either.isLeft(rfcResult)||Either.isLeft(revisionResult)) return fail("integrity carrier")
  const registration=registrationResult.right, dsse=dsseResult.right, rekor=rekorResult.right, rfc3161=rfcResult.right, revision=revisionResult.right
  const copy=(x:TaskJson|undefined):TaskJson|null=>x===null?null:x===undefined?null:x
  const canonical:ObjectJson={schema_version:NATIVE_OCCURRENCE_INTEGRITY_SCHEMA,registration:registration===null?null:ce(registration),dsse:dsse===null?null:ce(dsse),rekor:rekor===null?null:ce(rekor),rfc3161:rfc3161===null?null:ce(rfc3161),preregistration_binding:copy(value.preregistration_binding),worm:copy(value.worm),temporal:copy(value.temporal),actor_seal:copy(value.actor_seal),drand_proof:copy(value.drand_proof),custodian_reveal:copy(value.custodian_reveal),evaluator_a:copy(value.evaluator_a),evaluator_b:copy(value.evaluator_b),dual_evaluation_bridge:copy(value.dual_evaluation_bridge),revision_proposer:revision===null?null:cr(revision),duplicate_seen:value.duplicate_seen,retry_seen:value.retry_seen}
  return Either.right(frozen({registration,dsse,rekor,rfc3161,prereg:copy(value.preregistration_binding),worm:copy(value.worm),temporal:copy(value.temporal),actor:copy(value.actor_seal),drand:copy(value.drand_proof),reveal:copy(value.custodian_reveal),a:copy(value.evaluator_a),b:copy(value.evaluator_b),bridge:copy(value.dual_evaluation_bridge),revision,audit:copy(value.external_audit),duplicate:value.duplicate_seen,retry:value.retry_seen,canonical}))
}
const descAt=(x:TaskJson, key:string): Descriptor|null=>obj(x)?Either.getOrNull(cd(x[key])):null
const roleAt=(x:TaskJson,key:string): Role|null=>obj(x)?Either.getOrNull(role(x[key])):null
const field=(x:TaskJson,key:string):TaskJson|undefined=>obj(x)?x[key]:undefined
const eqDesc=(x:TaskJson,key:string,y:TaskJson,l:string):boolean=>{const a=descAt(x,key),b=descAt(y,l);return a!==null&&b!==null&&same(a,b)}
const validShaAt=(x:TaskJson,key:string):string|null=>obj(x)&&sha(x[key])?x[key]:null
const numAt=(x:TaskJson,key:string):number|bigint|null=>obj(x)&&integer(x[key])?x[key]:null
const textAt=(x:TaskJson,key:string):string|null=>obj(x)&&typeof x[key]==="string"?x[key]:null
const boolAt=(x:TaskJson,key:string):boolean|null=>obj(x)&&typeof x[key]==="boolean"?x[key]:null
const descriptorAt=(x:TaskJson,key:string):Descriptor|null=>Either.getOrNull(cd(field(x,key)))
const evidenceAt=(x:TaskJson,key:string):Evidence|null=>Either.getOrNull(evidence(field(x,key)))
const canonDescriptorAt=(x:TaskJson,key:string):ObjectJson|null=>{const d=descriptorAt(x,key);return d===null?null:ccd(d)}
const canonRoleAt=(x:TaskJson,key:string):ObjectJson|null=>{const r=roleAt(x,key);return r===null?null:cr(r)}
const canonicalRaw=(x:TaskJson):ObjectJson|null=>obj(x)?x:null
const validateComponents=(prereg:TaskJson,worm:TaskJson,temporal:TaskJson,actor:TaskJson,drand:TaskJson,reveal:TaskJson,a:TaskJson,b:TaskJson,bridge:TaskJson,audit:TaskJson): string|null=>{
 if(!obj(prereg)||!exact(prereg,["registration_package","registration_payload_sha256","plan_sha256","drand_chain_hash","drand_round","pulse_unix","manifest"])||!obj(worm)||!exact(worm,["occurrence_uid","object_key","version_id","conditional_create","object_lock_mode","retain_until_unix","policy_sha256","configuration_audit","claim_manifest","claimant","administrator","evidence"])||!obj(temporal)||!exact(temporal,["occurrence_uid","workflow_id","reuse_policy","workflow_maximum_attempts","activity_maximum_attempts","replacement_round_allowed","worm_claim_receipt","workflow_options","launch_manifest","evidence"])||!obj(actor)||!exact(actor,["occurrence_uid","plan_sha256","action_seal_sha256","material","episodes","manifest","sealed_unix","signer","evidence"])||!obj(drand)||!exact(drand,["occurrence_uid","chain_hash","round","pulse_unix","raw_pulse","verifier_receipt","actor_manifest","outcome_bundle","verifier","cryptographically_verified"])||!obj(reveal)||!exact(reveal,["occurrence_uid","pulse_unix","revealed_unix","mapping","outcome_bundle","evaluation_input","manifest","signer","evidence"])||!obj(a)||!exact(a,["occurrence_uid","evaluator","audit_system","input","output","task","scorer","config","implementation","signature_audit","audit_manifest","signature_verified_externally","score_sha256","blind_to_arm_identity","evaluated_unix","evidence"])||!obj(b)||!exact(b,["occurrence_uid","evaluator","audit_system","input","output","task","scorer","config","implementation","signature_audit","audit_manifest","signature_verified_externally","score_sha256","blind_to_arm_identity","evaluated_unix","evidence"])||!obj(bridge)||!exact(bridge,["dual_evaluation_evidence_sha256","evaluator_a_receipt","evaluator_b_receipt","bridge_manifest","externally_verified"])||!obj(audit)||!exact(audit,["audited_chain_sha256","report","signature_audit","auditor","externally_verified","issuer_separation_verified"]))return "component keys do not match frozen schema"
 const pp=descriptorAt(prereg,"registration_package"), pm=descriptorAt(prereg,"manifest"), plan=validShaAt(prereg,"plan_sha256"), payload=validShaAt(prereg,"registration_payload_sha256"), chain=validShaAt(prereg,"drand_chain_hash"), round=numAt(prereg,"drand_round"), pPulse=numAt(prereg,"pulse_unix")
 if(pp===null||pm===null||plan===null||payload===null||chain===null||round===null||pPulse===null||round<=0||pPulse<0||pm.sha256!==digest({schema:"hswm-preregistration-plan-binding/v1",registration_package:ccd(pp),registration_payload_sha256:payload,plan_sha256:plan,drand_chain_hash:chain,drand_round:round,pulse_unix:pPulse}))return "preregistration binding invalid"
 const uid=textAt(worm,"occurrence_uid"), objectKey=textAt(worm,"object_key"), version=textAt(worm,"version_id"), conditional=textAt(worm,"conditional_create"), lock=textAt(worm,"object_lock_mode"), retain=numAt(worm,"retain_until_unix"), policy=validShaAt(worm,"policy_sha256"), config=descriptorAt(worm,"configuration_audit"), claim=descriptorAt(worm,"claim_manifest"), claimant=roleAt(worm,"claimant"), admin=roleAt(worm,"administrator"), wormEvidence=evidenceAt(worm,"evidence")
 if(uid===null||objectKey!==`occurrences/${uid}/claim.json`||version===null||!id(version)||conditional!=="If-None-Match:*"||lock!=="COMPLIANCE"||retain===null||retain<=0||policy===null||config===null||claim===null||claim.sha256!==digest({schema:"hswm-worm-claim-manifest/v1",occurrence_uid:uid,object_key:objectKey,version_id:version,conditional_create:conditional,object_lock_mode:lock,retain_until_unix:retain,policy_sha256:policy,configuration_audit:ccd(config)})||claimant===null||admin===null||claimant.role!=="occurrence_claimant"||admin.role!=="worm_administrator"||!separate([claimant,admin])||wormEvidence===null||wormEvidence.kind!=="worm_claim"||!same(wormEvidence.bound,claim))return "WORM claim invalid"
 const work=textAt(temporal,"workflow_id"), reuse=textAt(temporal,"reuse_policy"), wa=numAt(temporal,"workflow_maximum_attempts"), aa=numAt(temporal,"activity_maximum_attempts"), replacement=boolAt(temporal,"replacement_round_allowed"), wr=descriptorAt(temporal,"worm_claim_receipt"), options=descriptorAt(temporal,"workflow_options"), launch=descriptorAt(temporal,"launch_manifest"), te=evidenceAt(temporal,"evidence")
 if(work!==`g0-occurrence/${uid}`||reuse!=="REJECT_DUPLICATE"||wa!==1||aa!==1||replacement!==false||wr===null||options===null||launch===null||launch.sha256!==digest({schema:"hswm-temporal-one-shot-launch-manifest/v1",occurrence_uid:uid,workflow_id:work,reuse_policy:reuse,workflow_maximum_attempts:wa,activity_maximum_attempts:aa,replacement_round_allowed:replacement,worm_claim_receipt:ccd(wr),workflow_options:ccd(options)})||te===null||te.kind!=="temporal"||!same(te.bound,launch))return "Temporal contract invalid"
 const actorUid=textAt(actor,"occurrence_uid"), actorPlan=validShaAt(actor,"plan_sha256"), action=validShaAt(actor,"action_seal_sha256"), material=descriptorAt(actor,"material"), episodes=field(actor,"episodes"), am=descriptorAt(actor,"manifest"), sealed=numAt(actor,"sealed_unix"), signer=roleAt(actor,"signer"), ae=evidenceAt(actor,"evidence")
 if(actorUid!==uid||actorPlan===null||action===null||material===null||!Array.isArray(episodes)||episodes.length!==20||am===null||sealed===null||sealed<0||signer===null||signer.role!=="actor"||ae===null||ae.kind!=="dsse"||!same(ae.bound,am))return "actor material invalid"
 const episodeCanonical:TaskJson[]=[]; const ids=new Set<string>(); for(const ep of episodes){if(!obj(ep)||!exact(ep,["episode_uid","request","response","action"])){return "actor material invalid"}const eu=textAt(ep,"episode_uid"),q=descriptorAt(ep,"request"),s=descriptorAt(ep,"response"),ac=descriptorAt(ep,"action");if(eu===null||q===null||s===null||ac===null||ids.has(eu))return "actor material invalid";ids.add(eu);episodeCanonical.push({action:ccd(ac),episode_uid:eu,request:ccd(q),response:ccd(s)})};if(am.sha256!==digest({schema:"hswm-actor-material-manifest/v1",occurrence_uid:uid,plan_sha256:actorPlan,action_seal_sha256:action,material:ccd(material),episodes:episodeCanonical}))return "actor manifest invalid"
 const dUid=textAt(drand,"occurrence_uid"), dChain=validShaAt(drand,"chain_hash"), dRound=numAt(drand,"round"), pulse=numAt(drand,"pulse_unix"), raw=descriptorAt(drand,"raw_pulse"), verifierReceipt=descriptorAt(drand,"verifier_receipt"), actorManifest=descriptorAt(drand,"actor_manifest"), outcome=descriptorAt(drand,"outcome_bundle"), verifier=roleAt(drand,"verifier")
 if(dUid!==uid||dChain===null||dRound===null||dRound<=0||pulse===null||pulse<0||raw===null||verifierReceipt===null||actorManifest===null||outcome===null||verifier===null||verifier.role!=="drand_verifier"||boolAt(drand,"cryptographically_verified")!==true)return "drand proof invalid"
 const rUid=textAt(reveal,"occurrence_uid"), rPulse=numAt(reveal,"pulse_unix"), revealed=numAt(reveal,"revealed_unix"), mapping=descriptorAt(reveal,"mapping"), rOutcome=descriptorAt(reveal,"outcome_bundle"), input=descriptorAt(reveal,"evaluation_input"), rm=descriptorAt(reveal,"manifest"), rs=roleAt(reveal,"signer"), re=evidenceAt(reveal,"evidence")
 if(rUid!==uid||rPulse===null||revealed===null||revealed<rPulse||mapping===null||rOutcome===null||input===null||rm===null||rm.sha256!==digest({schema:"hswm-custodian-reveal-manifest/v1",occurrence_uid:uid,pulse_unix:rPulse,mapping:ccd(mapping),outcome_bundle:ccd(rOutcome),evaluation_input:ccd(input)})||rs===null||rs.role!=="outcome_custodian"||re===null||re.kind!=="dsse"||!same(re.bound,rm))return "custodian reveal invalid"
 for(const [receipt,expectedSystem,expectedRole] of [[a,"inspect_ai","evaluator_a"],[b,"independent_b","evaluator_b"]] as const){const eu=textAt(receipt,"occurrence_uid"),er=roleAt(receipt,"evaluator"),sys=textAt(receipt,"audit_system"),i=descriptorAt(receipt,"input"),o=descriptorAt(receipt,"output"),task=descriptorAt(receipt,"task"),scorer=descriptorAt(receipt,"scorer"),cfg=descriptorAt(receipt,"config"),impl=descriptorAt(receipt,"implementation"),signature=descriptorAt(receipt,"signature_audit"),auditManifest=descriptorAt(receipt,"audit_manifest"),score=validShaAt(receipt,"score_sha256"),at=numAt(receipt,"evaluated_unix"),ev=evidenceAt(receipt,"evidence");if(eu!==uid||er===null||er.role!==expectedRole||sys!==expectedSystem||i===null||o===null||task===null||scorer===null||cfg===null||impl===null||signature===null||auditManifest===null||auditManifest.sha256!==digest({schema:"hswm-evaluation-audit-manifest/v1",occurrence_uid:uid,evaluator_role:er.role,input:ccd(i),output:ccd(o),task:ccd(task),scorer:ccd(scorer),config:ccd(cfg),implementation:ccd(impl),signature_audit:ccd(signature)})||score===null||boolAt(receipt,"blind_to_arm_identity")!==true||boolAt(receipt,"signature_verified_externally")!==true||at===null||at<0||ev===null||ev.kind!=="dsse"||!same(ev.bound,auditManifest))return "evaluation receipt invalid"}
 const dual=validShaAt(bridge,"dual_evaluation_evidence_sha256"), ar=descriptorAt(bridge,"evaluator_a_receipt"),br=descriptorAt(bridge,"evaluator_b_receipt"),bm=descriptorAt(bridge,"bridge_manifest");if(dual===null||ar===null||br===null||bm===null||boolAt(bridge,"externally_verified")!==true)return "dual evaluation bridge invalid"
 const ca=canonicalRaw(a),cb=canonicalRaw(b);if(ca===null||cb===null||bm.sha256!==digest({schema:"hswm-dual-evaluation-bridge/v1",evaluator_a:ca,evaluator_b:cb,dual_evaluation_evidence_sha256:dual}))return "dual evaluation bridge invalid"
 const achain=validShaAt(audit,"audited_chain_sha256"),report=descriptorAt(audit,"report"),auditSig=descriptorAt(audit,"signature_audit"),auditor=roleAt(audit,"auditor");if(achain===null||report===null||auditSig===null||auditor===null||auditor.role!=="external_auditor"||boolAt(audit,"externally_verified")!==true||boolAt(audit,"issuer_separation_verified")!==true)return "external audit invalid"
 return null
}
const integrityRecords = makeNativeIssuedRecordFactory<NativeOccurrenceAssessment>()
export interface NativeOccurrenceAssessment { readonly terminal:NativeOccurrenceTerminal;readonly claimCeiling:typeof NATIVE_OCCURRENCE_INTEGRITY_CLAIM_CEILING;readonly reason:string;readonly evidenceDigest:string;readonly chainDigest:string;readonly dualEvaluationBindingSha256:string;readonly dualEvaluationEvidenceSha256:string;readonly workflowEvidenceSha256s:readonly string[] }
const assessment=(terminal:NativeOccurrenceTerminal,reason:string,evidenceDigest:string,chainDigest:string,binding:string,dual:string,workflow:readonly string[]):NativeOccurrenceAssessment=>{const r=frozen({terminal,claimCeiling:NATIVE_OCCURRENCE_INTEGRITY_CLAIM_CEILING,reason,evidenceDigest,chainDigest,dualEvaluationBindingSha256:binding,dualEvaluationEvidenceSha256:dual,workflowEvidenceSha256s:Object.freeze([...workflow])});return integrityRecords.issue(r)}
export const nativeOccurrenceAssessmentCanonical=(x:NativeOccurrenceAssessment):Either.Either<ObjectJson,NativeOccurrenceIntegrityError>=>integrityRecords.isIssued(x)?Either.right({schema_version:NATIVE_OCCURRENCE_INTEGRITY_SCHEMA,terminal:x.terminal,claim_ceiling:x.claimCeiling,reason:x.reason,evidence_digest:x.evidenceDigest,chain_digest:x.chainDigest,dual_evaluation_binding_sha256:x.dualEvaluationBindingSha256,dual_evaluation_evidence_sha256:x.dualEvaluationEvidenceSha256,workflow_evidence_sha256s:x.workflowEvidenceSha256s}):fail("assessment was not issued by assess occurrence")
export const nativeAssessOccurrenceIntegrity=(input:TaskJson):Either.Either<NativeOccurrenceAssessment,NativeOccurrenceIntegrityError>=>{
 const p=parse(input);if(Either.isLeft(p))return fail(p.left.detail);const v=p.right,chain=digest(v.canonical),auditCanonical=v.audit===null?null:v.audit,evidenceDigest=digest({chain,external_audit:auditCanonical}), zero="0".repeat(64)
 let resultWorkflow:readonly string[]=[], resultBinding=zero, resultDual=zero
 const result=(t:NativeOccurrenceTerminal,r:string,w:readonly string[]=resultWorkflow,binding=resultBinding,dual=resultDual)=>Either.right(assessment(t,r,evidenceDigest,chain,binding,dual,w))
 if(v.duplicate)return result("VOID_DUPLICATE_OCCURRENCE","duplicate occurrence observed");if(v.retry)return result("VOID_RETRY","retry observed")
 if([v.registration,v.dsse,v.rekor,v.rfc3161,v.prereg,v.worm,v.temporal,v.actor,v.drand,v.reveal,v.a,v.b,v.bridge,v.revision,v.audit].some(x=>x===null))return result("BLOCKED_EXTERNAL","required external evidence/audit is absent")
 const registration=v.registration!,dsse=v.dsse!,rekor=v.rekor!,rfc=v.rfc3161!,worm=v.worm!,temporal=v.temporal!,actor=v.actor!,drand=v.drand!,reveal=v.reveal!,a=v.a!,b=v.b!,bridge=v.bridge!,audit=v.audit!
 const componentFailure=validateComponents(v.prereg!,worm,temporal,actor,drand,reveal,a,b,bridge,audit);if(componentFailure!==null)return result("VOID_BINDING_CHAIN",componentFailure)
 const preregForResult=descriptorAt(v.prereg!,"manifest")!, claimForResult=descriptorAt(worm,"claim_manifest")!, launchForResult=descriptorAt(temporal,"launch_manifest")!, actorForResult=descriptorAt(actor,"manifest")!, verifierForResult=descriptorAt(drand,"verifier_receipt")!, revealForResult=descriptorAt(reveal,"manifest")!, bridgeForResult=descriptorAt(bridge,"bridge_manifest")!
 resultWorkflow=[preregForResult.sha256,claimForResult.sha256,launchForResult.sha256,actorForResult.sha256,verifierForResult.sha256,revealForResult.sha256,bridgeForResult.sha256]; resultDual=validShaAt(bridge,"dual_evaluation_evidence_sha256")!
 const auditChain=validShaAt(audit,"audited_chain_sha256");if(auditChain!==chain)return result("VOID_BINDING_CHAIN","external audit does not bind full chain")
 if(new Set([registration.kind,dsse.kind,rekor.kind,rfc.kind]).size!==4||!([registration.kind,dsse.kind,rekor.kind,rfc.kind].every(x=>["registration","dsse","rekor","rfc3161"].includes(x))))return result("BLOCKED_EXTERNAL","external evidence kinds incomplete")
 if(!same(registration.bound,dsse.bound)||!same(rekor.bound,dsse.receipt)||!same(rfc.bound,dsse.receipt))return result("VOID_BINDING_CHAIN","registration/DSSE/Rekor/TSA binding fails")
 const preregPackage=descriptorAt(v.prereg!,"registration_package"), preregPlan=validShaAt(v.prereg!,"plan_sha256"), preregChain=validShaAt(v.prereg!,"drand_chain_hash"), preregRound=numAt(v.prereg!,"drand_round"), preregPulse=numAt(v.prereg!,"pulse_unix");if(preregPackage===null||preregPlan===null||preregChain===null||preregRound===null||preregPulse===null||!same(registration.bound,preregPackage)||validShaAt(actor,"plan_sha256")!==preregPlan)return result("VOID_BINDING_CHAIN","registration readback is not transitively bound to actor plan")
 if(validShaAt(drand,"chain_hash")!==preregChain||numAt(drand,"round")!==preregRound||numAt(drand,"pulse_unix")!==preregPulse)return result("VOID_BINDING_CHAIN","verified drand chain/round/pulse differs from preregistration")
 const uid=typeof field(worm,"occurrence_uid")==="string"?field(worm,"occurrence_uid"):null;if(uid===null||![temporal,actor,drand,reveal,a,b].every(x=>field(x,"occurrence_uid")===uid))return result("VOID_DUPLICATE_OCCURRENCE","occurrence identifiers disagree")
 const pulse=field(drand,"pulse_unix"),sealed=field(actor,"sealed_unix"),retain=field(worm,"retain_until_unix");if(!integer(pulse)||!integer(sealed)||!integer(retain)||sealed>=pulse||field(reveal,"pulse_unix")!==pulse||retain<=pulse)return result("VOID_LATE_EVIDENCE","actor/pulse/reveal/WORM chronology fails")
 { const wr=descAt(temporal,"worm_claim_receipt"), we=obj(worm)&&obj(worm["evidence"])?descAt(worm["evidence"],"receipt"):null;if(wr===null||we===null||!same(wr,we))return result("VOID_BINDING_CHAIN","Temporal launch is not bound to exact WORM claim receipt") }
 if(!eqDesc(drand,"actor_manifest",actor,"manifest"))return result("VOID_BINDING_CHAIN","verified pulse is not bound to the pre-pulse actor manifest")
 if(!eqDesc(reveal,"outcome_bundle",drand,"outcome_bundle")||!eqDesc(a,"input",reveal,"evaluation_input")||!eqDesc(b,"input",reveal,"evaluation_input"))return result("VOID_BINDING_CHAIN","actor-to-pulse-to-reveal-to-evaluation digest chain fails")
 const wormEvidence=evidenceAt(worm,"evidence")!, temporalEvidence=evidenceAt(temporal,"evidence")!, actorEvidence=evidenceAt(actor,"evidence")!, revealEvidence=evidenceAt(reveal,"evidence")!, aEvidence=evidenceAt(a,"evidence")!, bEvidence=evidenceAt(b,"evidence")!, pulseTime=numAt(drand,"pulse_unix")!, sealedTime=numAt(actor,"sealed_unix")!, revealedTime=numAt(reveal,"revealed_unix")!, aTime=numAt(a,"evaluated_unix")!, bTime=numAt(b,"evaluated_unix")!
 if([registration,dsse,rekor,rfc,wormEvidence,temporalEvidence,actorEvidence].some(x=>x.observed>=pulseTime))return result("VOID_LATE_EVIDENCE","pre-pulse evidence is late")
 if(!(registration.observed<=dsse.observed&&dsse.observed<= (rekor.observed<rfc.observed?rekor.observed:rfc.observed)&&(rekor.observed>rfc.observed?rekor.observed:rfc.observed)<=wormEvidence.observed&&wormEvidence.observed<=temporalEvidence.observed&&temporalEvidence.observed<=sealedTime&&sealedTime<=actorEvidence.observed&&actorEvidence.observed<pulseTime))return result("VOID_LATE_EVIDENCE","pre-pulse evidence order fails")
 if(!(pulseTime<=revealedTime&&revealedTime<=revealEvidence.observed&&revealEvidence.observed<=(aTime<bTime?aTime:bTime)&&aTime<=aEvidence.observed&&bTime<=bEvidence.observed))return result("VOID_LATE_EVIDENCE","post-pulse evidence order fails")
 const roles=[roleAt(worm,"claimant"),roleAt(worm,"administrator"),roleAt(actor,"signer"),v.revision!,roleAt(drand,"verifier"),roleAt(reveal,"signer"),roleAt(a,"evaluator"),roleAt(b,"evaluator"),roleAt(audit,"auditor")];if(roles.some(x=>x===null)||v.revision!.role!=="revision_proposer"||!separate(roles as Role[]))return result("VOID_ROLE_SEPARATION","roles or issuers are not independently bound")
 const ai=descAt(a,"implementation"),bi=descAt(b,"implementation");if(ai===null||bi===null||ai.sha256===bi.sha256)return result("VOID_ROLE_SEPARATION","evaluator implementations are not distinct")
 if(!eqDesc(a,"input",b,"input")||validShaAt(a,"score_sha256")!==validShaAt(b,"score_sha256"))return result("VOID_EVALUATOR_DISAGREEMENT","independent evaluator outputs disagree")
 const ar=obj(a)&&obj(a["evidence"])?descAt(a["evidence"],"receipt"):null, br=obj(b)&&obj(b["evidence"])?descAt(b["evidence"],"receipt"):null, bar=descAt(bridge,"evaluator_a_receipt"), bbr=descAt(bridge,"evaluator_b_receipt");if(ar===null||br===null||bar===null||bbr===null||!same(ar,bar)||!same(br,bbr))return result("VOID_BINDING_CHAIN","dual-evaluation bridge does not bind exact central evaluator material")
 const bridgeManifest=descriptorAt(bridge,"bridge_manifest")!, preregManifest=descriptorAt(v.prereg!,"manifest")!, claimManifest=descriptorAt(worm,"claim_manifest")!, launchManifest=descriptorAt(temporal,"launch_manifest")!, actorManifest=descriptorAt(actor,"manifest")!, verifierReceipt=descriptorAt(drand,"verifier_receipt")!, revealManifest=descriptorAt(reveal,"manifest")!
 const binding=digest({schema:"hswm-dual-evaluation-binding/v1",judgment_a:{occurrence_uid:textAt(a,"occurrence_uid")!,role:canonRoleAt(a,"evaluator")!,input:canonDescriptorAt(a,"input")!,output:canonDescriptorAt(a,"output")!,task:canonDescriptorAt(a,"task")!,scorer:canonDescriptorAt(a,"scorer")!,config:canonDescriptorAt(a,"config")!,implementation:canonDescriptorAt(a,"implementation")!,score_sha256:validShaAt(a,"score_sha256")!,blind_to_arm_identity:true,signature_audit:canonDescriptorAt(a,"signature_audit")!,signature_receipt:ccd(ar)},judgment_b:{occurrence_uid:textAt(b,"occurrence_uid")!,role:canonRoleAt(b,"evaluator")!,input:canonDescriptorAt(b,"input")!,output:canonDescriptorAt(b,"output")!,task:canonDescriptorAt(b,"task")!,scorer:canonDescriptorAt(b,"scorer")!,config:canonDescriptorAt(b,"config")!,implementation:canonDescriptorAt(b,"implementation")!,score_sha256:validShaAt(b,"score_sha256")!,blind_to_arm_identity:true,signature_audit:canonDescriptorAt(b,"signature_audit")!,signature_receipt:ccd(br)}})
 return result("CANDIDATE_REQUIRES_EXTERNAL_AUDIT","claimed external-audit receipt binds this candidate; this module does not verify it and live audit remains mandatory",[preregManifest.sha256,claimManifest.sha256,launchManifest.sha256,actorManifest.sha256,verifierReceipt.sha256,revealManifest.sha256,bridgeManifest.sha256],binding,validShaAt(bridge,"dual_evaluation_evidence_sha256")!)
}
export const nativeAssessOccurrence = nativeAssessOccurrenceIntegrity
