#!/usr/bin/env node
/** Command process for bounded loopback research-fabric operations. */
import { Effect, Either, Layer } from "effect"
import { resolve } from "node:path"
import { homedir } from "node:os"
import { renderNativeTaskJson } from "./native-task-json-domain.js"
import { pathToFileURL } from "node:url"
import { RESEARCH_FABRIC_CLAIM_BOUNDARY, RESEARCH_FABRIC_STATUS_V1, fabricRefusal, fabricSpecs, selectedFabricSpecs } from "./native-research-fabric-domain.js"
import { NodeResearchFabricRuntimeLive, ResearchFabricRuntime, type ResearchFabricRuntimeError } from "./native-research-fabric-runtime.js"
import { BoundedSubprocess, NodeBoundedSubprocessLive } from "./effect-bounded-subprocess.js"
import { observedVersion, researchFabricEnvelope, researchFabricStatus, startResearchFabricService, stopResearchFabricService } from "./native-research-fabric.js"
import { runArgvProcessMain } from "./effect-process-main.js"

const usage="usage: hswm-research-fabric <start|stop|status|doctor> [--state-dir PATH] [--service all|phoenix|temporal] [--timeout SECONDS]\nBounded loopback infrastructure; not HSWM cognition or learning.\n"
const parse=(argv:ReadonlyArray<string>):Either.Either<{readonly command:string;readonly root:string;readonly service:string;readonly timeoutSeconds:number},ReturnType<typeof fabricRefusal>>=>{if(argv.includes("--help")||argv.includes("-h"))return Either.right({command:"help",root:"",service:"all",timeoutSeconds:90});let command:string|undefined;let root=process.env["HSWM_RESEARCH_FABRIC_STATE_DIR"]??`${process.env["HOME"]??"."}/.local/state/hswm-research-fabric`,service="all",timeoutSeconds=90;for(let index=0;index<argv.length;index+=1){const value=argv[index];if(value===undefined)continue;if(!value.startsWith("--")){if(command!==undefined)return Either.left(fabricRefusal("exactly one command is required"));command=value;continue}const next=argv[index+1];if(next===undefined)return Either.left(fabricRefusal(`missing value for ${value}`));if(value==="--state-dir")root=next;else if(value==="--service")service=next;else if(value==="--timeout")timeoutSeconds=Number(next);else return Either.left(fabricRefusal(`unknown option ${value}`));index+=1}return command===undefined?Either.left(fabricRefusal("a command is required")):Either.right({command,root:resolve(root === "~" ? homedir() : root.startsWith("~/") ? `${homedir()}/${root.slice(2)}` : root),service,timeoutSeconds})}
const doctor=(root:string,specs:ReturnType<typeof fabricSpecs>):Effect.Effect<string,ReturnType<typeof fabricRefusal>|ResearchFabricRuntimeError,ResearchFabricRuntime|BoundedSubprocess>=>Effect.gen(function*(){const host=yield* ResearchFabricRuntime;const services=yield* Effect.all([researchFabricStatus(root,specs.phoenix),researchFabricStatus(root,specs.temporal)]);const dependencies=yield* Effect.all([{name:"openobserve-canonical",host:"192.168.0.27",port:5081,health:"http://192.168.0.27:5081/healthz",responsibility:"generic operational log and trace projection"},{name:"neo4j-canonical-kg",host:"192.168.0.25",port:7687,health:null,responsibility:"bounded canonical-KG projection; not HSWM state authority"},{name:"neo4j-code-kg",host:"192.168.0.19",port:7687,health:null,responsibility:"bounded code-graph projection"},{name:"grafana-mcp",host:"192.168.0.29",port:9090,health:null,responsibility:"bounded observability query interface"}].map((item)=>Effect.gen(function*(){const tcp=yield* host.tcpReady(item.host,item.port),http=item.health===null?null:yield* host.httpReady(item.health);return {name:item.name,endpoint:`${item.host}:${item.port}`,tcp,http:http?.[0]??null,http_status:http?.[1]??null,ready:tcp&&(http===null||http[0]),responsibility:item.responsibility}})));const executables=yield* Effect.all([specs.phoenix,specs.temporal].map((spec)=>Effect.gen(function*(){const executable=yield* host.executable(spec.executable),environment=yield* host.environment,version=executable===null?null:yield* observedVersion(spec,executable.realpath,Object.fromEntries(Object.entries(environment).filter(([,value])=>value!==undefined)) as Record<string,string>);return {service:spec.name,path:spec.executable,present:executable!==null,sha256:executable?.sha256??null,expected_sha256:spec.expectedExecutableSha256,sha256_match:spec.expectedExecutableSha256===null||executable?.sha256===spec.expectedExecutableSha256,version,expected_version:spec.expectedVersion,version_match:version===spec.expectedVersion}})));const ready=services.every((item)=>item["state"]==="ready")&&dependencies.every((item)=>item.ready)&&executables.every((item)=>item.version_match&&item.sha256_match);return renderNativeTaskJson({schema:RESEARCH_FABRIC_STATUS_V1,claim_boundary:RESEARCH_FABRIC_CLAIM_BOUNDARY,observed_unix_ns:yield* host.nowUnixNs,state_root:root,ready,services,executables,existing_proxmox_dependencies:dependencies},"pretty")+"\n"})
export const runNativeResearchFabricProcess=(argv:ReadonlyArray<string>):Effect.Effect<{readonly stdout:string;readonly exitCode:number},ReturnType<typeof fabricRefusal>|ResearchFabricRuntimeError,ResearchFabricRuntime|BoundedSubprocess>=>Effect.gen(function*(){const options=parse(argv);if(Either.isLeft(options))return yield* Effect.fail(options.left);if(options.right.command==="help")return {stdout:usage,exitCode:0};const specs=fabricSpecs(options.right.root,`${process.env["HOME"]??"."}/.local/bin`),selected=selectedFabricSpecs(specs,options.right.service);if(Either.isLeft(selected))return yield* Effect.fail(selected.left);if(options.right.command==="doctor"){const output=yield* doctor(options.right.root,specs);return {stdout:output,exitCode:JSON.parse(output).ready===true?0:1}}if(!["status","start","stop"].includes(options.right.command))return yield* Effect.fail(fabricRefusal("command must be start, stop, status, or doctor"));const timeoutMs=options.right.timeoutSeconds*1_000;if(!Number.isFinite(timeoutMs)||timeoutMs<=0)return yield* Effect.fail(fabricRefusal("--timeout must be a positive number of seconds"));const ordered=options.right.command==="stop"?[...selected.right].reverse():selected.right;const serviceResults=yield* Effect.forEach(ordered,(spec)=>options.right.command==="status"?researchFabricStatus(options.right.root,spec):options.right.command==="start"?startResearchFabricService(options.right.root,spec,timeoutMs):stopResearchFabricService(options.right.root,spec,10_000));const envelope=researchFabricEnvelope(options.right.root,serviceResults);return {stdout:JSON.stringify(envelope,null,2)+"\n",exitCode:options.right.command==="stop"||serviceResults.every((item)=>item["state"]==="ready")?0:1}})
export const runNativeResearchFabricNodeProcess=(argv:ReadonlyArray<string>)=>runNativeResearchFabricProcess(argv).pipe(Effect.provide(Layer.merge(NodeResearchFabricRuntimeLive,NodeBoundedSubprocessLive)))
if(import.meta.url===pathToFileURL(process.argv[1]??"").href)process.exitCode=await runArgvProcessMain({program:runNativeResearchFabricNodeProcess,describeFailure:(error)=>JSON.stringify({schema:RESEARCH_FABRIC_STATUS_V1,claim_boundary:RESEARCH_FABRIC_CLAIM_BOUNDARY,error:error.detail})},process.argv.slice(2))
