/** Immutable, adapter-neutral one-shot occurrence workflow. */
import { Data, Either } from "effect"
import { makeNativeIssuedRecordFactory } from "./native-issued-record-domain.js"
import type { TaskJson } from "./native-task-json-domain.js"
export const NATIVE_OCCURRENCE_WORKFLOW_SCHEMA="hswm-g0-occurrence-one-shot-workflow/v1" as const
export const NATIVE_OCCURRENCE_LAUNCH_OPTIONS_SCHEMA="hswm-g0-occurrence-temporal-launch-options/v1" as const
export const NATIVE_OCCURRENCE_WORKFLOW_ID_PREFIX="g0-occurrence/" as const
export type NativeOccurrencePhase="REGISTERED"|"CLAIMED"|"SCHEDULED"|"PRE_PULSE_SEALED"|"PULSE_VERIFIED"|"REVEALED"|"DUAL_EVALUATED"|"SEALED"|"VOID"
export type NativePulseTiming="PRE_PULSE"|"POST_PULSE"
export type NativeVoidReason="DUPLICATE_OR_RETRY"|"LATE"|"ORDER"|"INVALID_EVIDENCE_DESCRIPTOR"|"TERMINAL_REENTRY"
export class NativeOccurrenceWorkflowError extends Data.TaggedError("NativeOccurrenceWorkflowError")<{readonly detail:string}>{}
export interface NativeOccurrenceWorkflowState {readonly occurrenceUid:string;readonly phase:NativeOccurrencePhase;readonly evidenceSha256s:readonly string[];readonly voidReason:NativeVoidReason|null;readonly rejectedEvidenceSha256:string|null;readonly schemaVersion:typeof NATIVE_OCCURRENCE_WORKFLOW_SCHEMA}
const failure=<A=never>(detail:string):Either.Either<A,NativeOccurrenceWorkflowError>=>Either.left(new NativeOccurrenceWorkflowError({detail}))
const uid=(value:string):boolean=>/^[A-Za-z][A-Za-z0-9._:-]{0,127}$/.test(value)
const sha=(value:string):boolean=>/^[0-9a-f]{64}$/.test(value)
const phases:readonly NativeOccurrencePhase[]=["REGISTERED","CLAIMED","SCHEDULED","PRE_PULSE_SEALED","PULSE_VERIFIED","REVEALED","DUAL_EVALUATED","SEALED","VOID"]
const voids:readonly NativeVoidReason[]=["DUPLICATE_OR_RETRY","LATE","ORDER","INVALID_EVIDENCE_DESCRIPTOR","TERMINAL_REENTRY"]
const next:Readonly<Record<Exclude<NativeOccurrencePhase,"SEALED"|"VOID">,NativeOccurrencePhase>>={REGISTERED:"CLAIMED",CLAIMED:"SCHEDULED",SCHEDULED:"PRE_PULSE_SEALED",PRE_PULSE_SEALED:"PULSE_VERIFIED",PULSE_VERIFIED:"REVEALED",REVEALED:"DUAL_EVALUATED",DUAL_EVALUATED:"SEALED"}
const workflowRecords=makeNativeIssuedRecordFactory<NativeOccurrenceWorkflowState>()
export const isNativeOccurrenceWorkflowState=workflowRecords.isIssued
export const nativeOccurrenceWorkflowCanonical=(value:NativeOccurrenceWorkflowState):Either.Either<TaskJson,NativeOccurrenceWorkflowError>=>workflowRecords.isIssued(value)?Either.right({occurrence_uid:value.occurrenceUid,phase:value.phase,evidence_sha256s:value.evidenceSha256s,void_reason:value.voidReason,rejected_evidence_sha256:value.rejectedEvidenceSha256,schema_version:value.schemaVersion}):failure("workflow state was not issued by registered/advance occurrence")
const state=(occurrenceUid:string,phase:NativeOccurrencePhase,evidenceSha256s:readonly string[],voidReason:NativeVoidReason|null=null,rejectedEvidenceSha256:string|null=null):NativeOccurrenceWorkflowState=>workflowRecords.issue({occurrenceUid,phase,evidenceSha256s:Object.freeze([...evidenceSha256s]),voidReason,rejectedEvidenceSha256,schemaVersion:NATIVE_OCCURRENCE_WORKFLOW_SCHEMA})
const voidState=(current:NativeOccurrenceWorkflowState,reason:NativeVoidReason,rejected?:string):NativeOccurrenceWorkflowState=>state(current.occurrenceUid,"VOID",current.evidenceSha256s,reason,rejected!==undefined&&sha(rejected)?rejected:null)
export const registeredNativeOccurrence=(occurrenceUid:string,registrationEvidenceSha256:string):Either.Either<NativeOccurrenceWorkflowState,NativeOccurrenceWorkflowError>=>!uid(occurrenceUid)?failure("occurrence_uid must be a bounded stable identifier"):!sha(registrationEvidenceSha256)?failure("evidence descriptor must be lowercase SHA-256"):Either.right(state(occurrenceUid,"REGISTERED",[registrationEvidenceSha256]))
export const advanceNativeOccurrence=(current:NativeOccurrenceWorkflowState,nextPhase:unknown,evidenceSha256:string,timing:unknown):Either.Either<NativeOccurrenceWorkflowState,NativeOccurrenceWorkflowError>=>{if(!workflowRecords.isIssued(current)||!uid(current.occurrenceUid)||!phases.includes(current.phase)||current.schemaVersion!==NATIVE_OCCURRENCE_WORKFLOW_SCHEMA||current.evidenceSha256s.some(item=>!sha(item)))return failure("invalid occurrence workflow state");if(current.phase==="VOID")return Either.right(current);if(current.phase==="SEALED")return Either.right(voidState(current,"TERMINAL_REENTRY",evidenceSha256));if(!phases.includes(nextPhase as NativeOccurrencePhase)||!(timing==="PRE_PULSE"||timing==="POST_PULSE"))return Either.right(voidState(current,"ORDER",evidenceSha256));const phase=nextPhase as NativeOccurrencePhase;if(!sha(evidenceSha256))return Either.right(voidState(current,"INVALID_EVIDENCE_DESCRIPTOR"));if(current.evidenceSha256s.includes(evidenceSha256)||phase===current.phase)return Either.right(voidState(current,"DUPLICATE_OR_RETRY",evidenceSha256));if(next[current.phase]!==phase)return Either.right(voidState(current,"ORDER",evidenceSha256));const required=["CLAIMED","SCHEDULED","PRE_PULSE_SEALED"].includes(phase)?"PRE_PULSE":"POST_PULSE";return timing!==required?Either.right(voidState(current,"LATE",evidenceSha256)):Either.right(state(current.occurrenceUid,phase,current.evidenceSha256s.concat(evidenceSha256)))}
export const voidNativeOccurrence=(current:NativeOccurrenceWorkflowState,reason:unknown,rejectedEvidenceSha256?:string):Either.Either<NativeOccurrenceWorkflowState,NativeOccurrenceWorkflowError>=>!workflowRecords.isIssued(current)?failure("workflow state was not issued by registered/advance occurrence"):!voids.includes(reason as NativeVoidReason)?failure("reason must be VoidReason"):current.phase==="VOID"?Either.right(current):Either.right(voidState(current,reason as NativeVoidReason,rejectedEvidenceSha256))
export const nativeTemporalOneShotLaunchOptions=(occurrenceUid:string):Either.Either<Readonly<Record<string,unknown>>,NativeOccurrenceWorkflowError>=>!uid(occurrenceUid)?failure("occurrence_uid must be a bounded stable identifier"):Either.right(Object.freeze({activity_retry_policy:Object.freeze({maximum_attempts:1}),occurrence_uid:occurrenceUid,replacement_round_allowed:false,schema_version:NATIVE_OCCURRENCE_LAUNCH_OPTIONS_SCHEMA,workflow_id:`${NATIVE_OCCURRENCE_WORKFLOW_ID_PREFIX}${occurrenceUid}`,workflow_id_reuse_policy:"REJECT_DUPLICATE",workflow_retry_policy:Object.freeze({maximum_attempts:1})}))
