PREFIX kbp: <https://hswm.invalid/kg-bundle-rdf/v1/prop/>
PREFIX kbr: <https://hswm.invalid/kg-bundle-rdf/v1/rel/>
SELECT ?node ?role ?status WHERE { <urn:hswm:kg:node:sym:AbstractNode:hswm-ice-graph-implementation-wp0-3-2026-09-08-v1> kbr:HAS_CONCEPT ?node . ?node kbp:role ?role ; kbp:status ?status . } ORDER BY ?role ?node
