import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { digest } from './domain.mts';
const dir='docs/research/artifacts/hswm_jev_principles_2026-09-21';
const write=(p:string,v:unknown)=>writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const runtime='src/hswm/effect-runtime/src/canonical-atom-v2-llm-semantic-runtime.ts';
const rows:any[]=[
 ['P1','Typed decision readout','Local LLM relation execution and trace','IMPLEMENTED_MEASURED_RESEARCH_ONLY','Fast and structurally reliable here; no overall semantic-quality gain.',['CR-0','CR-1','FCL-1'],'https://docs.typesafe.ai/primitives','src/hswm/effect-runtime/src/semantic-decision-domain.ts','Same-case meaning accuracy and refusal-aware proper scores.'],
 ['P2','Outcome-fitted probability assessment','Version-bound prediction assessment in the same semantic graph loop','IMPLEMENTED_POSTHOC_NOT_CANONICAL_LEARNING','Overconfidence shrank; direct probabilities remain worse than p=0.5.',['CR-1','CR-2','CR-3','FCL-1','FCL-4'],'https://docs.typesafe.ai/introduction/machine-learning-primer','src/hswm/effect-runtime/src/semantic-decision-domain.ts','Independent outcomes, held-out calibration, drift and causal-credit separation.'],
 ['P3','Shared-state computation','Snapshot-bound scheduling of dependency-free local LLM reads','DESIGN_ONLY_NOT_MEASURED','Serial latency does not establish shared-trunk or parallel-head gains.',['CR-0','CR-6','FCL-2'],'https://docs.typesafe.ai/primitives',runtime,'Preserve dependencies and serializable revisions; compare actual shared compute at equal quality.'],
 ['P4','Dynamic candidate and read construction','Role-bearing relation proposals and local read scope','HSWM_EXTENSION_NOT_IMPLEMENTED','Fixed binary support and no-op proposals do not discover relations.',['CR-4','FCL-3','FCL-5'],'docs/research/HSWM_LLM_SEMANTIC_GRAPH_IMPLEMENTATION_2026-09-14.md',runtime,'Candidate recall, none/expand, context sufficiency and fixed-topology controls.'],
 ['P5','Joint output-law preservation','Ordered n-ary role incidence and joint transition messages','HSWM_REQUIREMENT_NOT_MEASURED','Computationally independent questions do not imply statistical independence.',['CR-4','CR-5','FCL-3','FCL-5','FCL-6'],'docs/research/HSWM_SEMANTIC_WEIGHT_DEFINITION_AND_HYPERGRAPH_2026-09-14.md','formal/HSWMSemanticWeightDefinition.lean','Test exclusion/complementarity and higher-order response; do not multiply marginals without assumptions.'],
 ['P6','Typed recursive composition','Cognition-bearing HSWM cells composing under the same Step/Learn','HSWM_TRANSFER_HYPOTHESIS_NOT_IMPLEMENTED','No measured two-scale closure or continuity.',['CR-5','CR-6','CR-7','FCL-2','FCL-6','FCL-7','FCL-8'],'docs/research/HSWM_FRACTAL_SCIENTIFIC_CONNECTIONS_2026-08-28.md','ontology/identity/human_universal_body/HSWM_FRACTAL_SCIENTIFIC_CONNECTIONS_ONTOLOGY.v1.json','Preserve effects, rights, exit, lineage and calibration in concrete two-scale interventions.']
];
const catalog={schema_version:'hswm-jev-principle-applicability/v1',date:'2026-09-21',authority:'SECONDARY_AI',principles:rows.map(([id,name,structure,status,finding,obligations,source,implementation,limitation])=>({id,name,structure,status,finding,obligations,source,implementation,limitation})),
 standards:[{name:'SHACL 1.0',url:'https://www.w3.org/TR/shacl/',status:'W3C_RECOMMENDATION'},{name:'SPARQL 1.1 Query',url:'https://www.w3.org/TR/sparql11-query/',status:'W3C_RECOMMENDATION'},{name:'N-ary relations pattern',url:'https://www.w3.org/TR/swbp-n-aryRelations/',status:'W3C_WORKING_GROUP_NOTE_NOT_RECOMMENDATION'}],
 papers:[{title:'On Calibration of Modern Neural Networks',url:'https://proceedings.mlr.press/v70/guo17a.html',role:'Temperature scaling foundation, independent of Jev; not a guarantee of HSWM calibration'},{title:'Strictly Proper Scoring Rules, Prediction, and Estimation',url:'https://sites.stat.washington.edu/raftery/Research/PDF/Gneiting2007jasa.pdf',role:'Proper scoring foundation, not empirical calibration evidence'}],
 mandatory_comparator:{name:'OpenCog Hyperon',metta_version:'0.2.10',metta_commit:'3f76dc460da6961f57f69f6c3e550c59c74ada83',source:'docs/research/HYPERON_2026_DIRECT_PRIOR_DEEP_DIVE_2026-08-20.md',status:'PINNED_PRIOR_AUDIT_NOT_EXECUTED_IN_THIS_STUDY'}};
for(const p of catalog.principles)if(!existsSync(p.implementation))throw Error('Unknown implementation path '+p.implementation);
write(dir+'/applicability.v1.json',catalog);
write(dir+'/validation.v1.json',{schema_version:'hswm-jevp-engineering-validation/v1',date:'2026-09-21',native_build:'PASS',native_full_check:'PASS',decision_domain_tests:{passed:5},hswm_dev:{episode:'8ed52606-bf1b-4102-b0cb-db174692811d',relation:'relation:runtime-focused',tests_passed:55,feedback_source:'agent(codex): Useful native development regression evidence; 55 checks passed. This is agent usefulness feedback, not user feedback or evidence of DGX semantic efficacy.',feedback_is_user_feedback:false},evaluation_request_response_audits:960,learning_request_response_audits:8,remote_staged_artifact_hashes_verified:315,durable_and_local_archive_hash_match:true,claim:'ENGINEERING_INSTRUMENT_VALIDATION_NOT_EFFICACY'});
const receipt={schema_version:'hswm-jevp-material-research-receipt/v1',date:'2026-09-21',run_id:'hswm-jev-principles-20260921-v1',execution_status:'COMPLETE',scientific_status:'READOUT_ENGINEERING_GAIN_NO_SEMANTIC_LEARNING_GAIN',durable_archive:'data01:/mnt/hswm/runs/hswm-jev-principles-20260921-v1/artifacts.tar',archive_sha256:'4fe1df37b77a2456d037c74efae1dae46ca91e430e9f0651afcca569017d827d',original_wrapper_receipt_sha256:'dd80d07b9e72b626665b55ed9c78b35ab81587fa9a25ea3aa6b67dc2992f60c5',source_manifest_sha256:digest(readFileSync('_research/jev_principles_v1/source-pins.v1.json')),wrapper_checkout_commit:'3d7485befbf7d6847018c80d46ad4a00c294ed2d',manifest_base_commit:'2d8a27e2d9ab9460817235fe6775a940b7db95f9',commit_boundary:'Staged artifacts pinned individually; remote wrapper HEAD is not their identity.',http_calls:968,meaning_changes:0,admitted_revisions:4,artifacts:['observations.v1.json','audit.v1.json','applicability.v1.json','validation.v1.json'].map(n=>({path:dir+'/'+n,sha256:digest(readFileSync(dir+'/'+n))})),cr_fcl_promotion:false};
const raw=JSON.stringify(receipt,null,2)+'\n',rd='evidence/hswm_jev_principles_2026-09-21';mkdirSync(rd,{recursive:true});const receiptPath=rd+'/'+digest(raw)+'.json';writeFileSync(receiptPath,raw,{flag:'wx'});console.log(JSON.stringify({receipt_path:receiptPath,principles:catalog.principles.length}));
